/**
 * Árbol de habilidades: **Ciencia** — quinta disciplina de SkillTree, sembrada
 * en construcción (DRAFT): íntegra en la base de datos pero AÚN NO visible.
 *
 * No es un temario: es un DAG de competencias diseñado a partir de patrones
 * comunes a referencias reconocidas —NGSS (prácticas científicas + conceptos
 * transversales + ideas centrales), Khan Academy y OpenStax (fundamentos por
 * dominio), MIT OCW, CK-12, NASA y National Geographic Education, Nature
 * Education y Britannica— y de la investigación en didáctica de las ciencias.
 *
 * Principio rector (NGSS + investigación): enseñar a PENSAR científicamente
 * —observar, preguntar, buscar evidencia, modelar— y DESMONTAR ideas erróneas
 * intuitivas ANTES que memorizar hechos. Por eso el árbol nace en el pensamiento
 * científico y el método, y cada habilidad cuida especialmente los "errores
 * frecuentes" (las misconceptions son el corazón de aprender ciencia).
 *
 * Reutiliza al 100% el motor genérico (`upsertTree`): mismo modelo de lección,
 * mismos tipos de ejercicio, XP, repaso espaciado, logros y reproductor. No
 * añade ninguna excepción al motor.
 */

import type { SeedRes, TreeSpec } from "./lib";
import { CIE_LESSONS } from "./ciencia-lessons";

const R = {
  khan: (title: string): SeedRes => ({
    t: "VIDEO",
    title,
    url: "https://es.khanacademy.org/science",
    p: "Khan Academy",
  }),
  openstax: (title: string): SeedRes => ({
    t: "BOOK",
    title,
    url: "https://openstax.org/subjects/science",
    p: "OpenStax",
  }),
  ck12: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://www.ck12.org/",
    p: "CK-12",
  }),
  phet: (title: string): SeedRes => ({
    t: "EXERCISE",
    title,
    url: "https://phet.colorado.edu/es/",
    p: "PhET (Colorado)",
  }),
  nasa: (title: string): SeedRes => ({
    t: "OTHER",
    title,
    url: "https://science.nasa.gov/",
    p: "NASA Science",
  }),
  natgeo: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://education.nationalgeographic.org/",
    p: "Nat Geo Education",
  }),
};

export const CIENCIA_SPEC: TreeSpec = {
  category: {
    slug: "ciencia",
    name: "Ciencia",
    description:
      "Aprende a pensar como un científico: observa, pregunta, busca evidencia y entiende cómo funciona el mundo, de lo diminuto al cosmos.",
    icon: "🔬",
    order: 4,
  },
  tree: {
    slug: "ciencia-de-cero",
    title: "Ciencia · de cero a pensar como científico",
    description:
      "Desde el pensamiento científico hasta la materia, la energía, la vida, la Tierra y el cosmos. Aprende a razonar con evidencia y a desmontar ideas erróneas, no a memorizar. Un árbol de competencias con libertad para elegir por dónde empezar.",
    difficulty: "beginner",
    status: "PUBLISHED",
  },
  branches: {
    pensamiento: "Pensamiento científico",
    metodo: "Método científico y datos",
    materia: "Materia y sus estados",
    quimica: "Química: átomos y reacciones",
    energia: "Energía, fuerzas y movimiento",
    vida: "Biología: la vida",
    genetica: "Genética y evolución",
    tierra: "Ciencias de la Tierra",
    cosmos: "Astronomía y el universo",
    ecologia: "Ecología y medio ambiente",
    hito: "Hitos",
  },
  levels: ["Fundamentos", "Básico", "Intermedio", "Avanzado"],
  lessons: CIE_LESSONS,
  nodes: [
    // ───────────── Pensamiento científico ─────────────
    {
      s: "cie-que-es",
      b: "pensamiento",
      lv: 0,
      t: "Qué es la ciencia",
      root: true,
      pre: [],
      d: "La ciencia como forma de conocer basada en evidencia, no en autoridad ni opinión.",
      o: "Entender la ciencia como una manera de preguntar y responder con evidencia.",
      c: "Naturaleza de la ciencia.",
      w: "Sin entender qué es (y qué no es) la ciencia, se confunde con dogma o con opinión.",
      df: "easy",
      m: 25,
      xp: 10,
      er: ["Creer que la ciencia son 'hechos fijos' que no cambian.", "Confundir teoría científica con 'suposición'."],
      cr: ["Explicas por qué la ciencia se basa en evidencia y puede corregirse."],
      ex: ["Distinguir una afirmación científica de una opinión."],
      ev: ["Dar un ejemplo de idea científica que cambió con nueva evidencia."],
      r: [R.khan("Qué es la ciencia"), R.natgeo("Nature of science")],
    },
    {
      s: "cie-observacion",
      b: "pensamiento",
      lv: 0,
      t: "Observar y preguntar",
      pre: ["cie-que-es"],
      d: "La observación cuidadosa y la distinción entre observar e inferir.",
      o: "Distinguir una observación de una inferencia.",
      c: "Observación científica.",
      w: "Confundir lo que ves con lo que supones es el primer error de todo aprendiz de ciencia.",
      df: "easy",
      m: 30,
      xp: 12,
      er: ["Mezclar observación ('la calle está mojada') con inferencia ('llovió')."],
      cr: ["Separas observaciones de inferencias en una escena."],
      ex: ["Describir una foto solo con observaciones."],
      ev: ["Clasificar frases como observación o inferencia."],
      r: [R.ck12("Observación e inferencia"), R.khan("Observar")],
    },
    {
      s: "cie-evidencia",
      b: "pensamiento",
      lv: 1,
      t: "Evidencia y escepticismo",
      pre: ["cie-observacion"],
      d: "Toda afirmación necesita evidencia; correlación no implica causalidad.",
      o: "Exigir evidencia y evitar la trampa correlación-causalidad.",
      c: "Razonamiento con evidencia.",
      w: "Es la vacuna contra bulos y pseudociencia: pedir pruebas y dudar con criterio.",
      df: "medium",
      m: 35,
      xp: 14,
      er: ["Suponer que si dos cosas van juntas, una causa la otra.", "Aceptar una afirmación por quién la dice."],
      cr: ["Detectas una conclusión que confunde correlación con causa."],
      ex: ["Analizar un titular que confunde correlación y causa."],
      ev: ["Proponer qué evidencia haría falta para creer una afirmación."],
      r: [R.khan("Correlación y causalidad"), R.natgeo("Evidence")],
    },
    {
      s: "cie-modelos",
      b: "pensamiento",
      lv: 2,
      t: "Modelos científicos",
      pre: ["cie-evidencia"],
      d: "Un modelo representa la realidad de forma simplificada y útil, aunque no perfecta.",
      o: "Entender qué es (y qué no es) un modelo científico.",
      c: "Modelización.",
      w: "Casi toda la ciencia trabaja con modelos; confundirlos con la realidad lleva a errores.",
      df: "medium",
      m: 35,
      xp: 16,
      er: ["Creer que un modelo (p. ej. del átomo) es una foto exacta de la realidad."],
      cr: ["Explicas para qué sirve un modelo y sus límites."],
      ex: ["Comparar un mapa con el territorio real."],
      ev: ["Señalar una simplificación útil de un modelo conocido."],
      r: [R.ck12("Modelos científicos"), R.phet("Simulaciones")],
    },

    // ───────────── Método científico y datos ─────────────
    {
      s: "cie-metodo",
      b: "metodo",
      lv: 1,
      t: "El método científico",
      pre: ["cie-observacion"],
      d: "Del interrogante a la conclusión: pregunta, hipótesis, experimento, datos, conclusión.",
      o: "Aplicar el ciclo del método científico a una pregunta sencilla.",
      c: "Método científico.",
      w: "Es el motor que convierte curiosidad en conocimiento fiable.",
      df: "medium",
      m: 35,
      xp: 16,
      er: ["Creer que el método es una receta rígida de pasos fijos.", "Confundir hipótesis con 'adivinar'."],
      cr: ["Planteas hipótesis comprobable para una pregunta."],
      ex: ["Diseñar un experimento para '¿las plantas crecen más con música?'."],
      ev: ["Formular una hipótesis que se pueda poner a prueba."],
      r: [R.khan("Método científico"), R.ck12("Scientific method")],
    },
    {
      s: "cie-variables",
      b: "metodo",
      lv: 2,
      t: "Variables y experimentos controlados",
      pre: ["cie-metodo"],
      d: "Variable independiente, dependiente y de control; cambiar una cosa a la vez.",
      o: "Diseñar un experimento controlado cambiando una sola variable.",
      c: "Diseño experimental.",
      w: "Sin control de variables, un experimento no prueba nada.",
      df: "hard",
      m: 40,
      xp: 18,
      er: ["Cambiar varias variables a la vez y no saber cuál causó el efecto.", "Olvidar el grupo de control."],
      cr: ["Identificas variable independiente, dependiente y control."],
      ex: ["Diseñar un test de fertilizante con grupo de control."],
      ev: ["Detectar la variable no controlada en un experimento."],
      r: [R.khan("Variables"), R.phet("Diseño experimental")],
    },
    {
      s: "cie-datos",
      b: "metodo",
      lv: 2,
      t: "Datos, gráficas e incertidumbre",
      pre: ["cie-variables"],
      d: "Medir, representar datos y entender que toda medida tiene error.",
      o: "Interpretar datos en una gráfica y reconocer su incertidumbre.",
      c: "Análisis de datos.",
      w: "Los datos solo hablan si se representan y se leen con honestidad.",
      df: "hard",
      m: 40,
      xp: 18,
      er: ["Leer una gráfica sin mirar los ejes.", "Creer que una medida es exacta al infinito."],
      cr: ["Extraes una tendencia de una gráfica leyendo sus ejes."],
      ex: ["Graficar temperatura frente a tiempo."],
      ev: ["Detectar una gráfica engañosa (eje truncado)."],
      r: [R.khan("Interpretar datos"), R.openstax("Data & graphs")],
    },

    // ───────────── Materia y sus estados ─────────────
    {
      s: "cie-materia",
      b: "materia",
      lv: 1,
      t: "Qué es la materia",
      pre: ["cie-que-es"],
      d: "Todo lo que tiene masa y ocupa espacio; masa vs. volumen.",
      o: "Entender la materia por sus propiedades (masa y volumen).",
      c: "Concepto de materia.",
      w: "Es la base de la química y de entender de qué está hecho el mundo.",
      df: "easy",
      m: 30,
      xp: 12,
      er: ["Creer que el aire 'no es materia' porque no se ve.", "Confundir masa con peso."],
      cr: ["Distingues masa de volumen y de peso."],
      ex: ["Demostrar que el aire ocupa espacio (globo)."],
      ev: ["Clasificar si algo es o no materia."],
      r: [R.ck12("Materia"), R.khan("Propiedades de la materia")],
    },
    {
      s: "cie-estados",
      b: "materia",
      lv: 1,
      t: "Estados de la materia",
      pre: ["cie-materia"],
      d: "Sólido, líquido y gas según cómo se mueven y ordenan las partículas.",
      o: "Explicar los estados por el movimiento de las partículas.",
      c: "Estados de la materia.",
      w: "Introduce el modelo de partículas, clave para toda la química.",
      df: "medium",
      m: 35,
      xp: 14,
      er: ["Creer que las partículas de un sólido están 'quietas' del todo.", "Pensar que al hervir el agua 'desaparece'."],
      cr: ["Relacionas cada estado con el movimiento de sus partículas."],
      ex: ["Explicar la fusión del hielo con partículas."],
      ev: ["Predecir el estado según la energía de las partículas."],
      r: [R.phet("Estados de la materia"), R.ck12("States of matter")],
    },
    {
      s: "cie-atomos",
      b: "materia",
      lv: 2,
      t: "Átomos y elementos",
      pre: ["cie-estados"],
      d: "El átomo como unidad básica; los elementos como tipos de átomo.",
      o: "Entender que toda la materia está hecha de átomos de unos pocos elementos.",
      c: "Teoría atómica.",
      w: "Los átomos explican por qué existen distintos materiales.",
      df: "medium",
      m: 40,
      xp: 16,
      er: ["Imaginar el átomo como una bolita sólida.", "Confundir átomo con molécula."],
      cr: ["Distingues átomo, elemento y molécula."],
      ex: ["Representar una molécula de agua (H₂O)."],
      ev: ["Decir cuántos elementos hay en el agua y el CO₂."],
      r: [R.ck12("Átomos"), R.khan("Estructura atómica")],
    },
    {
      s: "cie-mezclas",
      b: "materia",
      lv: 2,
      t: "Mezclas y sustancias puras",
      pre: ["cie-atomos"],
      d: "Diferencia entre mezcla y sustancia pura; métodos de separación.",
      o: "Distinguir mezclas de sustancias puras y separarlas.",
      c: "Clasificación de la materia.",
      w: "Casi todo lo que nos rodea son mezclas; separarlas es química cotidiana.",
      df: "medium",
      m: 35,
      xp: 16,
      er: ["Creer que una disolución transparente es 'pura'."],
      cr: ["Clasificas materiales como mezcla o sustancia pura."],
      ex: ["Separar sal y agua por evaporación."],
      ev: ["Elegir un método para separar una mezcla dada."],
      r: [R.ck12("Mezclas"), R.khan("Mezclas y sustancias")],
    },

    // ───────────── Química: átomos y reacciones ─────────────
    {
      s: "cie-tabla",
      b: "quimica",
      lv: 2,
      t: "La tabla periódica",
      pre: ["cie-atomos"],
      d: "Cómo se organizan los elementos y qué predice su posición.",
      o: "Leer la tabla periódica y entender su lógica.",
      c: "Organización de los elementos.",
      w: "La tabla es el mapa de toda la química; su orden no es casual.",
      df: "hard",
      m: 45,
      xp: 20,
      er: ["Verla como una lista al azar en vez de un patrón."],
      cr: ["Localizas un elemento y lees su símbolo y número."],
      ex: ["Situar el oxígeno y el hierro en la tabla."],
      ev: ["Predecir un rasgo por la columna del elemento."],
      r: [R.khan("Tabla periódica"), R.ck12("Periodic table")],
    },
    {
      s: "cie-enlaces",
      b: "quimica",
      lv: 3,
      t: "Enlaces y moléculas",
      pre: ["cie-tabla"],
      d: "Cómo se unen los átomos para formar moléculas y compuestos.",
      o: "Entender por qué y cómo se enlazan los átomos.",
      c: "Enlace químico.",
      w: "Los enlaces explican por qué existen millones de sustancias distintas.",
      df: "hard",
      m: 50,
      xp: 22,
      er: ["Creer que los átomos se unen 'porque sí'."],
      cr: ["Explicas a alto nivel por qué se forma una molécula."],
      ex: ["Describir el enlace en la molécula de agua."],
      ev: ["Distinguir un elemento de un compuesto."],
      r: [R.khan("Enlaces químicos"), R.ck12("Chemical bonds")],
    },
    {
      s: "cie-reacciones",
      b: "quimica",
      lv: 3,
      t: "Reacciones químicas",
      pre: ["cie-enlaces"],
      d: "Los átomos se reorganizan; la masa se conserva (Lavoisier).",
      o: "Entender una reacción como reorganización de átomos que conserva la masa.",
      c: "Reacción química.",
      w: "Explica desde la combustión hasta la digestión; conservar la masa es una ley clave.",
      df: "hard",
      m: 50,
      xp: 24,
      er: ["Creer que en una reacción se 'crea' o 'destruye' materia."],
      cr: ["Explicas la conservación de la masa en una reacción."],
      ex: ["Analizar la combustión de una vela."],
      ev: ["Justificar por qué la masa total no cambia."],
      r: [R.khan("Reacciones químicas"), R.phet("Balancear reacciones")],
    },
    {
      s: "cie-acidos",
      b: "quimica",
      lv: 3,
      t: "Ácidos y bases (pH)",
      pre: ["cie-reacciones"],
      d: "Qué mide el pH y por qué importa en la vida diaria.",
      o: "Interpretar la escala de pH y clasificar sustancias comunes.",
      c: "Ácidos y bases.",
      w: "El pH aparece en la comida, el cuerpo, el suelo y los océanos.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Creer que 'ácido' siempre significa peligroso.", "Leer la escala de pH como lineal (es logarítmica)."],
      cr: ["Sitúas sustancias comunes en la escala de pH."],
      ex: ["Medir el pH de limón, agua y jabón."],
      ev: ["Ordenar sustancias por acidez."],
      r: [R.ck12("pH"), R.khan("Ácidos y bases")],
    },

    // ───────────── Energía, fuerzas y movimiento ─────────────
    {
      s: "cie-energia",
      b: "energia",
      lv: 1,
      t: "Qué es la energía",
      pre: ["cie-que-es"],
      d: "La energía como capacidad de causar cambios; sus formas.",
      o: "Reconocer las formas de energía y sus transformaciones.",
      c: "Concepto de energía.",
      w: "La energía es un hilo que conecta física, química, biología y Tierra.",
      df: "easy",
      m: 30,
      xp: 14,
      er: ["Creer que la energía 'se gasta' y desaparece.", "Confundir energía con fuerza."],
      cr: ["Identificas formas de energía en una escena."],
      ex: ["Rastrear la energía de una linterna."],
      ev: ["Nombrar tres formas de energía y un ejemplo de cada una."],
      r: [R.khan("Energía"), R.ck12("Forms of energy")],
    },
    {
      s: "cie-conservacion",
      b: "energia",
      lv: 2,
      t: "Conservación y transformación de la energía",
      pre: ["cie-energia"],
      d: "La energía no se crea ni se destruye: se transforma.",
      o: "Aplicar la conservación de la energía a cadenas de transformación.",
      c: "Conservación de la energía.",
      w: "Es una de las leyes más importantes y universales de la física.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Creer que la energía se 'pierde' (en realidad se transforma, a menudo en calor)."],
      cr: ["Sigues una cadena de transformaciones de energía."],
      ex: ["Analizar la energía en una montaña rusa."],
      ev: ["Explicar a dónde 'va' la energía de un coche que frena."],
      r: [R.phet("Energía en el skate"), R.khan("Conservación de la energía")],
    },
    {
      s: "cie-fuerzas",
      b: "energia",
      lv: 2,
      t: "Fuerzas y movimiento",
      pre: ["cie-energia"],
      d: "Las fuerzas cambian el movimiento; un objeto sin fuerza neta sigue igual (inercia).",
      o: "Relacionar fuerzas con cambios de movimiento (idea de Newton).",
      c: "Fuerzas y movimiento.",
      w: "Corrige una de las mayores ideas erróneas: que 'hace falta fuerza para mantener el movimiento'.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Creer que un objeto en movimiento necesita fuerza continua para seguir.", "Ignorar la fricción."],
      cr: ["Explicas por qué un objeto sigue moviéndose sin fuerza (inercia)."],
      ex: ["Analizar por qué un disco de hockey se desliza y frena."],
      ev: ["Predecir el movimiento con y sin fuerza neta."],
      r: [R.phet("Fuerzas y movimiento"), R.khan("Leyes de Newton")],
    },
    {
      s: "cie-ondas",
      b: "energia",
      lv: 3,
      t: "Ondas, luz y sonido",
      pre: ["cie-conservacion"],
      d: "Las ondas transportan energía sin transportar materia.",
      o: "Entender la onda como transporte de energía y sus propiedades.",
      c: "Ondas.",
      w: "Luz, sonido, radio y terremotos son ondas: un mismo modelo lo explica.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Creer que el sonido viaja en el vacío.", "Pensar que la onda 'lleva' la materia consigo."],
      cr: ["Distingues amplitud de frecuencia."],
      ex: ["Comparar una ola de agua con el sonido."],
      ev: ["Explicar por qué en el espacio no se oye nada."],
      r: [R.phet("Ondas"), R.khan("Ondas y sonido")],
    },
    {
      s: "cie-electricidad",
      b: "energia",
      lv: 3,
      t: "Electricidad básica",
      pre: ["cie-conservacion"],
      d: "Carga, corriente y circuitos simples.",
      o: "Entender un circuito simple y el flujo de corriente.",
      c: "Electricidad.",
      w: "La electricidad mueve el mundo moderno; su base es sencilla.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Creer que la corriente 'se gasta' en la bombilla.", "Confundir voltaje con corriente."],
      cr: ["Explicas qué necesita un circuito para funcionar."],
      ex: ["Encender una bombilla con pila y cable."],
      ev: ["Detectar por qué un circuito abierto no funciona."],
      r: [R.phet("Kit de construcción de circuitos"), R.khan("Circuitos")],
    },

    // ───────────── Biología: la vida ─────────────
    {
      s: "cie-vida",
      b: "vida",
      lv: 1,
      t: "Qué es estar vivo",
      pre: ["cie-que-es"],
      d: "Los rasgos comunes de los seres vivos: nutrirse, crecer, reproducirse, responder.",
      o: "Distinguir un ser vivo por sus características.",
      c: "Características de la vida.",
      w: "Definir la vida es el punto de partida de toda la biología.",
      df: "easy",
      m: 30,
      xp: 14,
      er: ["Creer que 'moverse' es lo que define la vida (una planta no se mueve y vive)."],
      cr: ["Clasificas si algo está vivo por sus rasgos."],
      ex: ["Comparar un cristal que 'crece' con un ser vivo."],
      ev: ["Justificar por qué el fuego no está vivo aunque 'crece'."],
      r: [R.ck12("Características de la vida"), R.khan("Qué es la vida")],
    },
    {
      s: "cie-celula",
      b: "vida",
      lv: 2,
      t: "La célula",
      pre: ["cie-vida"],
      d: "La célula como unidad básica de la vida; toda vida está hecha de células.",
      o: "Entender la célula como unidad estructural y funcional de la vida.",
      c: "Teoría celular.",
      w: "Igual que el átomo en la materia, la célula es la unidad de la vida.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Creer que las células solo están en animales.", "Imaginar la célula como algo 'vacío'."],
      cr: ["Nombras partes básicas de una célula y su función."],
      ex: ["Observar células de cebolla al microscopio."],
      ev: ["Distinguir célula animal de vegetal."],
      r: [R.ck12("La célula"), R.khan("Estructura celular")],
    },
    {
      s: "cie-cuerpo",
      b: "vida",
      lv: 2,
      t: "Sistemas de los seres vivos",
      pre: ["cie-celula"],
      d: "Cómo células, tejidos, órganos y sistemas se organizan y cooperan.",
      o: "Entender la organización jerárquica de un organismo.",
      c: "Organización biológica.",
      w: "Explica cómo lo pequeño (célula) construye lo grande (organismo).",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Ver los órganos como piezas aisladas y no como sistemas que cooperan."],
      cr: ["Ordenas los niveles: célula → tejido → órgano → sistema."],
      ex: ["Seguir el aire desde la nariz hasta las células."],
      ev: ["Relacionar un órgano con su sistema."],
      r: [R.khan("Cuerpo humano"), R.ck12("Body systems")],
    },
    {
      s: "cie-fotosintesis",
      b: "vida",
      lv: 3,
      t: "Fotosíntesis y energía en la vida",
      pre: ["cie-celula", "cie-energia"],
      d: "Cómo las plantas captan energía del Sol y sostienen casi toda la vida.",
      o: "Explicar la fotosíntesis como captura y transformación de energía.",
      c: "Energía en los seres vivos.",
      w: "Conecta energía y vida: casi toda la comida empieza en la fotosíntesis.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Creer que las plantas 'comen' tierra.", "Pensar que la masa de un árbol viene del suelo (viene del CO₂ del aire)."],
      cr: ["Explicas de dónde saca su energía y materia una planta."],
      ex: ["Rastrear la energía del Sol hasta tu comida."],
      ev: ["Justificar de dónde viene la masa de un árbol."],
      r: [R.khan("Fotosíntesis"), R.ck12("Photosynthesis")],
    },

    // ───────────── Genética y evolución ─────────────
    {
      s: "cie-adn",
      b: "genetica",
      lv: 3,
      t: "ADN y herencia",
      pre: ["cie-celula"],
      d: "El ADN como manual de instrucciones que se hereda de padres a hijos.",
      o: "Entender el ADN como información hereditaria.",
      c: "Herencia.",
      w: "Explica por qué nos parecemos a nuestra familia y la base de la vida.",
      df: "expert",
      m: 50,
      xp: 24,
      er: ["Creer que se heredan rasgos adquiridos en vida (p. ej. músculos)."],
      cr: ["Explicas a alto nivel qué es el ADN y cómo se hereda."],
      ex: ["Analizar por qué un rasgo aparece en una familia."],
      ev: ["Distinguir un rasgo heredado de uno adquirido."],
      r: [R.khan("ADN y herencia"), R.ck12("DNA")],
    },
    {
      s: "cie-evolucion",
      b: "genetica",
      lv: 3,
      t: "Evolución por selección natural",
      pre: ["cie-adn"],
      d: "Variación + selección + tiempo: cómo cambian las especies.",
      o: "Explicar la selección natural con un ejemplo.",
      c: "Evolución.",
      w: "Es la idea unificadora de la biología; también la más malentendida.",
      df: "expert",
      m: 55,
      xp: 26,
      er: ["Creer que los individuos 'evolucionan' en su vida (evolucionan las poblaciones).", "Pensar que la evolución 'busca' un objetivo."],
      cr: ["Explicas la selección natural con variación, selección y tiempo."],
      ex: ["Analizar las polillas claras y oscuras (industrialización)."],
      ev: ["Detectar un error común sobre la evolución."],
      r: [R.khan("Selección natural"), R.natgeo("Evolution")],
    },

    // ───────────── Ciencias de la Tierra ─────────────
    {
      s: "cie-tierra",
      b: "tierra",
      lv: 2,
      t: "El planeta Tierra: capas y rocas",
      pre: ["cie-materia"],
      d: "La estructura de la Tierra y el ciclo de las rocas.",
      o: "Describir las capas de la Tierra y de dónde vienen las rocas.",
      c: "Geología básica.",
      w: "Entender el suelo que pisamos y los recursos que usamos.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Imaginar el interior de la Tierra como hueco o inmóvil."],
      cr: ["Nombras las capas de la Tierra en orden."],
      ex: ["Clasificar tres rocas por su origen."],
      ev: ["Relacionar un tipo de roca con cómo se formó."],
      r: [R.natgeo("Capas de la Tierra"), R.ck12("Earth's layers")],
    },
    {
      s: "cie-tectonica",
      b: "tierra",
      lv: 3,
      t: "Tectónica de placas",
      pre: ["cie-tierra"],
      d: "Las placas se mueven y explican terremotos, volcanes y montañas.",
      o: "Explicar fenómenos geológicos con el movimiento de placas.",
      c: "Tectónica de placas.",
      w: "Una teoría que unificó la geología; explica el relieve del planeta.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Creer que los continentes están fijos."],
      cr: ["Relacionas un terremoto o volcán con un límite de placas."],
      ex: ["Encajar la costa de África y Sudamérica."],
      ev: ["Predecir dónde hay más terremotos y por qué."],
      r: [R.natgeo("Tectónica de placas"), R.khan("Placas")],
    },
    {
      s: "cie-clima",
      b: "tierra",
      lv: 3,
      t: "Clima y ciclo del agua",
      pre: ["cie-tierra", "cie-energia"],
      d: "Cómo el Sol, el agua y la atmósfera mueven el clima; tiempo vs. clima.",
      o: "Distinguir tiempo de clima y explicar el ciclo del agua.",
      c: "Sistema climático.",
      w: "Base para entender el medio ambiente y el cambio climático.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Confundir 'tiempo' (hoy) con 'clima' (patrón a largo plazo)."],
      cr: ["Describes el ciclo del agua y distingues tiempo de clima."],
      ex: ["Seguir una gota de agua por su ciclo."],
      ev: ["Clasificar afirmaciones como tiempo o clima."],
      r: [R.nasa("Clima"), R.natgeo("Ciclo del agua")],
    },

    // ───────────── Astronomía y el universo ─────────────
    {
      s: "cie-sistema-solar",
      b: "cosmos",
      lv: 2,
      t: "El sistema solar",
      pre: ["cie-que-es"],
      d: "El Sol, los planetas y sus movimientos; escalas y órbitas.",
      o: "Describir el sistema solar y los movimientos básicos.",
      c: "Sistema solar.",
      w: "Nuestro vecindario cósmico y la base para entender el cielo.",
      df: "medium",
      m: 35,
      xp: 16,
      er: ["Creer que los planetas están 'cerca' unos de otros (las escalas engañan)."],
      cr: ["Ordenas los planetas y explicas la órbita."],
      ex: ["Hacer un modelo a escala del sistema solar."],
      ev: ["Distinguir rotación de traslación."],
      r: [R.nasa("Sistema solar"), R.khan("El sistema solar")],
    },
    {
      s: "cie-estaciones",
      b: "cosmos",
      lv: 3,
      t: "Día, noche y estaciones",
      pre: ["cie-sistema-solar"],
      d: "La rotación causa el día; la inclinación del eje causa las estaciones.",
      o: "Explicar correctamente el origen de día, noche y estaciones.",
      c: "Movimientos de la Tierra.",
      w: "Corrige una de las ideas erróneas más famosas sobre las estaciones.",
      df: "hard",
      m: 40,
      xp: 20,
      er: ["Creer que hace más calor en verano porque la Tierra está más cerca del Sol (es por la inclinación del eje)."],
      cr: ["Explicas las estaciones por la inclinación del eje."],
      ex: ["Modelar con una linterna y una pelota inclinada."],
      ev: ["Refutar la idea de 'estaciones por distancia'."],
      r: [R.nasa("Estaciones"), R.khan("Estaciones del año")],
    },
    {
      s: "cie-estrellas",
      b: "cosmos",
      lv: 3,
      t: "Estrellas, galaxias y escala del universo",
      pre: ["cie-sistema-solar"],
      d: "Qué son las estrellas, las galaxias y la inmensa escala del cosmos.",
      o: "Comprender la escala del universo y qué es una estrella.",
      c: "Astronomía estelar.",
      w: "Sitúa a la humanidad en el cosmos y despierta el asombro científico.",
      df: "expert",
      m: 45,
      xp: 24,
      er: ["Creer que las estrellas son pequeñas o que están 'pegadas' al cielo.", "Confundir estrella con planeta."],
      cr: ["Explicas qué es una estrella y una galaxia."],
      ex: ["Comparar el tamaño del Sol con la Tierra."],
      ev: ["Ordenar por escala: planeta, estrella, galaxia, universo."],
      r: [R.nasa("Estrellas y galaxias"), R.khan("Escala del universo")],
    },

    // ───────────── Ecología y medio ambiente ─────────────
    {
      s: "cie-ecosistemas",
      b: "ecologia",
      lv: 2,
      t: "Ecosistemas y cadenas tróficas",
      pre: ["cie-vida"],
      d: "Cómo los seres vivos se relacionan entre sí y con su entorno; flujo de energía.",
      o: "Explicar un ecosistema y el flujo de energía en una cadena trófica.",
      c: "Ecología básica.",
      w: "Muestra que la vida es una red interconectada, no piezas sueltas.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Dibujar flechas de la cadena trófica al revés (van hacia quien come)."],
      cr: ["Construyes una cadena trófica con el flujo de energía correcto."],
      ex: ["Trazar quién se come a quién en un prado."],
      ev: ["Predecir el efecto de quitar un eslabón."],
      r: [R.natgeo("Ecosistemas"), R.ck12("Food chains")],
    },
    {
      s: "cie-ciclos",
      b: "ecologia",
      lv: 3,
      t: "Ciclos de la naturaleza",
      pre: ["cie-ecosistemas"],
      d: "El agua, el carbono y los nutrientes circulan y se reciclan.",
      o: "Entender que la materia se recicla en ciclos naturales.",
      c: "Ciclos biogeoquímicos.",
      w: "Explica cómo el planeta sostiene la vida reutilizando la materia.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Creer que la materia 'se acaba' en vez de reciclarse."],
      cr: ["Describes el ciclo del carbono a grandes rasgos."],
      ex: ["Seguir un átomo de carbono por su ciclo."],
      ev: ["Explicar cómo el carbono pasa del aire a un ser vivo."],
      r: [R.natgeo("Ciclo del carbono"), R.ck12("Biogeochemical cycles")],
    },
    {
      s: "cie-impacto",
      b: "ecologia",
      lv: 3,
      t: "Impacto humano y cambio climático",
      pre: ["cie-ecosistemas", "cie-clima"],
      d: "Cómo la actividad humana altera los ciclos y el clima, con base en evidencia.",
      o: "Explicar el cambio climático con evidencia científica.",
      c: "Ciencia ambiental.",
      w: "Aplica el pensamiento científico al mayor reto de nuestro tiempo.",
      df: "expert",
      m: 50,
      xp: 26,
      er: ["Confundir tiempo con clima al hablar del cambio climático.", "Tratar el consenso científico como 'opinión'."],
      cr: ["Explicas el efecto invernadero y el papel del CO₂ con evidencia."],
      ex: ["Analizar la curva de CO₂ y temperatura."],
      ev: ["Distinguir una fuente fiable de una engañosa sobre el clima."],
      r: [R.nasa("Cambio climático"), R.natgeo("Impacto humano")],
    },

    // ───────────── Hitos ─────────────
    {
      s: "hito-cie-fundamentos",
      b: "hito",
      lv: 1,
      t: "Hito · Fundamentos",
      pre: ["cie-observacion", "cie-materia", "cie-energia"],
      d: "Consolidas el pensamiento científico y las ideas de materia y energía.",
      o: "Confirmar una base sólida de razonamiento científico.",
      c: "Fundamentos científicos.",
      w: "Compuerta que asegura pensar con evidencia antes de profundizar.",
      df: "easy",
      m: 40,
      xp: 30,
      er: ["Avanzar sin distinguir observación de inferencia."],
      cr: ["Superas un repaso de pensamiento científico, materia y energía."],
      ex: ["Recorrido integrado de fundamentos."],
      ev: ["Autoevaluación de razonamiento científico."],
      r: [R.khan("Repaso de ciencia")],
    },
    {
      s: "hito-cie-intermedio",
      b: "hito",
      lv: 2,
      t: "Hito · Intermedio",
      pre: ["cie-metodo", "cie-atomos", "cie-celula"],
      d: "Manejas el método, la teoría atómica y la célula: las tres unidades básicas.",
      o: "Confirmar la transición al trabajo científico por dominios.",
      c: "Nivel intermedio.",
      w: "Confirma que unes método, materia y vida a nivel de sus unidades.",
      df: "medium",
      m: 50,
      xp: 35,
      er: ["Pasar a lo avanzado sin dominar el diseño experimental."],
      cr: ["Superas un repaso de método, átomos y células."],
      ex: ["Recorrido integrado intermedio."],
      ev: ["Autoevaluación intermedia."],
      r: [R.openstax("Science review")],
    },
    {
      s: "hito-cie-avanzado",
      b: "hito",
      lv: 3,
      t: "Hito · Avanzado",
      pre: ["cie-reacciones", "cie-evolucion", "cie-tectonica"],
      d: "Integras química, evolución y geología: pensar la ciencia como un todo conectado.",
      o: "Confirmar una comprensión conectada de los grandes dominios.",
      c: "Nivel avanzado.",
      w: "Cierre que muestra la ciencia como una red de ideas, no compartimentos.",
      df: "expert",
      m: 60,
      xp: 40,
      er: ["Ver los dominios como aislados, sin conexiones."],
      cr: ["Superas un repaso de química, evolución y Tierra."],
      ex: ["Recorrido integrado avanzado."],
      ev: ["Autoevaluación avanzada."],
      r: [R.openstax("Integrated science")],
    },
  ],
};
