/**
 * Árbol de habilidades: **Inglés (de cero a dominio C2)**.
 *
 * Base académica: dossier `docs/curriculum/idiomas-dossier.md` (CEFR + Companion
 * 2020, ACTFL, Cambridge, IELTS, TOEFL, Oxford 3000/5000, Pearson GSE, ILR/FSI;
 * y SLA: Krashen, Nation "cuatro hebras" + ciencia del vocabulario, Canale &
 * Swain, Byram, Levis/Jenkins, HVPT, SRS). El árbol está organizado por
 * **hebras de competencia que evolucionan** (no por temario) y cruzado por
 * **hitos de nivel** CEFR.
 *
 * Se integra en la arquitectura existente (Tree → Skill → SkillPrerequisite →
 * Resource). El contenido pedagógico enriquecido de cada Skill se guarda en las
 * columnas `objective`, `branch`, `difficulty` y en `content` (JSON): competencia,
 * justificación, razón de su posición, errores frecuentes, criterios de dominio,
 * ejercicios y evaluaciones sugeridas.
 */

import type { PrismaClient } from "@prisma/client";

type Res = {
  t: "VIDEO" | "ARTICLE" | "EXERCISE" | "BOOK" | "OTHER";
  title: string;
  url: string;
  p: string;
};

export interface EnNode {
  s: string; // slug
  b: string; // branch key
  lv: number; // nivel CEFR: 0 Pre-A1, 1 A1, 2 A2, 3 B1, 4 B2, 5 C1, 6 C2
  t: string; // título
  d: string; // descripción
  o: string; // objetivo de aprendizaje (can-do)
  c: string; // competencia adquirida
  w: string; // justificación pedagógica + razón de su posición
  df: "easy" | "medium" | "hard" | "expert";
  m: number; // minutos estimados
  xp: number;
  root?: boolean;
  pre: string[]; // prerrequisitos (slugs)
  er: string[]; // errores frecuentes
  cr: string[]; // criterios de dominio
  ex: string[]; // posibles ejercicios
  ev: string[]; // posibles evaluaciones
  r: Res[]; // recursos
}

/** Ramas (hebras de competencia) y su nivel de referencia visual. */
export const EN_BRANCHES: Record<string, string> = {
  estrategias: "Estrategias y autonomía",
  pronunciacion: "Pronunciación",
  vocabulario: "Vocabulario",
  gramatica: "Gramática",
  escucha: "Comprensión auditiva",
  lectura: "Lectura",
  conversacion: "Conversación",
  escritura: "Escritura",
  cultura: "Cultura",
  fluidez: "Fluidez",
  hito: "Hitos de nivel",
};

const LANE = [
  "estrategias",
  "pronunciacion",
  "vocabulario",
  "gramatica",
  "escucha",
  "lectura",
  "conversacion",
  "escritura",
  "cultura",
  "fluidez",
  "hito",
];

// Recursos reutilizables (fuentes reconocidas y de acceso libre).
const R = {
  bc: (title: string): Res => ({
    t: "ARTICLE",
    title,
    url: "https://learnenglish.britishcouncil.org/",
    p: "British Council",
  }),
  bbc: (title: string): Res => ({
    t: "VIDEO",
    title,
    url: "https://www.bbc.co.uk/learningenglish",
    p: "BBC Learning English",
  }),
  camb: (title: string): Res => ({
    t: "ARTICLE",
    title,
    url: "https://dictionary.cambridge.org/grammar/british-grammar/",
    p: "Cambridge",
  }),
  oxf: (title: string): Res => ({
    t: "OTHER",
    title,
    url: "https://www.oxfordlearnersdictionaries.com/wordlists/oxford3000-5000",
    p: "Oxford",
  }),
  anki: (title: string): Res => ({
    t: "OTHER",
    title,
    url: "https://apps.ankiweb.net/",
    p: "Anki (SRS)",
  }),
  ipa: (title: string): Res => ({
    t: "EXERCISE",
    title,
    url: "https://soundsofspeech.uiowa.edu/english/english",
    p: "U. of Iowa",
  }),
  elllo: (title: string): Res => ({
    t: "VIDEO",
    title,
    url: "https://www.elllo.org/",
    p: "ELLLO",
  }),
  esllab: (title: string): Res => ({
    t: "EXERCISE",
    title,
    url: "https://www.esl-lab.com/",
    p: "Randall's ESL Lab",
  }),
  tatoeba: (title: string): Res => ({
    t: "OTHER",
    title,
    url: "https://tatoeba.org/en",
    p: "Tatoeba",
  }),
  refold: (title: string): Res => ({
    t: "ARTICLE",
    title,
    url: "https://refold.la/",
    p: "Refold",
  }),
  owl: (title: string): Res => ({
    t: "ARTICLE",
    title,
    url: "https://owl.purdue.edu/owl/",
    p: "Purdue OWL",
  }),
};

export const EN_NODES: EnNode[] = [
  // ───────── Fundación (Pre-A1) ─────────
  {
    s: "est-como-aprender",
    b: "estrategias",
    lv: 0,
    t: "Cómo aprender un idioma",
    root: true,
    pre: [],
    d: "Cómo funciona la adquisición (input comprensible, constancia), metas y rutina de estudio.",
    o: "Configurar un sistema de estudio sostenible y expectativas realistas.",
    c: "Metacognición y autorregulación del aprendizaje.",
    w: "Es la raíz del árbol: el hábito y las expectativas correctas predicen el éxito y reducen el abandono (filtro afectivo, Krashen).",
    df: "easy",
    m: 90,
    xp: 10,
    er: [
      "Querer 'estudiar gramática' antes de exponerse al idioma.",
      "Fijar metas vagas sin plazo.",
    ],
    cr: ["Tienes una meta de nivel con fecha y un plan semanal realista."],
    ex: ["Escribir tu meta CEFR y calendario de estudio."],
    ev: ["Autoevaluación de hábitos tras 2 semanas de constancia."],
    r: [R.refold("Cómo se aprende un idioma"), R.bc("Guía para empezar")],
  },
  {
    s: "fon-percepcion",
    b: "pronunciacion",
    lv: 0,
    t: "Oído fonológico (percepción)",
    pre: ["est-como-aprender"],
    d: "Distinguir los sonidos del inglés que no existen en español (p. ej. /ɪ/–/iː/, /b/–/v/, th).",
    o: "Percibir los contrastes de sonido del inglés antes de producirlos.",
    c: "Discriminación fonémica (percepción auditiva).",
    w: "Va primero porque no se puede adquirir ni pronunciar lo que no se distingue; el entrenamiento perceptivo (HVPT) previene la fosilización.",
    df: "medium",
    m: 300,
    xp: 15,
    er: [
      "'Oír' los sonidos ingleses a través del sistema español.",
      "Ignorar la sílaba tónica.",
    ],
    cr: ["Aciertas ≥85% en discriminación de pares mínimos."],
    ex: ["Pares mínimos: ship/sheep, bat/vat, thin/tin."],
    ev: ["Test de discriminación de pares mínimos."],
    r: [
      R.ipa("Sonidos del inglés (IPA interactivo)"),
      R.bbc("The sounds of English"),
    ],
  },
  {
    s: "lec-alfabeto",
    b: "lectura",
    lv: 0,
    t: "Relación letra–sonido (phonics)",
    pre: ["est-como-aprender", "fon-percepcion"],
    d: "Cómo se relacionan la ortografía inglesa y sus sonidos (una ortografía poco transparente).",
    o: "Decodificar palabras escritas con su pronunciación aproximada.",
    c: "Descodificación grafema–fonema.",
    w: "Compuerta de la lectura; el inglés no se lee 'como se escribe', así que conviene tratar la relación letra-sonido explícitamente y pronto.",
    df: "easy",
    m: 180,
    xp: 12,
    er: ["Leer las vocales 'a la española'.", "Pronunciar letras mudas."],
    cr: ["Lees en voz alta 20 palabras nuevas con pronunciación razonable."],
    ex: ["Leer en voz alta y comparar con audio del diccionario."],
    ev: ["Lectura en voz alta evaluada con modelo nativo."],
    r: [R.bc("Sounds and spelling"), R.camb("Pronunciation")],
  },
  {
    s: "voc-supervivencia",
    b: "vocabulario",
    lv: 0,
    t: "100 palabras y fórmulas de supervivencia",
    pre: ["est-como-aprender", "fon-percepcion"],
    d: "Saludos, cortesía, números, sí/no y frases como 'I don't understand' o 'How do you say…?'.",
    o: "Sobrevivir a una interacción mínima y sostener el input.",
    c: "Léxico funcional básico.",
    w: "Da victorias inmediatas (motivación) y ancla el sistema de sonidos a significado desde el primer día.",
    df: "easy",
    m: 360,
    xp: 15,
    er: ["Traducir palabra por palabra.", "Memorizar sin audio."],
    cr: ["Te presentas y pides ayuda con fórmulas memorizadas."],
    ex: ["Tarjetas SRS con audio de las 100 frases."],
    ev: ["Grabar una presentación de 5 frases."],
    r: [R.anki("Mazo de frases de supervivencia"), R.bc("Everyday phrases")],
  },

  // ───────── Estrategias ─────────
  {
    s: "est-srs",
    b: "estrategias",
    lv: 1,
    t: "Repetición espaciada (SRS)",
    pre: ["est-como-aprender", "voc-supervivencia"],
    d: "Usar tarjetas con audio e imágenes repasadas en intervalos crecientes.",
    o: "Retener vocabulario y frases a largo plazo con poco esfuerzo diario.",
    c: "Estrategia de memorización eficiente.",
    w: "La repetición espaciada y el efecto de testing trasladan el conocimiento a memoria de largo plazo; es el motor de memoria de todo el árbol.",
    df: "easy",
    m: 200,
    xp: 12,
    er: [
      "Tarjetas solo texto (sin audio/contexto).",
      "Dejar acumular repasos.",
    ],
    cr: ["Mantienes una rutina SRS ≥ 2 semanas seguidas."],
    ex: ["Crear/importar un mazo por frecuencia y repasar a diario."],
    ev: ["Retención ≥ 80% en repasos a 1 semana."],
    r: [R.anki("Empezar con Anki"), R.oxf("Oxford 3000 (base de mazos)")],
  },
  {
    s: "est-tolerancia",
    b: "estrategias",
    lv: 2,
    t: "Tolerancia a la ambigüedad",
    pre: ["aud-instrucciones", "lec-frases"],
    d: "Comprender sin traducir y sin necesitar entender el 100% del mensaje.",
    o: "Sostener el input y bajar la ansiedad ante lo desconocido.",
    c: "Estrategia de comprensión / autorregulación afectiva.",
    w: "Reduce el filtro afectivo (Krashen) y previene el hábito de traducir palabra por palabra, fuente típica de fosilización; por eso es temprana.",
    df: "easy",
    m: 120,
    xp: 12,
    er: [
      "Bloquearse ante cada palabra desconocida.",
      "Traducir mentalmente todo.",
    ],
    cr: ["Sigues un audio/texto entendiendo la idea global sin traducir."],
    ex: ["Ver un vídeo entendiendo solo lo esencial y resumirlo."],
    ev: ["Resumen de la idea principal de un input no adaptado."],
    r: [R.refold("No traducir: comprender en contexto")],
  },
  {
    s: "est-compensacion",
    b: "estrategias",
    lv: 3,
    t: "Estrategias de compensación",
    pre: ["ora-cotidiana"],
    d: "Parafrasear, pedir aclaración, inferir por contexto y usar circunloquios.",
    o: "No bloquearte cuando te falta una palabra.",
    c: "Competencia estratégica (Canale & Swain).",
    w: "Sostiene la fluidez real y la autonomía comunicativa; se vuelve necesaria justo cuando ya conversas (B1).",
    df: "medium",
    m: 300,
    xp: 18,
    er: ["Callar al no saber una palabra.", "Recurrir a la L1."],
    cr: ["Explicas 10 palabras difíciles sin nombrarlas."],
    ex: ["Juego de 'describe sin decir la palabra'."],
    ev: ["Conversación con vacíos léxicos resueltos por paráfrasis."],
    r: [R.bc("Communication strategies")],
  },
  {
    s: "est-mediacion",
    b: "estrategias",
    lv: 5,
    t: "Mediación (CEFR 2020)",
    pre: ["ora-debatir", "esc-argumentativo"],
    d: "Resumir, reformular e interpretar entre lenguas/registros para otras personas.",
    o: "Servir de puente comunicativo: transmitir información compleja a otros.",
    c: "Mediación lingüística y cultural.",
    w: "Destreza estrella del CEFR moderno y del uso profesional real; requiere dominio productivo previo (C1).",
    df: "hard",
    m: 400,
    xp: 25,
    er: ["Traducir literal en vez de mediar el sentido."],
    cr: ["Resumes un texto complejo para un público no experto."],
    ex: ["Explicar un artículo técnico a alguien de otra área."],
    ev: ["Tarea de mediación evaluada (resumen + adaptación de registro)."],
    r: [R.bc("Mediation skills")],
  },

  // ───────── Pronunciación ─────────
  {
    s: "fon-produccion",
    b: "pronunciacion",
    lv: 1,
    t: "Producción de sonidos inteligible",
    pre: ["fon-percepcion"],
    d: "Articular los sonidos del inglés de forma comprensible, incluidos los ausentes en español.",
    o: "Que te entiendan sin esfuerzo, aunque tengas acento.",
    c: "Producción fonémica (segmentos).",
    w: "La producción sigue a la percepción; la meta en A1 es la inteligibilidad, no el acento nativo (principio de inteligibilidad, Levis) — evita frustración.",
    df: "medium",
    m: 600,
    xp: 15,
    er: [
      "Sustituir sonidos ingleses por los españoles más cercanos.",
      "Añadir una 'e' antes de s- (school→eschool).",
    ],
    cr: ["Un oyente entiende tus frases sin pedir repetición."],
    ex: ["Grabarte y compararte con el audio del diccionario."],
    ev: ["Lectura grabada evaluada por inteligibilidad."],
    r: [
      R.ipa("Producir los sonidos del inglés"),
      R.bbc("Pronunciation workshop"),
    ],
  },
  {
    s: "fon-acento",
    b: "pronunciacion",
    lv: 2,
    t: "Acentuación (acento léxico)",
    pre: ["fon-produccion", "aud-conversaciones"],
    d: "Colocar la sílaba tónica correcta de cada palabra y percibir su efecto en el significado.",
    o: "Que el acento de palabra no impida la comprensión.",
    c: "Acento léxico (suprasegmentos).",
    w: "El acento léxico es de los rasgos de mayor impacto en la inteligibilidad y es enseñable pronto (Levis); un acento mal puesto hace que el oyente 'busque otra palabra'.",
    df: "medium",
    m: 400,
    xp: 15,
    er: [
      "Acentuar como en español (p. ej. 'HOtel' vs 'hoTEL').",
      "No marcar la reducción de las átonas.",
    ],
    cr: ["Colocas bien la tónica en 20 palabras nuevas."],
    ex: ["Marcar la tónica y verificar con el diccionario."],
    ev: ["Dictado de palabras con identificación de la tónica."],
    r: [R.camb("Word stress"), R.bbc("Word stress")],
  },
  {
    s: "fon-ritmo",
    b: "pronunciacion",
    lv: 3,
    t: "Ritmo y encadenamiento",
    pre: ["fon-acento", "flu-automatizar"],
    d: "Ritmo acentual del inglés (stress-timed) y enlace entre palabras (linking).",
    o: "Hablar con ritmo natural, no 'robótico'.",
    c: "Ritmo y habla encadenada (suprasegmentos).",
    w: "El inglés comprime las sílabas átonas; sin ritmo, la fluidez suena entrecortada. Requiere algo de automatización previa (fluidez A2).",
    df: "hard",
    m: 400,
    xp: 18,
    er: [
      "Dar el mismo peso a todas las sílabas (ritmo silábico).",
      "Separar cada palabra.",
    ],
    cr: ["Reproduces el ritmo de una frase modelo con enlaces."],
    ex: ["Shadowing marcando fuertes/débiles."],
    ev: ["Comparación prosódica con un modelo."],
    r: [R.bbc("Connected speech"), R.elllo("Escucha ritmo natural")],
  },
  {
    s: "fon-entonacion",
    b: "pronunciacion",
    lv: 4,
    t: "Entonación",
    pre: ["fon-ritmo", "aud-nativo"],
    d: "Melodía de la frase y prominencia para marcar información nueva, preguntas y actitud.",
    o: "Usar la entonación para transmitir significado e intención.",
    c: "Entonación y prominencia.",
    w: "La prominencia es el rasgo suprasegmental clave para la inteligibilidad internacional (Jenkins); se afina bien tras mucha escucha nativa (B2).",
    df: "hard",
    m: 400,
    xp: 20,
    er: [
      "Entonación plana o de patrón español.",
      "No destacar la información nueva.",
    ],
    cr: ["Distingues y produces entonación de pregunta, lista y contraste."],
    ex: ["Imitar la melodía de un monólogo corto."],
    ev: ["Lectura expresiva evaluada por entonación."],
    r: [R.bbc("Intonation"), R.bc("Intonation basics")],
  },
  {
    s: "fon-naturalidad",
    b: "pronunciacion",
    lv: 5,
    t: "Naturalidad: habla conectada y reducciones",
    pre: ["fon-entonacion", "aud-conferencias"],
    d: "Formas débiles, reducciones (gonna, wanna), elisiones y asimilaciones del habla real.",
    o: "Producir habla conectada natural, no sobrearticulada.",
    c: "Habla conectada avanzada.",
    w: "La naturalidad exige gran cantidad de input previo para interiorizar los patrones reales; por eso en C1.",
    df: "expert",
    m: 500,
    xp: 22,
    er: ["Sobrearticular cada palabra.", "No usar formas débiles."],
    cr: ["Reproduces un pasaje coloquial con reducciones naturales."],
    ex: ["Shadowing de diálogo coloquial rápido."],
    ev: ["Muestra de habla espontánea evaluada por naturalidad."],
    r: [R.bbc("Weak forms & reductions")],
  },
  {
    s: "fon-nativo",
    b: "pronunciacion",
    lv: 6,
    t: "Pronunciación cercana a hablante competente",
    pre: ["fon-naturalidad", "ora-adaptar"],
    d: "Matices finos de acento y sutileza prosódica próximos a un hablante muy competente.",
    o: "Transmitir matices con una pronunciación casi nativa.",
    c: "Refinamiento fonológico de alto nivel.",
    w: "Es un objetivo de C2 (no de B2): pulir el matiz cuando todo lo demás ya está automatizado.",
    df: "expert",
    m: 600,
    xp: 25,
    er: [
      "Calcos sutiles de la L1 en sonidos aislados.",
      "Sobre-formalidad prosódica.",
    ],
    cr: ["Un hablante competente te evalúa como 'casi nativo'."],
    ex: ["Trabajo fino con feedback de hablante experto."],
    ev: ["Valoración por hablante competente."],
    r: [R.ipa("Refinar sonidos concretos")],
  },

  // ───────── Vocabulario ─────────
  {
    s: "voc-nucleo-1",
    b: "vocabulario",
    lv: 1,
    t: "Vocabulario núcleo I (~500–800)",
    pre: ["voc-supervivencia", "est-srs"],
    d: "Las palabras de altísima frecuencia (Oxford 3000, nivel A1).",
    o: "Cubrir gran parte del habla cotidiana básica.",
    c: "Léxico de alta frecuencia.",
    w: "La frecuencia maximiza la cobertura por esfuerzo: unas cientos de palabras explican gran parte del habla diaria (Nation).",
    df: "easy",
    m: 2400,
    xp: 20,
    er: ["Aprender palabras raras antes que las frecuentes."],
    cr: ["Describes tu rutina diaria con el vocabulario aprendido."],
    ex: ["Mazo SRS de Oxford 3000 (A1) con audio."],
    ev: ["Prueba de vocabulario de alta frecuencia."],
    r: [R.oxf("Oxford 3000 (A1)"), R.anki("Mazo de frecuencia")],
  },
  {
    s: "voc-nucleo-2",
    b: "vocabulario",
    lv: 2,
    t: "Vocabulario núcleo II (~2000)",
    pre: ["voc-nucleo-1"],
    d: "Ampliar a ~2000 familias de palabras por temas cotidianos (Oxford 3000, A2).",
    o: "Alcanzar ~95% de cobertura del habla cotidiana.",
    c: "Léxico cotidiano.",
    w: "El umbral de ~2000 palabras cubre ~95% del habla oral y desbloquea la conversación cotidiana (Nation).",
    df: "medium",
    m: 3000,
    xp: 22,
    er: ["Dejar el SRS.", "No aprender colocaciones."],
    cr: ["Sostienes 3 min de conversación sobre temas familiares."],
    ex: ["Mazos temáticos + lectura graduada."],
    ev: ["Prueba de tamaño de vocabulario (~2000)."],
    r: [R.oxf("Oxford 3000 (A2)")],
  },
  {
    s: "voc-3000",
    b: "vocabulario",
    lv: 3,
    t: "Vocabulario III (~3–4k + colocaciones)",
    pre: ["voc-nucleo-2"],
    d: "Ampliar a ~3–4k familias y aprender colocaciones frecuentes (make/do, take a photo…).",
    o: "Acercarte al 95% de cobertura lectora con apoyo.",
    c: "Léxico intermedio y colocaciones.",
    w: "Las colocaciones son clave de naturalidad y marcan el salto B1→B2.",
    df: "hard",
    m: 3600,
    xp: 24,
    er: ["Aprender palabras sueltas sin sus combinaciones."],
    cr: ["Escribes un texto de 150 palabras con 10 colocaciones nuevas."],
    ex: ["Diccionario de colocaciones + lectura extensiva."],
    ev: ["Prueba de colocaciones."],
    r: [R.oxf("Oxford 3000/5000 (B1)"), R.camb("Colocaciones")],
  },
  {
    s: "voc-5000",
    b: "vocabulario",
    lv: 4,
    t: "Vocabulario IV (~5000 + idioms)",
    pre: ["voc-3000"],
    d: "Ampliar a ~5000 familias y aprender expresiones idiomáticas frecuentes.",
    o: "~95% de cobertura lectora y naturalidad idiomática.",
    c: "Léxico amplio y fraseología.",
    w: "~5000 familias sitúan la lectura en el umbral B2 (95%) y las expresiones idiomáticas dan naturalidad.",
    df: "hard",
    m: 4800,
    xp: 26,
    er: ["Traducir idioms literalmente."],
    cr: ["Usas 15 expresiones idiomáticas en contexto adecuado."],
    ex: ["Diccionario de idioms + inmersión."],
    ev: ["Prueba de vocabulario y modismos B2."],
    r: [R.oxf("Oxford 5000 (B2)")],
  },
  {
    s: "voc-8000",
    b: "vocabulario",
    lv: 5,
    t: "Vocabulario V (~8000 + jerga)",
    pre: ["voc-5000"],
    d: "Ampliar a ~8000 familias, incluyendo jerga, matices y colocaciones especializadas.",
    o: "~98% de cobertura lectora (comprensión no asistida).",
    c: "Léxico avanzado y especializado.",
    w: "El 98% de cobertura, que permite leer sin ayuda, exige ~8000 familias (Nation); es el umbral C1.",
    df: "expert",
    m: 6000,
    xp: 28,
    er: ["Estancarse en la 'meseta' intermedia."],
    cr: ["Lees un texto de tu campo entendiendo casi todo sin diccionario."],
    ex: ["Glosario personal de 300 términos de tu área."],
    ev: ["Prueba de vocabulario académico/especializado."],
    r: [R.oxf("Listas avanzadas"), R.camb("Vocabulario avanzado")],
  },
  {
    s: "voc-matiz",
    b: "vocabulario",
    lv: 6,
    t: "Léxico casi nativo (matiz/connotación)",
    pre: ["voc-8000"],
    d: "Connotación, colocación fina, registro culto y coloquial, matices de significado.",
    o: "Elegir la palabra exacta con el matiz y el tono adecuados.",
    c: "Precisión léxica de alto nivel.",
    w: "La precisión de C2 es, sobre todo, léxica: distinguir sinónimos por connotación y registro.",
    df: "expert",
    m: 6000,
    xp: 30,
    er: ["Usar connotación o tono inapropiados."],
    cr: ["Reescribes un texto en 3 registros distintos."],
    ex: ["Análisis de sinónimos por connotación."],
    ev: ["Tarea de reescritura por registro."],
    r: [R.camb("Matices y registro")],
  },

  // ───────── Gramática ─────────
  {
    s: "gra-oracion",
    b: "gramatica",
    lv: 1,
    t: "Estructura básica de la oración (SVO)",
    pre: ["voc-supervivencia"],
    d: "Orden sujeto-verbo-objeto, afirmación/negación y pronombres personales.",
    o: "Formar oraciones simples correctas.",
    c: "Sintaxis básica.",
    w: "Mínima mecánica necesaria para 'crear con la lengua'; el inglés es rígido en el orden SVO y exige sujeto explícito.",
    df: "medium",
    m: 500,
    xp: 15,
    er: [
      "Omitir el sujeto (permitido en español).",
      "Calcar el orden del español.",
    ],
    cr: ["Escribes 10 oraciones correctas sobre ti."],
    ex: ["Construir frases con tarjetas de sujeto/verbo/objeto."],
    ev: ["Corrección de oraciones."],
    r: [R.camb("Word order"), R.bc("Sentence structure")],
  },
  {
    s: "gra-preguntas",
    b: "gramatica",
    lv: 1,
    t: "Preguntas básicas (do/does, wh-)",
    pre: ["gra-oracion"],
    d: "Interrogativos wh-, preguntas de sí/no y el auxiliar do/does.",
    o: "Pedir y dar información esencial.",
    c: "Formación de preguntas.",
    w: "El auxiliar 'do' no existe en español y es fuente de error; preguntar mantiene viva la conversación y el input.",
    df: "medium",
    m: 300,
    xp: 14,
    er: ["Olvidar el auxiliar do/does.", "Orden incorrecto sujeto-verbo."],
    cr: ["Haces 8 preguntas correctas en una entrevista."],
    ex: ["Entrevistar a alguien con preguntas wh-."],
    ev: ["Producción de preguntas a partir de respuestas."],
    r: [R.camb("Questions"), R.bc("Question forms")],
  },
  {
    s: "gra-presente",
    b: "gramatica",
    lv: 1,
    t: "Presente (simple y continuo)",
    pre: ["gra-oracion"],
    d: "Present simple (hábitos) y present continuous (acciones en curso); la -s de 3ª persona.",
    o: "Hablar del presente y de lo habitual.",
    c: "Tiempos de presente.",
    w: "Sostiene la mayoría del habla inicial; el contraste simple/continuo y la -s son errores tempranos típicos.",
    df: "medium",
    m: 500,
    xp: 16,
    er: ["Olvidar la -s de 3ª persona.", "Confundir simple con continuo."],
    cr: ["Narras 'un día normal' en presente, oral y escrito."],
    ex: ["Describir rutinas vs. lo que pasa ahora."],
    ev: ["Ejercicio de contraste simple/continuo."],
    r: [R.camb("Present tenses"), R.bbc("Present simple/continuous")],
  },
  {
    s: "gra-pasado",
    b: "gramatica",
    lv: 2,
    t: "Pasado (simple)",
    pre: ["gra-presente"],
    d: "Past simple regular e irregular para narrar hechos terminados.",
    o: "Contar experiencias pasadas.",
    c: "Tiempo pasado.",
    w: "Narrar el pasado es núcleo de la interacción social; los verbos irregulares ingleses requieren memorización dedicada.",
    df: "hard",
    m: 700,
    xp: 18,
    er: ["Regularizar irregulares (goed).", "Usar did + verbo en pasado."],
    cr: ["Cuentas qué hiciste el fin de semana."],
    ex: ["Narrar una anécdota pasada."],
    ev: ["Ejercicio de verbos irregulares en contexto."],
    r: [R.camb("Past simple"), R.bc("Irregular verbs")],
  },
  {
    s: "gra-futuro",
    b: "gramatica",
    lv: 2,
    t: "Futuro (will / going to)",
    pre: ["gra-presente"],
    d: "Expresar planes, intenciones y predicciones con 'will' y 'be going to'.",
    o: "Hablar de lo que va a pasar.",
    c: "Expresión de futuro.",
    w: "Completa el eje temporal básico (presente-pasado-futuro); el contraste will/going to no tiene equivalente directo en español.",
    df: "medium",
    m: 400,
    xp: 16,
    er: ["Usar present simple para el futuro.", "Confundir will con going to."],
    cr: ["Planificas un viaje imaginario en voz alta."],
    ex: ["Predicciones vs. planes."],
    ev: ["Ejercicio de contraste will/going to."],
    r: [R.camb("Future forms")],
  },
  {
    s: "gra-conectores",
    b: "gramatica",
    lv: 2,
    t: "Conectores básicos",
    pre: ["gra-presente"],
    d: "and, but, because, so, then: enlazar ideas en un discurso mínimo.",
    o: "Enlazar ideas en un discurso coherente simple.",
    c: "Cohesión discursiva básica.",
    w: "Primer paso de la competencia discursiva; sin conectores, el habla queda en frases sueltas.",
    df: "easy",
    m: 200,
    xp: 12,
    er: ["Yuxtaponer sin conectar.", "Abusar de 'because'."],
    cr: ["Cuentas una anécdota en 5 frases enlazadas."],
    ex: ["Unir pares de frases con el conector adecuado."],
    ev: ["Ejercicio de conectores."],
    r: [R.bc("Linking words")],
  },
  {
    s: "gra-aspecto",
    b: "gramatica",
    lv: 3,
    t: "Aspecto: perfecto vs. pasado",
    pre: ["gra-pasado"],
    d: "Present perfect vs. past simple: experiencia y relevancia presente frente a hecho terminado.",
    o: "Elegir el tiempo correcto según el aspecto.",
    c: "Aspecto verbal.",
    w: "El present perfect es una de las mayores dificultades para hispanohablantes; distingue 'lo vivido/relevante' de 'lo terminado'.",
    df: "hard",
    m: 700,
    xp: 20,
    er: [
      "Usar present perfect como el pretérito perfecto español.",
      "Mezclar con past simple + tiempo definido.",
    ],
    cr: ["Eliges correctamente perfect/simple en un texto."],
    ex: ["Reescribir frases cambiando el aspecto."],
    ev: ["Ejercicio de contraste perfect/simple."],
    r: [R.camb("Present perfect"), R.bbc("Perfect vs past")],
  },
  {
    s: "gra-condicional",
    b: "gramatica",
    lv: 3,
    t: "Condicionales e hipótesis",
    pre: ["gra-pasado", "gra-futuro"],
    d: "Condicionales tipo 0–2 para expresar condiciones reales e hipotéticas.",
    o: "Hablar de lo posible y lo irreal.",
    c: "Estructuras condicionales.",
    w: "Amplían el mundo expresable más allá de lo real; requieren dominar pasado y futuro.",
    df: "hard",
    m: 600,
    xp: 20,
    er: ["Concordancia de tiempos incorrecta.", "Usar will en la cláusula if."],
    cr: ["Respondes '¿qué harías si…?' con estructura correcta."],
    ex: ["Completar condicionales según contexto."],
    ev: ["Ejercicio de condicionales 0–2."],
    r: [R.camb("Conditionals")],
  },
  {
    s: "gra-subordinacion",
    b: "gramatica",
    lv: 3,
    t: "Oraciones complejas (relativas)",
    pre: ["gra-conectores"],
    d: "Cláusulas relativas y subordinadas para producir discurso más denso y cohesionado.",
    o: "Producir oraciones complejas bien enlazadas.",
    c: "Subordinación / cohesión.",
    w: "Motor de la competencia discursiva intermedia; permite combinar ideas en vez de enumerarlas.",
    df: "hard",
    m: 600,
    xp: 20,
    er: [
      "Frases interminables sin puntuación clara.",
      "Omitir/confundir who/which/that.",
    ],
    cr: ["Combinas 10 pares de frases simples en complejas."],
    ex: ["Fusionar frases con relativas."],
    ev: ["Reescritura con subordinación."],
    r: [R.camb("Relative clauses")],
  },
  {
    s: "gra-avanzada",
    b: "gramatica",
    lv: 4,
    t: "Gramática avanzada (pasiva, reported, matices)",
    pre: ["gra-condicional", "gra-subordinacion"],
    d: "Voz pasiva, estilo indirecto, condicional 3 y matices modales.",
    o: "Expresar matices de duda, distancia y perspectiva con precisión.",
    c: "Gramática de precisión.",
    w: "Diferencia B2 de B1 en precisión y registro; consolida estructuras que dan flexibilidad y formalidad.",
    df: "expert",
    m: 900,
    xp: 24,
    er: [
      "Evitar la pasiva por miedo.",
      "Errores de concordancia en reported speech.",
    ],
    cr: ["Usas pasiva y estilo indirecto con naturalidad en un texto."],
    ex: ["Transformar activa/pasiva y directo/indirecto."],
    ev: ["Ejercicio integrado de estructuras avanzadas."],
    r: [R.camb("Passive & reported speech")],
  },

  // ───────── Comprensión auditiva ─────────
  {
    s: "aud-instrucciones",
    b: "escucha",
    lv: 1,
    t: "Comprender instrucciones y frases cotidianas",
    pre: ["fon-percepcion", "voc-nucleo-1"],
    d: "Entender frases y expresiones cotidianas en audio lento y claro (input comprensible).",
    o: "Captar información básica sobre uno mismo y el entorno.",
    c: "Comprensión auditiva inicial.",
    w: "El input comprensible es el motor de adquisición (Krashen); se empieza por audio lento y muy contextualizado.",
    df: "medium",
    m: 1200,
    xp: 16,
    er: ["Intentar entender cada palabra.", "Pánico al no captar todo."],
    cr: [
      "Sigues instrucciones simples y resúmenes vídeos CI para principiantes.",
    ],
    ex: ["Ver 10 vídeos de input comprensible y resumir en 1 frase."],
    ev: ["Comprensión de instrucciones orales."],
    r: [R.elllo("Escucha para principiantes"), R.esllab("Comprensión básica")],
  },
  {
    s: "aud-conversaciones",
    b: "escucha",
    lv: 2,
    t: "Comprender conversaciones lentas y claras",
    pre: ["aud-instrucciones", "voc-nucleo-2"],
    d: "Captar lo esencial de intercambios cotidianos algo más largos y a velocidad clara.",
    o: "Seguir conversaciones e intercambios claros.",
    c: "Comprensión auditiva cotidiana.",
    w: "El input crece en longitud y velocidad de forma gradual, apoyándose en un vocabulario ya de ~2000.",
    df: "medium",
    m: 2000,
    xp: 18,
    er: ["Bloquearse con palabras desconocidas."],
    cr: ["Resumes en 3 frases un audio de 2 minutos."],
    ex: ["Podcasts para aprendices con transcripción."],
    ev: ["Preguntas de comprensión sobre un diálogo."],
    r: [R.esllab("Diálogos graduados"), R.bbc("English at work")],
  },
  {
    s: "aud-podcasts",
    b: "escucha",
    lv: 3,
    t: "Comprender audio graduado y podcasts",
    pre: ["aud-conversaciones", "voc-3000"],
    d: "Seguir charlas y contenido más largo con apoyo (subtítulos en inglés).",
    o: "Comprender ideas principales y algunos detalles.",
    c: "Comprensión auditiva extensa.",
    w: "La cantidad de input es el factor más determinante del avance (inmersión); en B1 se pasa a contenido más largo.",
    df: "hard",
    m: 6000,
    xp: 22,
    er: ["Depender de subtítulos en español."],
    cr: ["Ves una serie corta y resumes cada episodio."],
    ex: ["Podcasts intermedios; series con subtítulos en inglés."],
    ev: ["Resumen de un podcast de 10 minutos."],
    r: [R.bbc("6 Minute English"), R.refold("Inmersión intermedia")],
  },
  {
    s: "aud-nativo",
    b: "escucha",
    lv: 4,
    t: "Comprender contenido nativo",
    pre: ["aud-podcasts", "voc-5000"],
    d: "Seguir series, noticias y la mayoría del habla nativa sin subtítulos.",
    o: "Entender contenido para nativos sin apoyo.",
    c: "Comprensión de contenido nativo.",
    w: "La meta B2 es la autonomía de escucha; se abandonan los subtítulos progresivamente.",
    df: "hard",
    m: 9000,
    xp: 26,
    er: ["Abandonar los subtítulos demasiado tarde."],
    cr: ["Ves una película sin subtítulos y la resumes."],
    ex: ["Medios nativos; series sin subtítulos."],
    ev: ["Comprensión de un noticiero."],
    r: [R.bbc("Noticias en inglés"), R.refold("Contenido nativo")],
  },
  {
    s: "aud-conferencias",
    b: "escucha",
    lv: 5,
    t: "Comprender conferencias y discurso académico",
    pre: ["aud-nativo", "voc-8000"],
    d: "Seguir charlas, conferencias y discurso académico o rápido, captando lo implícito.",
    o: "Entender discurso formal, rápido e implícito.",
    c: "Comprensión académica avanzada.",
    w: "C1 = flexibilidad y matiz; añade el registro académico y el habla rápida con implícitos (humor, ironía).",
    df: "expert",
    m: 6000,
    xp: 28,
    er: ["Perder los implícitos y el subtexto."],
    cr: ["Analizas el subtexto de una charla."],
    ex: ["Conferencias (p. ej. charlas divulgativas) con toma de notas."],
    ev: ["Preguntas inferenciales sobre una conferencia."],
    r: [R.elllo("Charlas avanzadas")],
  },
  {
    s: "aud-cualquier",
    b: "escucha",
    lv: 6,
    t: "Comprender cualquier acento y registro",
    pre: ["aud-conferencias"],
    d: "Entender cualquier variedad, acento y registro sin esfuerzo, incluido lo idiomático.",
    o: "Comprender sin límites de acento, registro o velocidad.",
    c: "Comprensión auditiva total.",
    w: "C2 = comprensión sin límites; se amplía la exposición a variedades regionales.",
    df: "expert",
    m: 6000,
    xp: 30,
    er: ["Dificultad con dialectos muy marcados."],
    cr: ["Comparas y comprendes 3 acentos regionales distintos."],
    ex: ["Medios de distintas regiones (UK, US, AUS…)."],
    ev: ["Comprensión de acentos variados."],
    r: [R.bbc("Acentos del inglés")],
  },

  // ───────── Lectura ─────────
  {
    s: "lec-frases",
    b: "lectura",
    lv: 1,
    t: "Leer palabras, frases y señales",
    pre: ["lec-alfabeto", "voc-nucleo-1"],
    d: "Decodificar palabras, frases sencillas y señales cotidianas con apoyo.",
    o: "Extraer información de textos muy simples.",
    c: "Lectura inicial.",
    w: "Añade un canal de input controlable por el alumno; refuerza el vocabulario núcleo.",
    df: "easy",
    m: 900,
    xp: 14,
    er: ["Subvocalizar con fonética española."],
    cr: ["Entiendes 10 mensajes/carteles reales."],
    ex: ["Leer mensajes, menús y señales."],
    ev: ["Comprensión de textos A1."],
    r: [R.bc("Reading A1"), R.tatoeba("Frases de ejemplo")],
  },
  {
    s: "lec-cotidiano",
    b: "lectura",
    lv: 2,
    t: "Leer textos cotidianos cortos",
    pre: ["lec-frases", "voc-nucleo-2"],
    d: "Leer correos, instrucciones y textos cortos, extrayendo información concreta.",
    o: "Extraer información concreta de textos cotidianos.",
    c: "Lectura funcional.",
    w: "La lectura extensiva incipiente es un crecimiento léxico barato y motivador.",
    df: "easy",
    m: 1500,
    xp: 16,
    er: ["Buscar cada palabra en el diccionario."],
    cr: ["Sigues una receta o unas instrucciones escritas."],
    ex: ["Lecturas graduadas nivel 1–2."],
    ev: ["Comprensión de un texto cotidiano."],
    r: [R.bc("Reading A2")],
  },
  {
    s: "lec-extensiva",
    b: "lectura",
    lv: 3,
    t: "Lectura extensiva (graded readers)",
    pre: ["lec-cotidiano", "voc-3000"],
    d: "Leer graded readers y artículos sencillos por volumen y placer.",
    o: "Crecer en vocabulario y fluidez lectora leyendo mucho.",
    c: "Lectura extensiva.",
    w: "La lectura extensiva produce adquisición incidental de léxico a escala; clave del avance B1.",
    df: "medium",
    m: 4000,
    xp: 20,
    er: ["Elegir textos demasiado difíciles (frustración)."],
    cr: ["Terminas un libro graduado y lo comentas."],
    ex: ["Graded readers nivel 3–4."],
    ev: ["Reseña breve de una lectura."],
    r: [R.bc("Graded readers"), R.refold("Lectura por volumen")],
  },
  {
    s: "lec-prosa",
    b: "lectura",
    lv: 4,
    t: "Leer prosa nativa (novela/prensa)",
    pre: ["lec-extensiva", "voc-5000"],
    d: "Leer con fluidez novelas accesibles y prensa general para nativos.",
    o: "Leer textos nativos generales con fluidez.",
    c: "Lectura autónoma.",
    w: "Con ~5000 familias (95% de cobertura) la lectura nativa se vuelve viable; consolida léxico de alto nivel.",
    df: "hard",
    m: 6000,
    xp: 24,
    er: ["Elegir textos aún demasiado densos."],
    cr: ["Lees una novela corta nativa."],
    ex: ["Novela accesible; prensa general."],
    ev: ["Comprensión de un artículo de prensa."],
    r: [R.bbc("Artículos"), R.oxf("Bookworms nativos")],
  },
  {
    s: "lec-especializado",
    b: "lectura",
    lv: 5,
    t: "Leer textos especializados y de análisis",
    pre: ["lec-prosa", "voc-8000"],
    d: "Leer textos densos y especializados, captando lo implícito y la postura del autor.",
    o: "Comprender textos complejos e implícitos.",
    c: "Lectura crítica.",
    w: "Prepara la mediación y la producción C1; exige el umbral de 98% de cobertura.",
    df: "expert",
    m: 5000,
    xp: 26,
    er: ["Saltarse matices por velocidad."],
    cr: ["Reseñas críticamente un texto complejo."],
    ex: ["Ensayos, prensa de análisis, literatura."],
    ev: ["Análisis crítico de un texto."],
    r: [R.camb("Lectura avanzada")],
  },
  {
    s: "lec-cualquier",
    b: "lectura",
    lv: 6,
    t: "Leer cualquier texto (literario/abstracto)",
    pre: ["lec-especializado"],
    d: "Comprender prácticamente todo lo escrito, incluidos textos literarios y abstractos.",
    o: "Comprender virtualmente cualquier texto.",
    c: "Lectura culta.",
    w: "Cierra la hebra lectora: matices literarios y estilísticos propios de C2.",
    df: "expert",
    m: 5000,
    xp: 28,
    er: ["Perder matices literarios/estilísticos."],
    cr: ["Haces un análisis literario breve."],
    ex: ["Literatura canónica y ensayo."],
    ev: ["Comentario literario."],
    r: [R.oxf("Literatura")],
  },

  // ───────── Conversación ─────────
  {
    s: "ora-preguntas-simples",
    b: "conversacion",
    lv: 1,
    t: "Responder y hacer preguntas simples",
    pre: ["voc-nucleo-1", "fon-produccion", "gra-preguntas", "cul-cortesia"],
    d: "Usar fórmulas y bloques memorizados para presentarte, pedir y responder.",
    o: "Producir mensajes cortos predecibles (nivel Novice).",
    c: "Interacción oral inicial.",
    w: "Converge léxico, sonidos, preguntas y cortesía; el 'chunking' permite hablar antes de dominar la gramática y baja el miedo a hablar.",
    df: "medium",
    m: 900,
    xp: 18,
    er: ["Querer construir todo desde cero.", "Miedo a hablar."],
    cr: ["Pides algo en una tienda (real o simulada) usando fórmulas."],
    ex: ["Juegos de rol guiados."],
    ev: ["Interacción breve evaluada."],
    r: [R.bc("Speaking A1"), R.tatoeba("Frases de conversación")],
  },
  {
    s: "ora-cotidiana",
    b: "conversacion",
    lv: 2,
    t: "Conversaciones cotidianas",
    pre: [
      "ora-preguntas-simples",
      "voc-nucleo-2",
      "gra-pasado",
      "gra-futuro",
      "aud-conversaciones",
      "cul-normas",
    ],
    d: "Mantener intercambios simples sobre temas familiares ('crear con la lengua').",
    o: "Interactuar en situaciones cotidianas predecibles.",
    c: "Interacción oral cotidiana.",
    w: "Nodo de convergencia (corazón del DAG): requiere léxico, tiempos verbales, escucha y normas sociales; marca el paso a la interacción real.",
    df: "hard",
    m: 2000,
    xp: 22,
    er: [
      "Traducir mentalmente.",
      "Silencios largos por buscar la palabra exacta.",
    ],
    cr: ["Sostienes 5 min de conversación sobre tu vida."],
    ex: ["Intercambios de idioma; juegos de rol."],
    ev: ["Conversación evaluada de 5 minutos."],
    r: [R.bc("Speaking A2"), R.elllo("Modelos de conversación")],
  },
  {
    s: "ora-narrar",
    b: "conversacion",
    lv: 3,
    t: "Narrar experiencias y desenvolverse",
    pre: [
      "ora-cotidiana",
      "gra-aspecto",
      "gra-condicional",
      "voc-3000",
      "est-compensacion",
    ],
    d: "Contar experiencias y manejar situaciones no ensayadas (viajes, imprevistos).",
    o: "Mantener la comunicación cuando algo se sale del guion.",
    c: "Autonomía comunicativa.",
    w: "Marca el salto A2→B1: requiere aspecto, condicionales y estrategias de compensación para no bloquearse.",
    df: "hard",
    m: 3000,
    xp: 24,
    er: ["Rendirse ante lo imprevisto en vez de rodear el problema."],
    cr: ["Resuelves un 'problema de viaje' hablado (perdiste el tren…)."],
    ex: ["Simulaciones de situaciones imprevistas."],
    ev: ["Rol de resolución de problemas."],
    r: [R.bc("Speaking B1")],
  },
  {
    s: "ora-debatir",
    b: "conversacion",
    lv: 4,
    t: "Debatir y argumentar opiniones",
    pre: [
      "ora-narrar",
      "gra-avanzada",
      "aud-nativo",
      "voc-5000",
      "fon-entonacion",
    ],
    d: "Conversar con nativos con espontaneidad y defender una postura con argumentos.",
    o: "Interactuar con fluidez y argumentar.",
    c: "Interacción argumentativa.",
    w: "Convergencia B2: escucha nativa + gramática fina + entonación + léxico amplio; sin ellos, la fluidez sacrifica la precisión (fosilización).",
    df: "expert",
    m: 4000,
    xp: 26,
    er: ["Fluidez a costa de precisión.", "No estructurar el argumento."],
    cr: ["Sostienes un debate de 10 minutos."],
    ex: ["Debates con roles."],
    ev: ["Debate evaluado por fluidez y argumentación."],
    r: [R.bc("Speaking B2")],
  },
  {
    s: "ora-persuadir",
    b: "conversacion",
    lv: 5,
    t: "Persuadir y exponer con eficacia",
    pre: ["ora-debatir", "voc-8000", "cul-referentes", "flu-pensar"],
    d: "Expresarte con fluidez, precisión y flexibilidad en contextos sociales, académicos y profesionales.",
    o: "Persuadir y exponer con eficacia en cualquier contexto.",
    c: "Discurso persuasivo (nivel Superior).",
    w: "C1: la lengua se usa como herramienta profesional; requiere pensar en el idioma y referentes culturales.",
    df: "expert",
    m: 5000,
    xp: 28,
    er: ["Usar un único registro para todo."],
    cr: ["Das una charla de 10 min con turno de preguntas."],
    ex: ["Presentaciones y reuniones simuladas."],
    ev: ["Exposición evaluada."],
    r: [R.owl("Public speaking")],
  },
  {
    s: "ora-adaptar",
    b: "conversacion",
    lv: 6,
    t: "Adaptar el lenguaje al contexto (sutileza)",
    pre: ["ora-persuadir", "voc-matiz", "cul-intercultural"],
    d: "Transmitir matices finos de significado con naturalidad casi nativa, adaptando registro y tono.",
    o: "Comunicar con precisión y sutileza casi nativas.",
    c: "Dominio pragmático (nivel Distinguished).",
    w: "C2: la maestría es elegir el matiz y el registro exactos en cada situación.",
    df: "expert",
    m: 5000,
    xp: 30,
    er: ["Sobre-formalidad.", "Calcos sutiles de la L1."],
    cr: ["Improvisas sobre un tema abstracto con matiz y adecuación."],
    ex: ["Improvisación sobre temas variados."],
    ev: ["Muestra de habla evaluada por sutileza."],
    r: [R.bc("Advanced speaking")],
  },

  // ───────── Escritura ─────────
  {
    s: "esc-frases",
    b: "escritura",
    lv: 1,
    t: "Escribir datos y frases simples",
    pre: ["lec-alfabeto", "gra-oracion"],
    d: "Rellenar formularios y escribir notas y frases muy simples.",
    o: "Comunicar datos básicos por escrito.",
    c: "Escritura inicial.",
    w: "Escribir frases simples es de nivel A1 (rellenar formularios, notas); prerrequisito que a menudo se omite.",
    df: "easy",
    m: 400,
    xp: 12,
    er: ["Calcar la estructura oral.", "Errores de ortografía básica."],
    cr: ["Rellenas un formulario y escribes 5 notas correctas."],
    ex: ["Completar formularios y notas."],
    ev: ["Corrección de frases escritas."],
    r: [R.bc("Writing A1")],
  },
  {
    s: "esc-mensajes",
    b: "escritura",
    lv: 2,
    t: "Mensajes y correos simples",
    pre: ["esc-frases", "lec-cotidiano", "gra-pasado"],
    d: "Escribir mensajes, notas y correos electrónicos sencillos.",
    o: "Comunicarte por escrito en situaciones cotidianas.",
    c: "Escritura funcional.",
    w: "El output escrito consolida la gramática (pasado) con tiempo para monitorizar; requiere leer modelos cotidianos.",
    df: "medium",
    m: 900,
    xp: 16,
    er: ["Registro inconsistente.", "Estructura oral en un correo."],
    cr: ["Escribes un correo de 80–100 palabras."],
    ex: ["Plantillas de correos/mensajes."],
    ev: ["Correo evaluado con rúbrica."],
    r: [R.bc("Writing A2")],
  },
  {
    s: "esc-textos",
    b: "escritura",
    lv: 3,
    t: "Textos conectados (opinión, carta)",
    pre: ["esc-mensajes", "gra-subordinacion"],
    d: "Redactar textos con estructura (opinión, descripción, carta) en párrafos coherentes.",
    o: "Organizar ideas en párrafos coherentes.",
    c: "Escritura discursiva.",
    w: "Consolida el discurso escrito con tiempo de monitorización; requiere subordinación para conectar ideas.",
    df: "medium",
    m: 1500,
    xp: 18,
    er: ["Falta de párrafos/conectores.", "Registro inconsistente."],
    cr: ["Redactas una opinión de 200 palabras estructurada."],
    ex: ["Escribir una carta de opinión."],
    ev: ["Texto evaluado con rúbrica."],
    r: [R.owl("Estructura de párrafos"), R.bc("Writing B1")],
  },
  {
    s: "esc-argumentativo",
    b: "escritura",
    lv: 4,
    t: "Textos argumentativos y detallados",
    pre: ["esc-textos", "gra-avanzada"],
    d: "Redactar textos claros y detallados con argumentos y cohesión.",
    o: "Argumentar por escrito con claridad.",
    c: "Escritura argumentativa.",
    w: "Se alinea con los criterios de escritura B2 de los exámenes (IELTS/TOEFL); requiere gramática avanzada.",
    df: "hard",
    m: 2500,
    xp: 22,
    er: ["Cohesión y párrafos débiles."],
    cr: ["Escribes un ensayo argumentativo de 300 palabras."],
    ex: ["Ensayo con tesis y contraargumento."],
    ev: ["Ensayo evaluado con rúbrica tipo examen."],
    r: [R.owl("Argumentative essays")],
  },
  {
    s: "esc-complejo",
    b: "escritura",
    lv: 5,
    t: "Textos complejos estructurados",
    pre: ["esc-argumentativo", "voc-8000"],
    d: "Escribir textos bien estructurados sobre temas complejos, con estilo y cohesión.",
    o: "Escribir con estilo y cohesión sobre temas complejos.",
    c: "Escritura experta.",
    w: "Se alinea con la escritura C1 (informes, textos académicos/profesionales); requiere léxico avanzado.",
    df: "expert",
    m: 3500,
    xp: 26,
    er: ["Cohesión de nivel superior débil.", "Tono inadecuado."],
    cr: ["Escribes un informe/ensayo de 600 palabras."],
    ex: ["Informe académico o profesional."],
    ev: ["Texto evaluado por estructura y estilo."],
    r: [R.owl("Academic writing")],
  },
  {
    s: "esc-estilo",
    b: "escritura",
    lv: 6,
    t: "Escritura con estilo y registro",
    pre: ["esc-complejo", "est-mediacion", "cul-intercultural"],
    d: "Escribir con estilo, cohesión y adecuación a distintos géneros y registros.",
    o: "Escribir con voz propia y adecuación total al género.",
    c: "Escritura de autor.",
    w: "Cierra la hebra escrita: dominio del estilo y del registro propio de C2; se apoya en mediación y competencia intercultural.",
    df: "expert",
    m: 4000,
    xp: 30,
    er: ["Voz/estilo poco natural."],
    cr: ["Escribes un artículo publicable en el género elegido."],
    ex: ["Escritura creativa o profesional con edición."],
    ev: ["Texto evaluado por estilo y adecuación."],
    r: [R.owl("Style & genre")],
  },

  // ───────── Cultura ─────────
  {
    s: "cul-cortesia",
    b: "cultura",
    lv: 1,
    t: "Cortesía, saludos y tabúes básicos",
    pre: ["voc-supervivencia"],
    d: "Fórmulas de saludo/cortesía, small talk y 2–3 tabúes culturales clave del mundo anglófono.",
    o: "Interactuar sin ofender y con las convenciones del primer contacto.",
    c: "Competencia intercultural inicial (Byram).",
    w: "La cultura es parte de la competencia comunicativa desde el día 1: saludar, la cortesía y el 'please/thank you' son contenido A1, no un añadido tardío.",
    df: "easy",
    m: 300,
    xp: 12,
    er: [
      "Trasladar la cortesía del español.",
      "Omitir 'please' (suena brusco en inglés).",
    ],
    cr: [
      "Saludas y haces small talk adecuados a un contexto formal e informal.",
    ],
    ex: ["Role-play de saludos formal/informal."],
    ev: ["Interacción de cortesía evaluada."],
    r: [R.bc("Politeness & greetings")],
  },
  {
    s: "cul-normas",
    b: "cultura",
    lv: 2,
    t: "Normas sociales y pragmática",
    pre: ["cul-cortesia", "ora-preguntas-simples"],
    d: "Cómo pedir, agradecer, rechazar y disculparse de forma adecuada (indirectness inglesa).",
    o: "Actuar según las normas pragmáticas cotidianas.",
    c: "Pragmática / competencia sociolingüística.",
    w: "El inglés es más indirecto que el español al pedir/rechazar; ignorarlo causa malentendidos, así que se aborda pronto (A2).",
    df: "medium",
    m: 500,
    xp: 14,
    er: ["Peticiones demasiado directas (suenan groseras)."],
    cr: ["Formulas la misma petición en registro formal e informal."],
    ex: ["Reescribir peticiones directas como corteses."],
    ev: ["Rol de peticiones y disculpas."],
    r: [R.bc("Making requests politely")],
  },
  {
    s: "cul-registro",
    b: "cultura",
    lv: 3,
    t: "Registro y adecuación al contexto",
    pre: ["cul-normas", "ora-cotidiana"],
    d: "Adecuar el lenguaje al contexto: formal vs. informal, hablado vs. escrito.",
    o: "Elegir el registro adecuado a cada situación.",
    c: "Competencia sociolingüística.",
    w: "La adecuación al contexto es competencia sociolingüística de nivel B1; evita sonar fuera de lugar.",
    df: "medium",
    m: 700,
    xp: 16,
    er: ["Usar un único registro para todo.", "Jerga en contextos formales."],
    cr: ["Resuelves 3 situaciones con el registro correcto."],
    ex: ["Clasificar expresiones por registro."],
    ev: ["Rol con cambios de registro."],
    r: [R.bc("Formal and informal English")],
  },
  {
    s: "cul-humor",
    b: "cultura",
    lv: 4,
    t: "Humor, ironía y matices de registro",
    pre: ["cul-registro", "aud-nativo"],
    d: "Captar y usar humor, ironía, sarcasmo y understatement típicos del inglés.",
    o: "Entender y producir humor e ironía culturales.",
    c: "Pragmática cultural avanzada.",
    w: "Requiere gran exposición previa a input nativo; el humor y el understatement son muy culturales en inglés (B2).",
    df: "hard",
    m: 1500,
    xp: 20,
    er: ["Interpretar la ironía literalmente."],
    cr: ["Explicas 5 chistes/expresiones culturales."],
    ex: ["Analizar comedia y sitcoms."],
    ev: ["Interpretación de humor/ironía."],
    r: [R.bbc("British humour")],
  },
  {
    s: "cul-referentes",
    b: "cultura",
    lv: 5,
    t: "Referentes culturales, historia y actualidad",
    pre: ["cul-humor", "lec-especializado"],
    d: "Referencias culturales, históricas y de actualidad del mundo anglófono.",
    o: "Entender referencias culturales, históricas y de actualidad.",
    c: "Conocimiento sociocultural.",
    w: "La competencia intercultural crítica (Byram) se profundiza en C1; sin referentes se pierden capas de significado.",
    df: "hard",
    m: 2000,
    xp: 22,
    er: ["Perder referencias culturales en textos/medios."],
    cr: ["Explicas 10 referentes culturales relevantes."],
    ex: ["Analizar prensa y cultura anglófona."],
    ev: ["Ensayo sobre un tema cultural."],
    r: [R.bbc("Cultura y actualidad")],
  },
  {
    s: "cul-intercultural",
    b: "cultura",
    lv: 6,
    t: "Competencia intercultural crítica",
    pre: ["cul-referentes", "aud-cualquier"],
    d: "Variación dialectal, mediación entre culturas y conciencia crítica (savoir s'engager).",
    o: "Mediar entre culturas y dominar la variación dialectal.",
    c: "Competencia intercultural plena.",
    w: "La lengua es cultura; cierra el árbol con la conciencia crítica intercultural de Byram (C2).",
    df: "expert",
    m: 3000,
    xp: 28,
    er: ["Perder matices dialectales o culturales."],
    cr: ["Comparas registros/dialectos de dos regiones y medias entre ambos."],
    ex: ["Comparación intercultural."],
    ev: ["Tarea de mediación intercultural."],
    r: [R.bc("Intercultural awareness")],
  },

  // ───────── Fluidez ─────────
  {
    s: "flu-automatizar",
    b: "fluidez",
    lv: 2,
    t: "Automatizar frases (shadowing)",
    pre: ["ora-preguntas-simples", "aud-conversaciones"],
    d: "Repetir tras el audio (shadowing) para automatizar frases frecuentes.",
    o: "Responder sin pensar en lo ya conocido.",
    c: "Fluidez inicial y prosodia.",
    w: "Es la 'hebra de fluidez' de Nation: sin automatizar lo conocido, el conocimiento no se convierte en uso.",
    df: "medium",
    m: 1200,
    xp: 16,
    er: ["Priorizar lo nuevo y nunca automatizar lo conocido."],
    cr: ["Haces shadowing de un diálogo de 1 min con soltura."],
    ex: ["Shadowing diario de audios cortos."],
    ev: ["Producción fluida de frases automatizadas."],
    r: [R.elllo("Audios para shadowing"), R.refold("Técnica de shadowing")],
  },
  {
    s: "flu-conversacional",
    b: "fluidez",
    lv: 3,
    t: "Fluidez conversacional",
    pre: ["flu-automatizar", "ora-narrar"],
    d: "Reducir pausas, usar muletillas útiles y producir bloques más largos sin traducir.",
    o: "Hablar de forma más continua y natural sobre lo conocido.",
    c: "Fluidez conversacional.",
    w: "La fluidez debe crecer entre A2 y C1, no ser un único nodo; en B1 se busca continuidad y menos pausas.",
    df: "medium",
    m: 2000,
    xp: 18,
    er: ["Pararse a buscar la palabra 'perfecta'.", "Silencios largos."],
    cr: ["Monólogo de 2 min sobre un tema conocido sin pausas largas."],
    ex: ["Técnica 4/3/2 (repetir contando el mismo relato más rápido)."],
    ev: ["Monólogo evaluado por fluidez."],
    r: [R.bc("Fluency practice")],
  },
  {
    s: "flu-pensar",
    b: "fluidez",
    lv: 5,
    t: "Pensar en el idioma",
    pre: ["flu-conversacional", "ora-debatir"],
    d: "Producir sin traducción mental; monólogo interno en inglés.",
    o: "Comunicarte sin traducir internamente.",
    c: "Automatización avanzada.",
    w: "Cima de la hebra de fluidez; sostiene la persuasión y la exposición eficaz (C1).",
    df: "hard",
    m: 3000,
    xp: 22,
    er: ["Traducir internamente bajo presión."],
    cr: ["Pasas un día pensando/relatando tu jornada en inglés."],
    ex: ["Monólogo interno guiado."],
    ev: ["Producción espontánea sin latencia de traducción."],
    r: [R.refold("Pensar en el idioma")],
  },

  // ───────── Hitos de nivel (compuertas) ─────────
  {
    s: "hito-a1",
    b: "hito",
    lv: 1,
    t: "Hito A1 · Supervivencia",
    pre: [
      "aud-instrucciones",
      "lec-frases",
      "ora-preguntas-simples",
      "esc-frases",
      "cul-cortesia",
      "gra-presente",
    ],
    d: "Comprendes y usas expresiones cotidianas básicas; te presentas y haces preguntas simples si te hablan despacio.",
    o: "Consolidar el nivel A1 en las cuatro destrezas + cultura.",
    c: "Usuario básico inicial (CEFR A1).",
    w: "Compuerta que confirma un avance equilibrado de todas las hebras en A1 antes de pasar a A2.",
    df: "easy",
    m: 60,
    xp: 40,
    er: [],
    cr: ["Superas una autoevaluación A1 en las 4 destrezas."],
    ex: ["Recorrido integrado A1."],
    ev: ["Autoevaluación tipo can-do A1."],
    r: [R.bc("Test de nivel A1")],
  },
  {
    s: "hito-a2",
    b: "hito",
    lv: 2,
    t: "Hito A2 · Conversación básica",
    pre: [
      "aud-conversaciones",
      "lec-cotidiano",
      "ora-cotidiana",
      "esc-mensajes",
      "cul-normas",
      "flu-automatizar",
    ],
    d: "Te desenvuelves en tareas cotidianas simples e intercambias información básica sobre temas familiares.",
    o: "Consolidar el nivel A2.",
    c: "Usuario básico (CEFR A2).",
    w: "Confirma el avance equilibrado en A2, incluida la fluidez inicial.",
    df: "medium",
    m: 60,
    xp: 50,
    er: [],
    cr: ["Superas una autoevaluación A2 en las 4 destrezas."],
    ex: ["Recorrido integrado A2."],
    ev: ["Autoevaluación can-do A2."],
    r: [R.bc("Test de nivel A2")],
  },
  {
    s: "hito-b1",
    b: "hito",
    lv: 3,
    t: "Hito B1 · Independencia",
    pre: [
      "aud-podcasts",
      "lec-extensiva",
      "ora-narrar",
      "esc-textos",
      "cul-registro",
      "flu-conversacional",
    ],
    d: "Te manejas en la mayoría de situaciones de viaje; narras experiencias y explicas opiniones y planes.",
    o: "Consolidar el nivel B1.",
    c: "Usuario independiente (CEFR B1).",
    w: "Confirma el avance equilibrado en B1 (autonomía comunicativa).",
    df: "hard",
    m: 60,
    xp: 60,
    er: [],
    cr: ["Superas una autoevaluación B1 en las 4 destrezas."],
    ex: ["Recorrido integrado B1."],
    ev: ["Autoevaluación can-do B1."],
    r: [R.bc("Test de nivel B1")],
  },
  {
    s: "hito-b2",
    b: "hito",
    lv: 4,
    t: "Hito B2 · Fluidez funcional",
    pre: [
      "aud-nativo",
      "lec-prosa",
      "ora-debatir",
      "esc-argumentativo",
      "cul-humor",
      "fon-entonacion",
    ],
    d: "Interactúas con fluidez y naturalidad con nativos; entiendes textos complejos y argumentas con claridad.",
    o: "Consolidar el nivel B2.",
    c: "Usuario independiente avanzado (CEFR B2).",
    w: "Confirma el avance equilibrado en B2, incluida la entonación.",
    df: "expert",
    m: 60,
    xp: 80,
    er: [],
    cr: ["Superas una autoevaluación B2 en las 4 destrezas."],
    ex: ["Recorrido integrado B2."],
    ev: ["Autoevaluación can-do B2."],
    r: [R.bc("Test de nivel B2")],
  },
  {
    s: "hito-c1",
    b: "hito",
    lv: 5,
    t: "Hito C1 · Dominio operativo",
    pre: [
      "aud-conferencias",
      "lec-especializado",
      "ora-persuadir",
      "esc-complejo",
      "cul-referentes",
      "est-mediacion",
    ],
    d: "Usas la lengua de forma flexible y eficaz para fines sociales, académicos y profesionales; comprendes lo implícito.",
    o: "Consolidar el nivel C1.",
    c: "Usuario competente (CEFR C1).",
    w: "Confirma el avance equilibrado en C1, incluida la mediación.",
    df: "expert",
    m: 60,
    xp: 100,
    er: [],
    cr: ["Superas una autoevaluación C1 en las 4 destrezas."],
    ex: ["Recorrido integrado C1."],
    ev: ["Autoevaluación can-do C1."],
    r: [R.bc("Test de nivel C1")],
  },
  {
    s: "hito-c2",
    b: "hito",
    lv: 6,
    t: "Hito C2 · Maestría",
    pre: [
      "aud-cualquier",
      "lec-cualquier",
      "ora-adaptar",
      "esc-estilo",
      "cul-intercultural",
      "fon-nativo",
    ],
    d: "Comprendes prácticamente todo y te expresas con precisión y sutileza casi nativas.",
    o: "Consolidar el nivel C2 (maestría).",
    c: "Usuario competente experto (CEFR C2).",
    w: "Cierre del árbol: confirma la maestría en todas las hebras.",
    df: "expert",
    m: 60,
    xp: 150,
    er: [],
    cr: ["Superas una autoevaluación C2 integral."],
    ex: ["Recorrido integrado C2."],
    ev: ["Autoevaluación can-do C2."],
    r: [R.bc("Test de nivel C2")],
  },
];

/**
 * Validación pura del DAG antes de insertarlo. Verifica: slugs únicos,
 * prerrequisitos existentes, ausencia de ciclos, alcanzabilidad desde una raíz,
 * ausencia de nodos aislados y continuidad de todas las hebras hasta C2.
 * Lanza un error si algo falla (evita sembrar un árbol roto en producción).
 */
export function validateEnglishTree(nodes: EnNode[] = EN_NODES): {
  ok: boolean;
  errors: string[];
} {
  const errors: string[] = [];
  const bySlug = new Map(nodes.map((n) => [n.s, n]));

  // Slugs únicos.
  if (bySlug.size !== nodes.length) errors.push("Hay slugs duplicados.");

  // Prerrequisitos existentes.
  for (const n of nodes)
    for (const p of n.pre)
      if (!bySlug.has(p))
        errors.push(`${n.s}: prerrequisito inexistente '${p}'.`);

  // Sin ciclos (DFS con colores).
  const color = new Map<string, number>(); // 0 sin visitar, 1 en pila, 2 hecho
  const dfs = (slug: string): boolean => {
    color.set(slug, 1);
    for (const p of bySlug.get(slug)?.pre ?? []) {
      const c = color.get(p) ?? 0;
      if (c === 1) return true; // arista de retroceso → ciclo
      if (c === 0 && dfs(p)) return true;
    }
    color.set(slug, 2);
    return false;
  };
  for (const n of nodes)
    if ((color.get(n.s) ?? 0) === 0 && dfs(n.s)) {
      errors.push(`Ciclo detectado en o cerca de '${n.s}'.`);
      break;
    }

  // Alcanzabilidad desde raíces (BFS por aristas de desbloqueo).
  const roots = nodes
    .filter((n) => n.root || n.pre.length === 0)
    .map((n) => n.s);
  if (roots.length === 0)
    errors.push("No hay ninguna raíz (nodo sin prerrequisitos).");
  const unlocks = new Map<string, string[]>();
  for (const n of nodes)
    for (const p of n.pre) unlocks.set(p, [...(unlocks.get(p) ?? []), n.s]);
  const reachable = new Set<string>(roots);
  const queue = [...roots];
  while (queue.length) {
    const cur = queue.shift()!;
    for (const nxt of unlocks.get(cur) ?? [])
      if (!reachable.has(nxt)) {
        reachable.add(nxt);
        queue.push(nxt);
      }
  }
  for (const n of nodes)
    if (!reachable.has(n.s))
      errors.push(`'${n.s}' no es alcanzable desde una raíz.`);

  // Sin nodos aislados (todo nodo tiene prereq o desbloquea a alguien).
  for (const n of nodes)
    if (n.pre.length === 0 && !(unlocks.get(n.s)?.length ?? 0) && !n.root)
      errors.push(`'${n.s}' está aislado.`);

  // Continuidad de hebras hasta C2: el hito C2 depende (transitivamente) de
  // al menos un nodo de cada rama de competencia.
  const c2 = bySlug.get("hito-c2");
  if (c2) {
    const anc = new Set<string>();
    const stack = [...c2.pre];
    while (stack.length) {
      const s = stack.pop()!;
      if (anc.has(s)) continue;
      anc.add(s);
      for (const p of bySlug.get(s)?.pre ?? []) stack.push(p);
    }
    const branchesReached = new Set([...anc].map((s) => bySlug.get(s)?.b));
    for (const b of Object.keys(EN_BRANCHES))
      if (b !== "hito" && !branchesReached.has(b))
        errors.push(`La rama '${b}' no tiene continuidad hasta C2.`);
  }

  return { ok: errors.length === 0, errors };
}

/** Posición X por rama (para separar visualmente las hebras). */
function laneX(branch: string): number {
  const i = Math.max(0, LANE.indexOf(branch));
  return 120 + i * 150;
}

/**
 * Inserta (o reemplaza) el árbol de Inglés de forma idempotente, respetando la
 * arquitectura Tree → Skill → SkillPrerequisite → Resource. Seguro de re-ejecutar.
 */
export async function upsertEnglishTree(
  db: PrismaClient,
): Promise<{ tree: string; skills: number; prerequisites: number }> {
  // No sembrar un árbol inválido.
  const check = validateEnglishTree();
  if (!check.ok) {
    throw new Error(
      `Árbol de Inglés inválido:\n- ${check.errors.join("\n- ")}`,
    );
  }

  // Categoría Idiomas (crea si falta; no toca otras categorías).
  const category = await db.category.upsert({
    where: { slug: "idiomas" },
    update: {},
    create: {
      slug: "idiomas",
      name: "Idiomas",
      description: "Aprende a comunicarte en nuevos idiomas.",
      icon: "🌍",
      order: 0,
    },
  });

  // Árbol (reemplaza sus skills para reflejar la versión más reciente).
  const existing = await db.tree.findUnique({ where: { slug: "ingles" } });
  if (existing) {
    await db.skill.deleteMany({ where: { treeId: existing.id } });
  }
  const tree = existing
    ? await db.tree.update({
        where: { id: existing.id },
        data: {
          categoryId: category.id,
          title: "Inglés · de cero a dominio (C2)",
          description:
            "Aprende inglés desde cero hasta un nivel avanzado siguiendo cómo se adquiere realmente una lengua: por competencias que evolucionan (escucha, habla, lectura, escritura, vocabulario, gramática, pronunciación, cultura, estrategias y fluidez).",
          difficulty: "beginner",
          status: "PUBLISHED",
        },
      })
    : await db.tree.create({
        data: {
          categoryId: category.id,
          slug: "ingles",
          title: "Inglés · de cero a dominio (C2)",
          description:
            "Aprende inglés desde cero hasta un nivel avanzado siguiendo cómo se adquiere realmente una lengua: por competencias que evolucionan (escucha, habla, lectura, escritura, vocabulario, gramática, pronunciación, cultura, estrategias y fluidez).",
          difficulty: "beginner",
          status: "PUBLISHED",
        },
      });

  const idBySlug: Record<string, string> = {};
  let order = 0;
  for (const n of EN_NODES) {
    const created = await db.skill.create({
      data: {
        treeId: tree.id,
        slug: n.s,
        title: n.t,
        description: n.d,
        objective: n.o,
        branch: n.b,
        difficulty: n.df,
        tier: n.lv,
        xpReward: n.xp,
        estimatedMinutes: n.m,
        positionX: laneX(n.b),
        positionY: n.lv * 130,
        isRoot: !!n.root,
        order: order++,
        content: {
          competency: n.c,
          rationale: n.w,
          commonErrors: n.er,
          masteryCriteria: n.cr,
          exercises: n.ex,
          assessments: n.ev,
        },
        resources: {
          create: n.r.map((res, i) => ({
            type: res.t,
            title: res.title,
            url: res.url,
            provider: res.p,
            order: i,
          })),
        },
      },
    });
    idBySlug[n.s] = created.id;
  }

  let prerequisites = 0;
  for (const n of EN_NODES) {
    for (const pre of n.pre) {
      await db.skillPrerequisite.create({
        data: { skillId: idBySlug[n.s]!, prerequisiteId: idBySlug[pre]! },
      });
      prerequisites++;
    }
  }

  return { tree: tree.slug, skills: EN_NODES.length, prerequisites };
}
