/**
 * Árbol de habilidades: **Matemáticas** — tercera disciplina de SkillTree.
 * Publicada: visible para todos los usuarios.
 *
 * No es un temario: es un DAG de competencias diseñado a partir de currículos
 * reconocidos —Khan Academy (scope & sequence), OpenStax (Prealgebra/Algebra/
 * Precalculus/Calculus), los estándares comunes (Common Core / NCTM) y NRICH
 * (resolución de problemas, Pólya)—. Enseña a PENSAR con cantidades y patrones,
 * no a memorizar procedimientos.
 *
 * Organización: 10 GRANDES RAMAS que el usuario empieza con libertad; dentro de
 * cada una, la progresión avanza por niveles (Fundamentos → Básico →
 * Intermedio → Avanzado). Los prerrequisitos `pre` codifican el DAG conceptual
 * real. El contenido interactivo vive en `./matematicas-lessons`.
 *
 * Reutiliza al 100% el motor genérico (`upsertTree`): las fórmulas se muestran
 * con los bloques monoespaciados que ya existen; la práctica usa los mismos
 * tipos (choice/fill/order/match) y el repaso espaciado funciona desde el inicio.
 */

import type { SeedRes, TreeSpec } from "./lib";
import { MAT_LESSONS } from "./matematicas-lessons";

const R = {
  khan: (title: string): SeedRes => ({
    t: "VIDEO",
    title,
    url: "https://es.khanacademy.org/math",
    p: "Khan Academy",
  }),
  openstax: (title: string): SeedRes => ({
    t: "BOOK",
    title,
    url: "https://openstax.org/subjects/math",
    p: "OpenStax",
  }),
  mathfun: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://www.mathsisfun.com/",
    p: "Math is Fun",
  }),
  nrich: (title: string): SeedRes => ({
    t: "EXERCISE",
    title,
    url: "https://nrich.maths.org/",
    p: "NRICH (Cambridge)",
  }),
  desmos: (title: string): SeedRes => ({
    t: "OTHER",
    title,
    url: "https://www.desmos.com/calculator",
    p: "Desmos",
  }),
};

export const MATEMATICAS_SPEC: TreeSpec = {
  category: {
    slug: "matematicas",
    name: "Matemáticas",
    description:
      "Aprende a pensar con cantidades, patrones y lógica: de contar a razonar como un matemático.",
    icon: "🔢",
    order: 2,
  },
  tree: {
    slug: "matematicas-de-cero",
    title: "Matemáticas · de cero a dominio",
    description:
      "Aprende matemáticas como se entienden de verdad: razonando, no memorizando. Un árbol de competencias —números, aritmética, álgebra, geometría, funciones, datos y cálculo— con libertad para elegir por dónde empezar.",
    difficulty: "beginner",
    // Publicada: visible para todos los usuarios.
    status: "PUBLISHED",
  },
  branches: {
    razonamiento: "Razonamiento y resolución de problemas",
    numeros: "Números y operaciones",
    aritmetica: "Fracciones, decimales y porcentajes",
    algebra: "Álgebra y ecuaciones",
    geometria: "Geometría y medida",
    funciones: "Funciones y gráficas",
    datos: "Estadística y probabilidad",
    precalculo: "Trigonometría y exponenciales",
    calculo: "Cálculo",
    hito: "Hitos",
  },
  levels: ["Fundamentos", "Básico", "Intermedio", "Avanzado"],
  lessons: MAT_LESSONS,
  nodes: [
    // ───────────── Razonamiento y resolución de problemas ─────────────
    {
      s: "mat-que-es",
      b: "razonamiento",
      lv: 0,
      t: "Qué son las matemáticas",
      root: true,
      pre: [],
      d: "Las matemáticas como lenguaje de patrones y cantidades, no como memorizar reglas.",
      o: "Ver las matemáticas como una forma de pensar, no de calcular a ciegas.",
      c: "Actitud matemática.",
      w: "Sin un buen modelo mental (razonar > memorizar), todo lo demás se vuelve mecánico y frágil.",
      df: "easy",
      m: 25,
      xp: 10,
      er: ["Creer que 'ser de letras' impide aprender matemáticas.", "Memorizar sin entender."],
      cr: ["Explicas con tus palabras qué es un patrón matemático."],
      ex: ["Describir un patrón en una secuencia de números."],
      ev: ["Continuar una secuencia y justificar por qué."],
      r: [R.nrich("Qué es pensar matemáticamente"), R.mathfun("Introduction")],
    },
    {
      s: "mat-pensamiento",
      b: "razonamiento",
      lv: 0,
      t: "Pensamiento matemático",
      pre: ["mat-que-es"],
      d: "Traducir situaciones reales a operaciones y símbolos.",
      o: "Traducir un problema cotidiano a una operación matemática.",
      c: "Modelización básica.",
      w: "El paso difícil no es calcular, sino decidir QUÉ calcular.",
      df: "easy",
      m: 30,
      xp: 12,
      er: ["Operar sin entender qué representa cada número."],
      cr: ["Conviertes un enunciado en una operación correcta."],
      ex: ["Escribir la operación de un problema de reparto."],
      ev: ["Plantear (no resolver) tres problemas reales."],
      r: [R.khan("Traducir problemas"), R.nrich("Modelling")],
    },
    {
      s: "mat-resolucion",
      b: "razonamiento",
      lv: 1,
      t: "Resolver problemas (método de Pólya)",
      pre: ["mat-pensamiento"],
      d: "Comprender, planear, ejecutar y revisar: las cuatro fases de Pólya.",
      o: "Aplicar un método ordenado para atacar cualquier problema.",
      c: "Resolución estructurada de problemas.",
      w: "Un método vence al pánico ante el problema en blanco; sirve en toda la disciplina.",
      df: "medium",
      m: 35,
      xp: 14,
      er: ["Lanzarse a calcular sin entender el problema.", "No revisar si la respuesta tiene sentido."],
      cr: ["Resuelves un problema aplicando las cuatro fases y revisas el resultado."],
      ex: ["Resolver un problema de edades con las 4 fases."],
      ev: ["Explicar tu plan antes de calcular."],
      r: [R.nrich("How to solve it (Pólya)"), R.khan("Problem solving")],
    },

    // ───────────── Números y operaciones ─────────────
    {
      s: "mat-numeros",
      b: "numeros",
      lv: 0,
      t: "Números y el sistema decimal",
      pre: ["mat-que-es"],
      d: "Valor posicional: por qué el mismo dígito vale distinto según su lugar.",
      o: "Entender el valor posicional en base 10.",
      c: "Sentido numérico.",
      w: "El valor posicional sostiene toda la aritmética; sin él, las operaciones son magia.",
      df: "easy",
      m: 30,
      xp: 12,
      er: ["Ignorar el valor posicional (el 5 de 50 no es el 5 de 5)."],
      cr: ["Descompones un número por el valor de cada cifra."],
      ex: ["Escribir 3.407 como suma de valores posicionales."],
      ev: ["Comparar dos números grandes y justificar cuál es mayor."],
      r: [R.khan("Valor posicional"), R.mathfun("Place value")],
    },
    {
      s: "mat-operaciones",
      b: "numeros",
      lv: 1,
      t: "Las cuatro operaciones",
      pre: ["mat-numeros"],
      d: "Suma, resta, multiplicación y división: qué significan y cómo se relacionan.",
      o: "Elegir la operación correcta según lo que pide el problema.",
      c: "Operaciones básicas.",
      w: "Saber CUÁNDO usar cada operación importa más que calcular rápido.",
      df: "easy",
      m: 35,
      xp: 12,
      er: ["Confundir qué operación resuelve el problema.", "Multiplicar cuando toca dividir."],
      cr: ["Resuelves problemas eligiendo la operación adecuada."],
      ex: ["Repartir 24 caramelos entre 6 niños."],
      ev: ["Inventar un problema para cada operación."],
      r: [R.khan("Aritmética"), R.mathfun("Operations")],
    },
    {
      s: "mat-enteros",
      b: "numeros",
      lv: 1,
      t: "Números negativos (enteros)",
      pre: ["mat-operaciones"],
      d: "La recta numérica y las reglas de signos con sentido, no memorizadas.",
      o: "Operar con números negativos entendiendo por qué.",
      c: "Números enteros.",
      w: "Deudas, temperaturas y coordenadas necesitan negativos; las reglas de signos confunden si se memorizan.",
      df: "medium",
      m: 35,
      xp: 14,
      er: ["'Menos por menos' sin entender por qué es más.", "Restar un negativo mal."],
      cr: ["Sumas y restas enteros usando la recta numérica."],
      ex: ["Calcular la diferencia entre -3 °C y 8 °C."],
      ev: ["Situar y ordenar enteros en la recta."],
      r: [R.khan("Números negativos"), R.mathfun("Negative numbers")],
    },
    {
      s: "mat-orden-operaciones",
      b: "numeros",
      lv: 2,
      t: "Jerarquía de operaciones",
      pre: ["mat-operaciones"],
      d: "Por qué 2 + 3 × 4 = 14 y no 20: el orden importa.",
      o: "Evaluar expresiones respetando la jerarquía.",
      c: "Orden de operaciones.",
      w: "Sin un orden acordado, una misma expresión daría resultados distintos.",
      df: "medium",
      m: 30,
      xp: 14,
      er: ["Operar de izquierda a derecha ignorando la jerarquía."],
      cr: ["Evalúas una expresión con paréntesis y potencias en el orden correcto."],
      ex: ["Calcular 2 + 3 × (4 - 1)²."],
      ev: ["Detectar el error en una evaluación mal ordenada."],
      r: [R.khan("Orden de operaciones"), R.mathfun("Order of operations")],
    },
    {
      s: "mat-potencias",
      b: "numeros",
      lv: 2,
      t: "Potencias y raíces",
      pre: ["mat-orden-operaciones"],
      d: "Multiplicar un número por sí mismo; la raíz como operación inversa.",
      o: "Entender potencias y raíces como abreviaturas con sentido.",
      c: "Potenciación.",
      w: "Áreas, volúmenes, crecimiento y notación científica se apoyan en potencias.",
      df: "medium",
      m: 35,
      xp: 16,
      er: ["Confundir 2³ con 2×3.", "Creer que la raíz de una suma es la suma de raíces."],
      cr: ["Calculas potencias y raíces exactas sencillas."],
      ex: ["Calcular 5² y √49."],
      ev: ["Explicar por qué √(a²) = |a|."],
      r: [R.khan("Exponentes"), R.mathfun("Exponents")],
    },

    // ───────────── Fracciones, decimales y porcentajes ─────────────
    {
      s: "mat-fracciones",
      b: "aritmetica",
      lv: 1,
      t: "Fracciones",
      pre: ["mat-operaciones"],
      d: "Partes de un todo; fracciones equivalentes y cómo compararlas.",
      o: "Entender, comparar y simplificar fracciones.",
      c: "Fracciones.",
      w: "Las fracciones son la puerta al álgebra y a las proporciones; suelen ser el gran tropiezo.",
      df: "medium",
      m: 40,
      xp: 16,
      er: ["Sumar numeradores y denominadores directamente.", "No buscar denominador común."],
      cr: ["Sumas fracciones con distinto denominador y simplificas."],
      ex: ["Calcular 1/2 + 1/3."],
      ev: ["Ordenar tres fracciones de menor a mayor."],
      r: [R.khan("Fracciones"), R.mathfun("Fractions")],
    },
    {
      s: "mat-decimales",
      b: "aritmetica",
      lv: 1,
      t: "Decimales",
      pre: ["mat-operaciones"],
      d: "Los decimales como fracciones de base 10; operar y redondear.",
      o: "Operar con decimales y convertirlos a/desde fracciones.",
      c: "Números decimales.",
      w: "Dinero, medidas y datos casi siempre son decimales.",
      df: "easy",
      m: 35,
      xp: 14,
      er: ["Desalinear la coma al sumar.", "Redondear antes de tiempo."],
      cr: ["Sumas y multiplicas decimales y redondeas bien."],
      ex: ["Calcular 2,5 × 0,4."],
      ev: ["Convertir 3/4 a decimal y viceversa."],
      r: [R.khan("Decimales"), R.mathfun("Decimals")],
    },
    {
      s: "mat-porcentajes",
      b: "aritmetica",
      lv: 2,
      t: "Porcentajes",
      pre: ["mat-decimales", "mat-fracciones"],
      d: "El porcentaje como fracción de 100; aumentos, descuentos e interés.",
      o: "Calcular porcentajes y variaciones porcentuales en contextos reales.",
      c: "Porcentajes.",
      w: "Rebajas, impuestos, propinas e intereses: el cálculo más usado en la vida diaria.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Sumar porcentajes de bases distintas.", "Confundir '20% de' con '20% más'."],
      cr: ["Calculas un descuento y un aumento porcentual."],
      ex: ["Precio final de 80 € con 25% de descuento."],
      ev: ["Explicar por qué subir 10% y bajar 10% no vuelve al inicio."],
      r: [R.khan("Porcentajes"), R.mathfun("Percentage")],
    },
    {
      s: "mat-razones",
      b: "aritmetica",
      lv: 2,
      t: "Razones y proporciones",
      pre: ["mat-fracciones"],
      d: "Comparar cantidades y usar la regla de tres con criterio.",
      o: "Resolver problemas de proporcionalidad directa.",
      c: "Proporcionalidad.",
      w: "Recetas, escalas, mapas y velocidades son proporciones.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Aplicar regla de tres cuando NO hay proporcionalidad."],
      cr: ["Resuelves un problema con regla de tres justificada."],
      ex: ["Si 3 kg cuestan 6 €, ¿cuánto cuestan 5 kg?"],
      ev: ["Detectar una relación que no es proporcional."],
      r: [R.khan("Razones y proporciones"), R.mathfun("Ratios")],
    },

    // ───────────── Álgebra y ecuaciones ─────────────
    {
      s: "mat-variables",
      b: "algebra",
      lv: 2,
      t: "Variables y expresiones",
      pre: ["mat-orden-operaciones"],
      d: "Usar letras para representar cantidades desconocidas o generales.",
      o: "Escribir y evaluar expresiones con variables.",
      c: "Lenguaje algebraico.",
      w: "La variable es el salto de la aritmética al álgebra: generalizar.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Creer que 'x' es siempre un único número fijo.", "Mal la evaluación por sustitución."],
      cr: ["Traduces un enunciado a una expresión algebraica y la evalúas."],
      ex: ["Escribir 'el doble de un número más 3'."],
      ev: ["Evaluar 2x + 3 para varios valores de x."],
      r: [R.khan("Expresiones algebraicas"), R.openstax("Prealgebra")],
    },
    {
      s: "mat-ecuaciones",
      b: "algebra",
      lv: 2,
      t: "Ecuaciones de primer grado",
      pre: ["mat-variables"],
      d: "Una balanza: lo que haces a un lado, lo haces al otro.",
      o: "Resolver ecuaciones lineales con una incógnita.",
      c: "Ecuaciones lineales.",
      w: "Resolver 'para x' es una de las herramientas más transferibles de todas.",
      df: "medium",
      m: 45,
      xp: 20,
      er: ["No aplicar la misma operación a ambos lados.", "Cambiar de signo al pasar mal un término."],
      cr: ["Resuelves 2x + 3 = 11 y compruebas la solución."],
      ex: ["Resolver 3x - 5 = 10."],
      ev: ["Plantear y resolver una ecuación de un problema."],
      r: [R.khan("Ecuaciones lineales"), R.openstax("Elementary Algebra")],
    },
    {
      s: "mat-sistemas",
      b: "algebra",
      lv: 3,
      t: "Sistemas de ecuaciones",
      pre: ["mat-ecuaciones"],
      d: "Dos ecuaciones, dos incógnitas: sustitución e igualación.",
      o: "Resolver un sistema lineal 2×2.",
      c: "Sistemas lineales.",
      w: "Mezclas, cruces de tarifas y equilibrios se modelan con sistemas.",
      df: "hard",
      m: 50,
      xp: 22,
      er: ["Resolver una ecuación e ignorar la otra."],
      cr: ["Resuelves un sistema 2×2 por sustitución."],
      ex: ["Resolver x+y=10, x-y=2."],
      ev: ["Interpretar la solución como intersección de dos rectas."],
      r: [R.khan("Sistemas de ecuaciones"), R.desmos("Graficar rectas")],
    },
    {
      s: "mat-cuadraticas",
      b: "algebra",
      lv: 3,
      t: "Ecuaciones cuadráticas",
      pre: ["mat-ecuaciones", "mat-potencias"],
      d: "Ecuaciones con x²; factorización y fórmula general.",
      o: "Resolver ecuaciones de segundo grado.",
      c: "Ecuaciones cuadráticas.",
      w: "Trayectorias, áreas y optimización llevan a cuadráticas.",
      df: "hard",
      m: 55,
      xp: 24,
      er: ["Olvidar la segunda solución.", "Errores de signo en la fórmula general."],
      cr: ["Resuelves una cuadrática por factorización o fórmula."],
      ex: ["Resolver x² - 5x + 6 = 0."],
      ev: ["Relacionar las soluciones con los cortes en el eje x."],
      r: [R.khan("Ecuaciones cuadráticas"), R.mathfun("Quadratic equation")],
    },

    // ───────────── Geometría y medida ─────────────
    {
      s: "mat-figuras",
      b: "geometria",
      lv: 1,
      t: "Figuras y ángulos",
      pre: ["mat-numeros"],
      d: "Puntos, rectas, ángulos y las figuras planas básicas.",
      o: "Reconocer y clasificar figuras y ángulos.",
      c: "Geometría básica.",
      w: "El vocabulario geométrico es la base para medir y demostrar.",
      df: "easy",
      m: 35,
      xp: 14,
      er: ["Confundir tipos de ángulo (agudo/obtuso)."],
      cr: ["Clasificas ángulos y triángulos correctamente."],
      ex: ["Clasificar tres ángulos dados."],
      ev: ["Identificar figuras en un dibujo."],
      r: [R.khan("Geometría"), R.mathfun("Geometry")],
    },
    {
      s: "mat-perimetro-area",
      b: "geometria",
      lv: 2,
      t: "Perímetro y área",
      pre: ["mat-figuras", "mat-operaciones"],
      d: "Medir el contorno y la superficie de figuras planas.",
      o: "Calcular perímetros y áreas de figuras básicas.",
      c: "Medida de figuras.",
      w: "Suelos, terrenos, telas y pantallas se miden con área y perímetro.",
      df: "medium",
      m: 40,
      xp: 16,
      er: ["Confundir área con perímetro.", "Mezclar unidades (cm y m)."],
      cr: ["Calculas el área de un rectángulo y un triángulo."],
      ex: ["Área de un rectángulo de 4×3."],
      ev: ["Decidir si un problema pide área o perímetro."],
      r: [R.khan("Área y perímetro"), R.mathfun("Area")],
    },
    {
      s: "mat-pitagoras",
      b: "geometria",
      lv: 3,
      t: "Teorema de Pitágoras",
      pre: ["mat-perimetro-area", "mat-potencias"],
      d: "En un triángulo rectángulo, a² + b² = c².",
      o: "Aplicar Pitágoras para hallar un lado desconocido.",
      c: "Teorema de Pitágoras.",
      w: "Distancias, diagonales y navegación se calculan con Pitágoras.",
      df: "hard",
      m: 45,
      xp: 20,
      er: ["Aplicarlo en triángulos NO rectángulos.", "Confundir la hipotenusa."],
      cr: ["Hallas la hipotenusa dados los catetos."],
      ex: ["Catetos 3 y 4: hallar la hipotenusa."],
      ev: ["Justificar cuándo se puede aplicar el teorema."],
      r: [R.khan("Teorema de Pitágoras"), R.mathfun("Pythagoras")],
    },

    // ───────────── Funciones y gráficas ─────────────
    {
      s: "mat-plano",
      b: "funciones",
      lv: 2,
      t: "El plano cartesiano",
      pre: ["mat-enteros"],
      d: "Localizar puntos con coordenadas (x, y).",
      o: "Representar y leer puntos en el plano.",
      c: "Coordenadas.",
      w: "El plano conecta álgebra y geometría: es la base de las gráficas.",
      df: "medium",
      m: 30,
      xp: 14,
      er: ["Invertir el orden de las coordenadas (x, y)."],
      cr: ["Sitúas y lees puntos en los cuatro cuadrantes."],
      ex: ["Ubicar (3, -2) en el plano."],
      ev: ["Leer las coordenadas de puntos dados."],
      r: [R.khan("Plano cartesiano"), R.desmos("Explorar el plano")],
    },
    {
      s: "mat-funciones-intro",
      b: "funciones",
      lv: 3,
      t: "Qué es una función",
      pre: ["mat-plano", "mat-variables"],
      d: "Una máquina que a cada entrada le asigna una única salida.",
      o: "Entender el concepto de función y su gráfica.",
      c: "Concepto de función.",
      w: "La función es el objeto central de las matemáticas modernas y del cálculo.",
      df: "hard",
      m: 45,
      xp: 20,
      er: ["Creer que una entrada puede tener dos salidas."],
      cr: ["Distingues una función de una relación que no lo es."],
      ex: ["Evaluar f(x) = 2x + 1 en varios puntos."],
      ev: ["Aplicar la prueba de la recta vertical."],
      r: [R.khan("Funciones"), R.desmos("Graficar funciones")],
    },
    {
      s: "mat-lineales",
      b: "funciones",
      lv: 3,
      t: "Funciones lineales",
      pre: ["mat-funciones-intro"],
      d: "Rectas: pendiente e intersección; y = mx + b.",
      o: "Interpretar y graficar funciones lineales.",
      c: "Funciones lineales.",
      w: "El modelo de cambio constante: tarifas, velocidad, conversión de unidades.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Confundir pendiente con intersección."],
      cr: ["Interpretas la pendiente y el corte de una recta."],
      ex: ["Graficar y = 2x + 1."],
      ev: ["Deducir la ecuación de una recta desde dos puntos."],
      r: [R.khan("Funciones lineales"), R.desmos("Rectas")],
    },

    // ───────────── Estadística y probabilidad ─────────────
    {
      s: "mat-estadistica",
      b: "datos",
      lv: 2,
      t: "Estadística descriptiva",
      pre: ["mat-decimales"],
      d: "Media, mediana y moda: resumir un conjunto de datos.",
      o: "Calcular e interpretar medidas de tendencia central.",
      c: "Estadística descriptiva.",
      w: "Interpretar datos es alfabetización básica del siglo XXI.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Usar la media cuando hay valores extremos (mejor mediana)."],
      cr: ["Calculas media, mediana y moda de un conjunto."],
      ex: ["Media de 4, 8, 6, 10, 2."],
      ev: ["Elegir la medida más representativa y justificarlo."],
      r: [R.khan("Estadística"), R.mathfun("Statistics")],
    },
    {
      s: "mat-probabilidad",
      b: "datos",
      lv: 2,
      t: "Probabilidad básica",
      pre: ["mat-fracciones"],
      d: "Medir la posibilidad de un suceso entre 0 y 1.",
      o: "Calcular probabilidades de sucesos simples.",
      c: "Probabilidad.",
      w: "Riesgo, juegos, seguros y decisiones se apoyan en probabilidad.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Creer que 'toca' salir cara tras varias cruces (falacia del jugador)."],
      cr: ["Calculas la probabilidad de un suceso simple."],
      ex: ["Probabilidad de sacar par en un dado."],
      ev: ["Distinguir sucesos independientes de dependientes."],
      r: [R.khan("Probabilidad"), R.mathfun("Probability")],
    },

    // ───────────── Trigonometría y exponenciales ─────────────
    {
      s: "mat-trigonometria",
      b: "precalculo",
      lv: 3,
      t: "Trigonometría básica",
      pre: ["mat-pitagoras"],
      d: "Seno, coseno y tangente como razones en el triángulo rectángulo.",
      o: "Usar las razones trigonométricas para hallar lados y ángulos.",
      c: "Trigonometría.",
      w: "Física, ingeniería, gráficos y sonido dependen de la trigonometría.",
      df: "expert",
      m: 55,
      xp: 24,
      er: ["Confundir qué lado es opuesto/adyacente."],
      cr: ["Hallas un lado usando seno, coseno o tangente."],
      ex: ["Hallar la altura con un ángulo y una distancia."],
      ev: ["Elegir la razón adecuada según los datos."],
      r: [R.khan("Trigonometría"), R.openstax("Precalculus")],
    },
    {
      s: "mat-exponenciales",
      b: "precalculo",
      lv: 3,
      t: "Exponenciales y logaritmos",
      pre: ["mat-potencias", "mat-funciones-intro"],
      d: "Crecimiento que se acelera; el logaritmo como operación inversa.",
      o: "Entender el crecimiento exponencial y el logaritmo.",
      c: "Funciones exponenciales.",
      w: "Interés compuesto, epidemias y escalas (pH, decibelios) son exponenciales.",
      df: "expert",
      m: 55,
      xp: 24,
      er: ["Confundir crecimiento lineal con exponencial."],
      cr: ["Distingues crecimiento lineal de exponencial y usas logaritmos simples."],
      ex: ["Calcular el interés compuesto de un ahorro."],
      ev: ["Explicar por qué el log 'deshace' la potencia."],
      r: [R.khan("Exponenciales y logaritmos"), R.openstax("Precalculus")],
    },

    // ───────────── Cálculo ─────────────
    {
      s: "mat-limites",
      b: "calculo",
      lv: 3,
      t: "Límites (idea intuitiva)",
      pre: ["mat-funciones-intro"],
      d: "Acercarse infinitamente a un valor: la idea que funda el cálculo.",
      o: "Comprender intuitivamente qué es un límite.",
      c: "Límites.",
      w: "El límite es la base de derivadas e integrales.",
      df: "expert",
      m: 50,
      xp: 24,
      er: ["Confundir el límite con el valor de la función en el punto."],
      cr: ["Explicas el límite de una función con una tabla de acercamiento."],
      ex: ["Estudiar a qué se acerca (x²-1)/(x-1) cuando x→1."],
      ev: ["Interpretar un límite gráficamente."],
      r: [R.khan("Límites"), R.openstax("Calculus")],
    },
    {
      s: "mat-derivadas",
      b: "calculo",
      lv: 3,
      t: "Derivadas (razón de cambio)",
      pre: ["mat-limites", "mat-lineales"],
      d: "La derivada como pendiente instantánea y velocidad de cambio.",
      o: "Interpretar la derivada como razón de cambio.",
      c: "Derivadas.",
      w: "Optimización, física y economía usan derivadas para medir el cambio.",
      df: "expert",
      m: 60,
      xp: 26,
      er: ["Ver la derivada solo como una regla mecánica sin significado."],
      cr: ["Interpretas la derivada como pendiente/velocidad en un contexto."],
      ex: ["Relacionar posición y velocidad de un móvil."],
      ev: ["Explicar qué significa que la derivada sea cero."],
      r: [R.khan("Derivadas"), R.openstax("Calculus")],
    },

    // ───────────── Hitos ─────────────
    {
      s: "hito-mat-fundamentos",
      b: "hito",
      lv: 1,
      t: "Hito · Fundamentos",
      pre: ["mat-resolucion", "mat-operaciones", "mat-numeros"],
      d: "Consolidas el sentido numérico, las operaciones y un método para resolver problemas.",
      o: "Confirmar una base sólida de razonamiento y aritmética.",
      c: "Fundamentos matemáticos.",
      w: "Compuerta que asegura una base firme antes de subir de nivel.",
      df: "easy",
      m: 40,
      xp: 30,
      er: ["Avanzar con lagunas en el valor posicional o las operaciones."],
      cr: ["Superas un repaso integrado de fundamentos."],
      ex: ["Recorrido integrado de fundamentos."],
      ev: ["Autoevaluación de razonamiento y operaciones."],
      r: [R.khan("Repaso de aritmética")],
    },
    {
      s: "hito-mat-intermedio",
      b: "hito",
      lv: 2,
      t: "Hito · Intermedio",
      pre: ["mat-porcentajes", "mat-variables", "mat-perimetro-area"],
      d: "Dominas fracciones/porcentajes, el lenguaje algebraico y la medida.",
      o: "Confirmar la transición de la aritmética al álgebra y la geometría.",
      c: "Nivel intermedio.",
      w: "Confirma que puedes generalizar (variables) y medir el mundo.",
      df: "medium",
      m: 50,
      xp: 35,
      er: ["Pasar a lo avanzado sin soltura con las variables."],
      cr: ["Superas un repaso de aritmética avanzada, álgebra inicial y medida."],
      ex: ["Recorrido integrado intermedio."],
      ev: ["Autoevaluación intermedia."],
      r: [R.khan("Repaso de prealgebra")],
    },
    {
      s: "hito-mat-avanzado",
      b: "hito",
      lv: 3,
      t: "Hito · Avanzado",
      pre: ["mat-cuadraticas", "mat-funciones-intro", "mat-pitagoras"],
      d: "Manejas funciones, ecuaciones de segundo grado y geometría métrica.",
      o: "Confirmar la preparación para precálculo y cálculo.",
      c: "Nivel avanzado.",
      w: "Cierre que abre la puerta a trigonometría, exponenciales y cálculo.",
      df: "hard",
      m: 60,
      xp: 40,
      er: ["Saltar a cálculo sin dominar funciones."],
      cr: ["Superas un repaso de álgebra, funciones y geometría."],
      ex: ["Recorrido integrado avanzado."],
      ev: ["Autoevaluación avanzada."],
      r: [R.openstax("Precalculus")],
    },
  ],
};
