/**
 * Árbol de habilidades: **Música** — cuarta disciplina de SkillTree.
 * Publicada: visible para todos los usuarios.
 *
 * No es un temario por capítulos: es un DAG de competencias que evolucionan,
 * diseñado a partir de patrones comunes a referencias reconocidas —Berklee
 * (oído y armonía contemporánea, aprender haciendo), ABRSM y Trinity (progresión
 * graduada por competencias: oído + teoría + técnica + lectura), conservatorios
 * (notación → intervalos → escalas → armonía), Coursera/MIT OCW (fundamentos)—
 * y, sobre todo, de la investigación en adquisición musical: Gordon (audiation:
 * oír música en la mente), Kodály y Suzuki ("sound before symbol": el oído y el
 * ritmo ANTES que la lectura; aprender por imitación y haciendo).
 *
 * Principio rector: se enseña a ESCUCHAR y a SENTIR el ritmo antes de leer, y a
 * COMPRENDER antes de memorizar símbolos. El árbol es agnóstico de instrumento
 * (la técnica es transferible); en el futuro pueden añadirse árboles por
 * instrumento bajo esta misma categoría.
 *
 * Reutiliza al 100% el motor genérico (`upsertTree`): la notación se representa
 * con los bloques monoespaciados que ya existen (figuras, notas, acordes como
 * texto); la práctica usa los mismos tipos (choice/fill/order/match) y el repaso
 * espaciado funciona desde el inicio. No añade ni una excepción al motor.
 */

import type { SeedRes, TreeSpec } from "./lib";
import { MUS_LESSONS } from "./musica-lessons";

const R = {
  berklee: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://online.berklee.edu/free-music-resources",
    p: "Berklee Online",
  }),
  mtnet: (title: string): SeedRes => ({
    t: "EXERCISE",
    title,
    url: "https://www.musictheory.net/lessons",
    p: "musictheory.net",
  }),
  teoria: (title: string): SeedRes => ({
    t: "EXERCISE",
    title,
    url: "https://www.teoria.com/",
    p: "teoria.com",
  }),
  ableton: (title: string): SeedRes => ({
    t: "OTHER",
    title,
    url: "https://learningmusic.ableton.com/",
    p: "Ableton · Learning Music",
  }),
  coursera: (title: string): SeedRes => ({
    t: "VIDEO",
    title,
    url: "https://www.coursera.org/learn/edinburgh-music-theory",
    p: "Coursera (Edinburgh)",
  }),
  abrsm: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://www.abrsm.org/en-us/exam-support/",
    p: "ABRSM",
  }),
};

export const MUSICA_SPEC: TreeSpec = {
  category: {
    slug: "musica",
    name: "Música",
    description:
      "Aprende música como se aprende de verdad: escuchando, sintiendo el ritmo y creando, no solo leyendo partituras.",
    icon: "🎵",
    order: 3,
  },
  tree: {
    slug: "musica-de-cero",
    title: "Música · de cero a músico",
    description:
      "Desarrolla oído, ritmo, lectura, armonía e improvisación como competencias que crecen. Aprende a escuchar y a crear, no a memorizar. Un árbol para hacerte músico, con cualquier instrumento o con tu voz.",
    difficulty: "beginner",
    // Publicada: visible para todos los usuarios.
    status: "PUBLISHED",
  },
  branches: {
    escucha: "Escucha y oído",
    ritmo: "Ritmo y tempo",
    lectura: "Lectura musical",
    melodia: "Melodía y tono",
    armonia: "Armonía",
    tecnica: "Técnica y práctica",
    improvisacion: "Improvisación",
    composicion: "Composición",
    produccion: "Producción musical",
    cultura: "Historia y cultura",
    hito: "Hitos",
  },
  levels: ["Fundamentos", "Básico", "Intermedio", "Avanzado"],
  lessons: MUS_LESSONS,
  nodes: [
    // ───────────── Escucha y oído ─────────────
    {
      s: "mus-que-es",
      b: "escucha",
      lv: 0,
      t: "Qué es la música y cómo se aprende",
      root: true,
      pre: [],
      d: "La música como sonido organizado en el tiempo; se aprende con el oído antes que con la vista.",
      o: "Entender que la música se aprende escuchando y haciendo, no memorizando símbolos.",
      c: "Actitud musical.",
      w: "Sin el principio 'sonido antes que símbolo', leer partituras se vuelve mecánico y frustrante.",
      df: "easy",
      m: 25,
      xp: 10,
      er: ["Creer que hay que leer partituras antes de tocar.", "Pensar que se necesita 'talento innato'."],
      cr: ["Explicas por qué el oído va antes que la lectura."],
      ex: ["Escuchar una canción e identificar si sube o baja de energía."],
      ev: ["Describir con tus palabras qué hace que algo 'suene a música'."],
      r: [R.berklee("Cómo se aprende música"), R.ableton("Learning Music")],
    },
    {
      s: "mus-escucha-activa",
      b: "escucha",
      lv: 0,
      t: "Escucha activa",
      pre: ["mus-que-es"],
      d: "Escuchar con atención los elementos: ritmo, melodía, instrumentos, dinámica.",
      o: "Distinguir los elementos que forman una canción al escucharla.",
      c: "Escucha analítica.",
      w: "Todo músico crece escuchando con intención; es la base del oído.",
      df: "easy",
      m: 30,
      xp: 12,
      er: ["Escuchar solo la melodía e ignorar ritmo y acompañamiento."],
      cr: ["Identificas al menos tres elementos distintos en una canción."],
      ex: ["Escuchar una canción centrándote solo en la batería."],
      ev: ["Describir la instrumentación de una pista."],
      r: [R.berklee("Escucha activa"), R.coursera("Elementos de la música")],
    },
    {
      s: "mus-oido-tono",
      b: "escucha",
      lv: 1,
      t: "Oído: agudo y grave (altura)",
      pre: ["mus-escucha-activa"],
      d: "Distinguir sonidos más agudos y más graves; la altura como una de las dimensiones del sonido.",
      o: "Reconocer de oído si un sonido es más agudo o más grave que otro.",
      c: "Percepción de altura.",
      w: "La altura es la base de la melodía, los intervalos y la lectura.",
      df: "easy",
      m: 30,
      xp: 14,
      er: ["Confundir 'más fuerte' con 'más agudo'."],
      cr: ["Ordenas tres sonidos de grave a agudo."],
      ex: ["Cantar una nota grave y otra aguda."],
      ev: ["Decir si una segunda nota sube o baja respecto a la primera."],
      r: [R.mtnet("Altura del sonido"), R.teoria("Ear training")],
    },
    {
      s: "mus-oido-intervalos",
      b: "escucha",
      lv: 2,
      t: "Reconocer intervalos de oído",
      pre: ["mus-oido-tono", "mus-intervalos"],
      d: "Asociar la distancia entre dos notas con canciones de referencia.",
      o: "Reconocer intervalos comunes usando canciones ancla.",
      c: "Oído interválico.",
      w: "Reconocer intervalos de oído es lo que permite sacar melodías y afinar.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Intentar memorizar intervalos sin una canción de referencia."],
      cr: ["Reconoces una octava y una quinta de oído."],
      ex: ["Asociar la 5ª justa con el inicio de 'Estrellita/Twinkle'."],
      ev: ["Identificar tres intervalos comunes de oído."],
      r: [R.teoria("Interval ear training"), R.mtnet("Interval identification")],
    },

    // ───────────── Ritmo y tempo ─────────────
    {
      s: "mus-pulso",
      b: "ritmo",
      lv: 0,
      t: "El pulso",
      pre: ["mus-que-es"],
      d: "El latido constante de la música; sentirlo con el cuerpo antes de contarlo.",
      o: "Sentir y mantener un pulso constante.",
      c: "Sentido del pulso.",
      w: "El pulso es el cimiento del ritmo; sin él no hay música que se sostenga.",
      df: "easy",
      m: 25,
      xp: 12,
      er: ["Acelerar o frenar sin darte cuenta.", "Confundir pulso con ritmo."],
      cr: ["Mantienes un pulso constante dando palmas con una canción."],
      ex: ["Marcar el pulso de tu canción favorita con el pie."],
      ev: ["Mantener el pulso tras bajar el volumen de la música."],
      r: [R.ableton("Beats"), R.berklee("El pulso")],
    },
    {
      s: "mus-compas",
      b: "ritmo",
      lv: 1,
      t: "Compás y métrica",
      pre: ["mus-pulso"],
      d: "Agrupar los pulsos en compases: 2/4, 3/4, 4/4; el acento del primer tiempo.",
      o: "Identificar el compás de una canción (binario, ternario, cuaternario).",
      c: "Métrica.",
      w: "El compás organiza el pulso y da carácter (vals vs. marcha).",
      df: "medium",
      m: 35,
      xp: 16,
      er: ["No sentir el acento del primer tiempo.", "Contar mal los tiempos por compás."],
      cr: ["Cuentas correctamente los tiempos de un 3/4 y un 4/4."],
      ex: ["Contar 1-2-3 sobre un vals."],
      ev: ["Decir si una canción está en 3/4 o 4/4."],
      r: [R.mtnet("Time signatures"), R.ableton("Time signatures")],
    },
    {
      s: "mus-figuras",
      b: "ritmo",
      lv: 1,
      t: "Figuras rítmicas y duración",
      pre: ["mus-pulso"],
      d: "Redonda, blanca, negra, corchea: cuánto dura cada figura respecto al pulso.",
      o: "Relacionar cada figura con su duración en pulsos.",
      c: "Duración rítmica.",
      w: "Las figuras son el vocabulario del ritmo escrito y hablado.",
      df: "medium",
      m: 35,
      xp: 16,
      er: ["Confundir la duración relativa de las figuras."],
      cr: ["Sabes cuántas negras caben en una redonda."],
      ex: ["Palmear negras y luego corcheas sobre el mismo pulso."],
      ev: ["Ordenar figuras de mayor a menor duración."],
      r: [R.mtnet("Note durations"), R.teoria("Rhythm")],
    },
    {
      s: "mus-subdivision",
      b: "ritmo",
      lv: 2,
      t: "Subdivisión y síncopa",
      pre: ["mus-compas", "mus-figuras"],
      d: "Dividir el pulso en partes iguales y acentuar los tiempos débiles (síncopa).",
      o: "Subdividir el pulso y reconocer la síncopa.",
      c: "Subdivisión rítmica.",
      w: "La subdivisión da precisión; la síncopa, groove y expresión.",
      df: "hard",
      m: 45,
      xp: 20,
      er: ["Perder el pulso al subdividir.", "No sentir la síncopa 'fuera del tiempo'."],
      cr: ["Palmeas una figura sincopada manteniendo el pulso con el pie."],
      ex: ["Decir 'ta-ka-ti-ki' subdividiendo en cuatro."],
      ev: ["Reproducir un patrón sincopado sencillo."],
      r: [R.ableton("Syncopation"), R.berklee("Subdivisión")],
    },

    // ───────────── Lectura musical ─────────────
    {
      s: "mus-pentagrama",
      b: "lectura",
      lv: 1,
      t: "El pentagrama y las claves",
      pre: ["mus-oido-tono"],
      d: "Las cinco líneas donde vive la altura; la clave fija la referencia (sol, fa).",
      o: "Entender cómo el pentagrama representa lo agudo y lo grave.",
      c: "Notación de altura.",
      w: "Es el mapa visual del sonido; se lee mejor cuando ya oyes agudo/grave.",
      df: "medium",
      m: 35,
      xp: 16,
      er: ["Leer sin tener clara la clave.", "Creer que más arriba = más fuerte (es más agudo)."],
      cr: ["Sitúas una nota más aguda por encima de otra en el pentagrama."],
      ex: ["Dibujar el pentagrama y la clave de sol."],
      ev: ["Decir cuál de dos notas escritas es más aguda."],
      r: [R.mtnet("The staff, clefs"), R.teoria("Reading")],
    },
    {
      s: "mus-notas",
      b: "lectura",
      lv: 1,
      t: "Nombres de las notas",
      pre: ["mus-pentagrama"],
      d: "Do-Re-Mi… y su equivalencia C-D-E; su lugar en el pentagrama.",
      o: "Nombrar las notas en el pentagrama en clave de sol.",
      c: "Lectura de notas.",
      w: "Nombrar notas conecta lo que oyes, lo que lees y lo que tocas.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Memorizar posiciones sin relacionarlas con el sonido."],
      cr: ["Nombras cinco notas en clave de sol sin dudar."],
      ex: ["Leer las notas de una melodía sencilla."],
      ev: ["Nombrar notas señaladas al azar."],
      r: [R.mtnet("Note identification"), R.teoria("Note reading")],
    },
    {
      s: "mus-lectura-ritmica",
      b: "lectura",
      lv: 2,
      t: "Leer ritmo escrito",
      pre: ["mus-notas", "mus-figuras"],
      d: "Combinar figuras y compás para leer un ritmo en voz alta o con palmas.",
      o: "Leer y reproducir un ritmo escrito manteniendo el pulso.",
      c: "Lectura rítmica.",
      w: "Une la notación con el ritmo real; puente hacia la lectura completa.",
      df: "hard",
      m: 45,
      xp: 20,
      er: ["Leer las notas pero no su duración."],
      cr: ["Palmeas un compás de 4/4 escrito con negras y corcheas."],
      ex: ["Leer 'ta ta ti-ti ta' de una partitura rítmica."],
      ev: ["Reproducir un ritmo escrito de dos compases."],
      r: [R.mtnet("Rhythm reading"), R.teoria("Rhythmic dictation")],
    },
    {
      s: "mus-lectura-primera-vista",
      b: "lectura",
      lv: 3,
      t: "Lectura a primera vista",
      pre: ["mus-lectura-ritmica"],
      d: "Leer y ejecutar una pieza nueva sin prepararla, mirando adelante.",
      o: "Leer a primera vista una melodía sencilla.",
      c: "Lectura a primera vista.",
      w: "Habilidad clave para tocar en grupo y aprender repertorio rápido.",
      df: "expert",
      m: 50,
      xp: 24,
      er: ["Parar ante cada error en vez de seguir el pulso.", "No mirar el compás siguiente."],
      cr: ["Lees a primera vista 4 compases sencillos sin detenerte."],
      ex: ["Leer una melodía nueva de 4 compases al primer intento."],
      ev: ["Mantener el pulso pese a un error de lectura."],
      r: [R.abrsm("Sight-reading"), R.teoria("Sight reading")],
    },

    // ───────────── Melodía y tono ─────────────
    {
      s: "mus-intervalos",
      b: "melodia",
      lv: 1,
      t: "Intervalos",
      pre: ["mus-oido-tono"],
      d: "La distancia entre dos notas; el ladrillo con el que se construyen melodías y acordes.",
      o: "Entender y nombrar intervalos por su tamaño.",
      c: "Intervalos.",
      w: "Los intervalos son la unidad de medida de melodía y armonía.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Contar mal los pasos entre notas.", "Olvidar contar la nota de partida."],
      cr: ["Nombras el intervalo entre dos notas cercanas."],
      ex: ["Medir la distancia de Do a Sol."],
      ev: ["Clasificar tres intervalos por tamaño."],
      r: [R.mtnet("Intervals"), R.teoria("Intervals")],
    },
    {
      s: "mus-escalas",
      b: "melodia",
      lv: 2,
      t: "Escalas mayores y menores",
      pre: ["mus-intervalos"],
      d: "Una escala es un patrón fijo de tonos y semitonos; mayor (alegre) vs. menor (melancólica).",
      o: "Construir una escala mayor por su patrón de tonos y semitonos.",
      c: "Escalas.",
      w: "Las escalas son la paleta de la melodía y la base de la tonalidad.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Olvidar dónde van los semitonos en la escala mayor."],
      cr: ["Construyes una escala mayor desde cualquier nota."],
      ex: ["Escribir la escala de Do mayor."],
      ev: ["Detectar la nota 'fuera de escala' en una serie."],
      r: [R.mtnet("Scales"), R.teoria("Scales")],
    },
    {
      s: "mus-tonalidad",
      b: "melodia",
      lv: 2,
      t: "Tonalidad y armadura",
      pre: ["mus-escalas"],
      d: "La nota 'hogar' (tónica) y las alteraciones fijas de cada tono (armadura).",
      o: "Entender el concepto de tonalidad y su centro.",
      c: "Tonalidad.",
      w: "La tonalidad explica por qué una melodía 'quiere volver a casa'.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Confundir la tónica con la primera nota que suena."],
      cr: ["Identificas la tónica de una melodía sencilla."],
      ex: ["Cantar una melodía y encontrar su nota de reposo."],
      ev: ["Decir en qué nota 'descansa' una melodía."],
      r: [R.mtnet("Key signatures"), R.coursera("Tonalidad")],
    },
    {
      s: "mus-melodia-construccion",
      b: "melodia",
      lv: 3,
      t: "Construir una melodía",
      pre: ["mus-escalas"],
      d: "Combinar notas de una escala con dirección, saltos y reposos para crear una melodía.",
      o: "Componer una melodía sencilla con sentido dentro de una escala.",
      c: "Construcción melódica.",
      w: "Crear melodías es donde la teoría se vuelve música propia.",
      df: "expert",
      m: 50,
      xp: 24,
      er: ["Saltos sin dirección que suenan aleatorios."],
      cr: ["Creas una melodía de 4 compases que reposa en la tónica."],
      ex: ["Improvisar una melodía con las notas de Do mayor."],
      ev: ["Justificar por qué tu melodía suena 'completa'."],
      r: [R.berklee("Melodía"), R.ableton("Melodies")],
    },

    // ───────────── Armonía ─────────────
    {
      s: "mus-acordes",
      b: "armonia",
      lv: 2,
      t: "Acordes (tríadas)",
      pre: ["mus-escalas"],
      d: "Tres notas sonando juntas; la tríada mayor y menor y su color.",
      o: "Construir tríadas mayores y menores.",
      c: "Acordes.",
      w: "Los acordes son el color y el soporte de casi toda la música.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Confundir mayor y menor.", "Apilar notas sin respetar terceras."],
      cr: ["Construyes una tríada mayor y una menor."],
      ex: ["Formar el acorde de Do mayor (Do-Mi-Sol)."],
      ev: ["Distinguir de oído un acorde mayor de uno menor."],
      r: [R.mtnet("Chords"), R.teoria("Triads")],
    },
    {
      s: "mus-progresiones",
      b: "armonia",
      lv: 3,
      t: "Progresiones de acordes",
      pre: ["mus-acordes"],
      d: "Encadenar acordes en el tiempo; progresiones que sostienen millones de canciones.",
      o: "Reconocer y tocar progresiones comunes.",
      c: "Progresiones armónicas.",
      w: "Las progresiones son el esqueleto armónico de una canción.",
      df: "expert",
      m: 50,
      xp: 24,
      er: ["Cambiar de acorde fuera de tiempo."],
      cr: ["Tocas o cantas una progresión I-V-vi-IV."],
      ex: ["Identificar la progresión de una canción pop."],
      ev: ["Predecir el siguiente acorde probable."],
      r: [R.ableton("Chords"), R.berklee("Progresiones")],
    },
    {
      s: "mus-cadencias",
      b: "armonia",
      lv: 3,
      t: "Cadencias: tensión y reposo",
      pre: ["mus-progresiones"],
      d: "Cómo los acordes crean tensión y la resuelven; la cadencia como 'punto y aparte'.",
      o: "Reconocer cadencias de reposo y de tensión.",
      c: "Cadencias.",
      w: "Las cadencias dan sentido de frase y de final a la música.",
      df: "expert",
      m: 45,
      xp: 24,
      er: ["No sentir la diferencia entre final abierto y cerrado."],
      cr: ["Distingues una cadencia conclusiva de una suspensiva."],
      ex: ["Comparar terminar en V y terminar en I."],
      ev: ["Decir si una frase 'termina' o 'sigue'."],
      r: [R.mtnet("Cadences"), R.coursera("Cadencias")],
    },
    {
      s: "mus-funciones",
      b: "armonia",
      lv: 3,
      t: "Funciones armónicas (I–IV–V)",
      pre: ["mus-progresiones"],
      d: "Cada acorde de la tonalidad cumple un papel: reposo (I), tensión (V), preparación (IV).",
      o: "Entender el papel de tónica, subdominante y dominante.",
      c: "Funciones armónicas.",
      w: "Las funciones explican por qué las progresiones funcionan (no son arbitrarias).",
      df: "expert",
      m: 50,
      xp: 26,
      er: ["Ver los acordes como colores sueltos, sin función."],
      cr: ["Etiquetas los acordes de una progresión como I, IV o V."],
      ex: ["Analizar una canción de tres acordes por función."],
      ev: ["Explicar por qué el V 'pide' volver al I."],
      r: [R.berklee("Funciones armónicas"), R.coursera("Armonía funcional")],
    },

    // ───────────── Técnica y práctica ─────────────
    {
      s: "mus-postura",
      b: "tecnica",
      lv: 1,
      t: "Postura, respiración y relajación",
      pre: ["mus-que-es"],
      d: "El cuerpo como primer instrumento: postura equilibrada, respiración y ausencia de tensión.",
      o: "Adoptar una postura relajada y respirar para tocar/cantar mejor.",
      c: "Base física.",
      w: "La tensión lesiona y limita; la técnica sana empieza por el cuerpo.",
      df: "easy",
      m: 30,
      xp: 14,
      er: ["Tocar con hombros y manos tensos.", "Aguantar la respiración."],
      cr: ["Mantienes una postura relajada durante la práctica."],
      ex: ["Revisar tensión en hombros y mandíbula al tocar."],
      ev: ["Detectar y soltar una zona de tensión."],
      r: [R.abrsm("Postura y técnica"), R.berklee("Relajación")],
    },
    {
      s: "mus-practica-deliberada",
      b: "tecnica",
      lv: 2,
      t: "Cómo practicar (práctica deliberada)",
      pre: ["mus-postura"],
      d: "Practicar con objetivo, lento y por fragmentos; la calidad supera a las horas.",
      o: "Estructurar una sesión de práctica eficaz.",
      c: "Práctica deliberada.",
      w: "La investigación (Ericsson) muestra que se progresa con práctica enfocada, no con repetición ciega.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Tocar de principio a fin repitiendo errores.", "Practicar siempre rápido."],
      cr: ["Aíslas el fragmento difícil y lo trabajas lento."],
      ex: ["Diseñar una sesión de 20 min con un objetivo claro."],
      ev: ["Explicar por qué practicar lento acelera el aprendizaje."],
      r: [R.berklee("Práctica eficaz"), R.abrsm("Practice tips")],
    },
    {
      s: "mus-tempo-metronomo",
      b: "tecnica",
      lv: 2,
      t: "Practicar con metrónomo",
      pre: ["mus-practica-deliberada", "mus-compas"],
      d: "El metrónomo como espejo del pulso; subir el tempo por pasos pequeños.",
      o: "Usar el metrónomo para ganar precisión y velocidad con control.",
      c: "Control del tempo.",
      w: "El metrónomo objetiva el pulso y estructura el progreso de velocidad.",
      df: "medium",
      m: 35,
      xp: 18,
      er: ["Subir el tempo antes de dominar el lento.", "Ignorar cuándo te adelantas o atrasas."],
      cr: ["Tocas un pasaje limpio a un tempo y lo subes un poco."],
      ex: ["Practicar una escala a 60 y luego a 72 BPM."],
      ev: ["Detectar si vas por delante o por detrás del clic."],
      r: [R.ableton("Tempo"), R.abrsm("Metrónomo")],
    },

    // ───────────── Improvisación ─────────────
    {
      s: "mus-improv-ritmica",
      b: "improvisacion",
      lv: 2,
      t: "Improvisación rítmica",
      pre: ["mus-subdivision"],
      d: "Crear patrones rítmicos propios sobre un pulso, sin miedo al error.",
      o: "Improvisar ritmos manteniendo el pulso.",
      c: "Improvisación rítmica.",
      w: "Improvisar libera la musicalidad y afianza el pulso interno.",
      df: "hard",
      m: 40,
      xp: 20,
      er: ["Perder el pulso al inventar.", "Bloquearte por miedo a 'sonar mal'."],
      cr: ["Improvisas 4 compases de percusión corporal sobre un pulso."],
      ex: ["Responder con palmas a un ritmo dado (pregunta-respuesta)."],
      ev: ["Mantener el pulso mientras improvisas."],
      r: [R.ableton("Improvisation"), R.berklee("Ritmo creativo")],
    },
    {
      s: "mus-improv-melodica",
      b: "improvisacion",
      lv: 3,
      t: "Improvisar melodías",
      pre: ["mus-escalas", "mus-improv-ritmica"],
      d: "Usar las notas de una escala para crear melodías espontáneas con sentido.",
      o: "Improvisar melodías sencillas dentro de una escala.",
      c: "Improvisación melódica.",
      w: "Es la síntesis de oído, escala y ritmo: crear en tiempo real.",
      df: "expert",
      m: 50,
      xp: 26,
      er: ["Tocar notas fuera de la escala sin intención.", "No dejar silencios."],
      cr: ["Improvisas una melodía sobre una escala manteniendo el pulso."],
      ex: ["Improvisar con la escala pentatónica sobre una base."],
      ev: ["Crear una frase con pregunta y respuesta."],
      r: [R.berklee("Improvisación"), R.ableton("Melodies")],
    },

    // ───────────── Composición ─────────────
    {
      s: "mus-motivo",
      b: "composicion",
      lv: 3,
      t: "Motivo y frase",
      pre: ["mus-melodia-construccion"],
      d: "Una idea musical corta (motivo) que se repite y transforma para crear frases.",
      o: "Crear y desarrollar un motivo musical.",
      c: "Desarrollo motívico.",
      w: "El motivo es la semilla de la composición: unidad y variedad.",
      df: "expert",
      m: 50,
      xp: 26,
      er: ["Repetir sin variar (monótono) o variar sin repetir (incoherente)."],
      cr: ["Desarrollas un motivo con repetición y variación."],
      ex: ["Tomar 3 notas y transformarlas (subir, invertir)."],
      ev: ["Identificar el motivo de una obra conocida."],
      r: [R.berklee("Composición"), R.coursera("Forma y motivo")],
    },
    {
      s: "mus-forma",
      b: "composicion",
      lv: 3,
      t: "Forma musical",
      pre: ["mus-motivo"],
      d: "Cómo se organizan las secciones (A-B-A, estrofa-estribillo) para dar estructura.",
      o: "Reconocer y usar estructuras formales básicas.",
      c: "Forma musical.",
      w: "La forma da sentido de viaje y memoria a una pieza.",
      df: "expert",
      m: 45,
      xp: 24,
      er: ["Componer sin estructura (todo suena igual o inconexo)."],
      cr: ["Analizas una canción en estrofa/estribillo."],
      ex: ["Etiquetar las secciones de una canción pop (A/B)."],
      ev: ["Esbozar la forma de una pieza propia."],
      r: [R.coursera("Forma musical"), R.berklee("Song form")],
    },

    // ───────────── Producción musical ─────────────
    {
      s: "mus-daw",
      b: "produccion",
      lv: 2,
      t: "Qué es un DAW",
      pre: ["mus-figuras"],
      d: "La estación de audio digital: grabar, secuenciar y editar música en el ordenador.",
      o: "Entender qué es un DAW y su flujo básico.",
      c: "Herramientas de producción.",
      w: "Producir democratiza la creación musical; el DAW es el estudio moderno.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Perderse en opciones antes de entender pistas y tempo."],
      cr: ["Describes qué es una pista y la línea de tiempo."],
      ex: ["Crear un patrón de batería en un DAW gratuito."],
      ev: ["Explicar el flujo grabar → editar → exportar."],
      r: [R.ableton("Making beats"), R.berklee("Producción")],
    },
    {
      s: "mus-grabacion-mezcla",
      b: "produccion",
      lv: 3,
      t: "Grabación y mezcla básica",
      pre: ["mus-daw"],
      d: "Capturar sonido con calidad y equilibrar volúmenes y frecuencias (mezcla).",
      o: "Grabar una pista y hacer una mezcla básica equilibrada.",
      c: "Grabación y mezcla.",
      w: "Una buena mezcla hace que las ideas suenen profesionales.",
      df: "expert",
      m: 55,
      xp: 26,
      er: ["Grabar con niveles saturados.", "Subir todo en vez de equilibrar."],
      cr: ["Equilibras el volumen de dos pistas."],
      ex: ["Grabar voz + acompañamiento y equilibrarlos."],
      ev: ["Detectar una pista demasiado alta en una mezcla."],
      r: [R.berklee("Mezcla"), R.ableton("Recording")],
    },

    // ───────────── Historia y cultura ─────────────
    {
      s: "mus-generos",
      b: "cultura",
      lv: 1,
      t: "Géneros y estilos",
      pre: ["mus-escucha-activa"],
      d: "Reconocer familias de música por sus rasgos (ritmo, instrumentación, forma).",
      o: "Distinguir géneros por sus rasgos característicos.",
      c: "Cultura musical.",
      w: "Conocer géneros amplía el oído y el vocabulario creativo.",
      df: "easy",
      m: 30,
      xp: 14,
      er: ["Juzgar géneros en vez de escucharlos con curiosidad."],
      cr: ["Identificas tres géneros por sus rasgos."],
      ex: ["Comparar un blues y una cumbia."],
      ev: ["Asociar un rasgo (swing, clave) con su género."],
      r: [R.coursera("Historia de la música"), R.berklee("Estilos")],
    },
    {
      s: "mus-eras",
      b: "cultura",
      lv: 2,
      t: "Eras de la música",
      pre: ["mus-generos"],
      d: "Un mapa de épocas (barroco, clásico, romántico, moderno, actual) y su sonido.",
      o: "Situar la música en su contexto histórico.",
      c: "Historia de la música.",
      w: "El contexto explica por qué la música suena como suena en cada época.",
      df: "medium",
      m: 35,
      xp: 16,
      er: ["Memorizar fechas sin escuchar ejemplos."],
      cr: ["Asocias una obra con su era por el sonido."],
      ex: ["Escuchar y ubicar tres fragmentos en su época."],
      ev: ["Ordenar cronológicamente tres estilos."],
      r: [R.coursera("Eras musicales"), R.berklee("Historia")],
    },

    // ───────────── Hitos ─────────────
    {
      s: "hito-mus-fundamentos",
      b: "hito",
      lv: 1,
      t: "Hito · Fundamentos",
      pre: ["mus-pulso", "mus-oido-tono", "mus-escucha-activa"],
      d: "Consolidas el oído básico y el sentido del pulso: la base de todo músico.",
      o: "Confirmar una base sólida de oído y ritmo.",
      c: "Fundamentos musicales.",
      w: "Compuerta que asegura oído y pulso antes de leer y armonizar.",
      df: "easy",
      m: 40,
      xp: 30,
      er: ["Avanzar a la lectura sin sentir el pulso ni distinguir alturas."],
      cr: ["Superas un repaso de escucha activa, altura y pulso."],
      ex: ["Recorrido integrado de fundamentos."],
      ev: ["Autoevaluación de oído y ritmo."],
      r: [R.teoria("Ear & rhythm review")],
    },
    {
      s: "hito-mus-intermedio",
      b: "hito",
      lv: 2,
      t: "Hito · Intermedio",
      pre: ["mus-escalas", "mus-notas", "mus-acordes"],
      d: "Manejas escalas, lectura de notas y tríadas: teoría que ya suena a música.",
      o: "Confirmar la transición de los fundamentos a la teoría aplicada.",
      c: "Nivel intermedio.",
      w: "Confirma que unes oído, lectura y armonía básica.",
      df: "medium",
      m: 50,
      xp: 35,
      er: ["Pasar a armonía avanzada sin dominar escalas y acordes."],
      cr: ["Superas un repaso de escalas, lectura y tríadas."],
      ex: ["Recorrido integrado intermedio."],
      ev: ["Autoevaluación intermedia."],
      r: [R.mtnet("Theory review")],
    },
    {
      s: "hito-mus-avanzado",
      b: "hito",
      lv: 3,
      t: "Hito · Avanzado",
      pre: ["mus-progresiones", "mus-melodia-construccion", "mus-lectura-primera-vista"],
      d: "Compones melodías, entiendes progresiones y lees a primera vista: piensas como músico.",
      o: "Confirmar madurez musical: oído, teoría, lectura y creación.",
      c: "Nivel avanzado.",
      w: "Cierre que abre la puerta a la composición, la improvisación y la producción.",
      df: "expert",
      m: 60,
      xp: 40,
      er: ["Tocar sin entender lo que ocurre armónicamente."],
      cr: ["Superas un repaso de armonía, melodía y lectura."],
      ex: ["Recorrido integrado avanzado."],
      ev: ["Autoevaluación avanzada."],
      r: [R.berklee("Musicianship review")],
    },
  ],
};
