/**
 * Árbol de habilidades: **Programación** — la disciplina de referencia que
 * demuestra que el motor de SkillTree es agnóstico.
 *
 * No es un temario ni el índice de un libro: es un DAG de competencias diseñado
 * a partir de principios comunes a fuentes reconocidas —ACM/IEEE CS2023
 * (concepto sobre lenguaje), Harvard CS50 (fundamentos → web), roadmap.sh
 * (dependencias reales), The Odin Project y freeCodeCamp (aprender construyendo),
 * MDN y la documentación oficial (HTML/CSS/JS, Git, SQL), y los clásicos de
 * algoritmos y estructuras de datos—.
 *
 * Organización: 13 GRANDES RAMAS (competencias) que el usuario puede empezar con
 * libertad; dentro de cada una, la progresión avanza por niveles
 * (Fundamentos → Básico → Intermedio → Avanzado). Los prerrequisitos `pre`
 * codifican el DAG conceptual real (validado: acíclico y alcanzable). El árbol
 * está pensado para crecer durante años añadiendo ramas y niveles.
 *
 * Base pedagógica: enseñar a PENSAR, no sintaxis por sintaxis. Los fundamentos
 * usan Python (claro para principiantes, como MIT 6.0001/CS50); las ramas de
 * web usan HTML/CSS/JS; datos usa SQL. El contenido interactivo vive en
 * `./programacion-lessons`.
 */

import type { SeedRes, TreeSpec } from "./lib";
import { PROG_LESSONS } from "./programacion-lessons";

const R = {
  py: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://docs.python.org/es/3/tutorial/",
    p: "Python (oficial)",
  }),
  cs50: (title: string): SeedRes => ({
    t: "VIDEO",
    title,
    url: "https://cs50.harvard.edu/x/",
    p: "Harvard CS50",
  }),
  fcc: (title: string): SeedRes => ({
    t: "EXERCISE",
    title,
    url: "https://www.freecodecamp.org/learn/",
    p: "freeCodeCamp",
  }),
  odin: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://www.theodinproject.com/",
    p: "The Odin Project",
  }),
  mdn: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://developer.mozilla.org/es/docs/Learn",
    p: "MDN",
  }),
  roadmap: (title: string): SeedRes => ({
    t: "OTHER",
    title,
    url: "https://roadmap.sh/",
    p: "roadmap.sh",
  }),
  git: (title: string): SeedRes => ({
    t: "BOOK",
    title,
    url: "https://git-scm.com/book/es/v2",
    p: "Pro Git",
  }),
  sql: (title: string): SeedRes => ({
    t: "EXERCISE",
    title,
    url: "https://sqlbolt.com/",
    p: "SQLBolt",
  }),
  automate: (title: string): SeedRes => ({
    t: "BOOK",
    title,
    url: "https://automatetheboringstuff.com/",
    p: "Automate the Boring Stuff",
  }),
};

export const PROGRAMACION_SPEC: TreeSpec = {
  category: {
    slug: "programacion",
    name: "Programación",
    description: "Aprende a crear software desde cero: lógica, código y buenas prácticas.",
    icon: "💻",
    order: 1,
  },
  tree: {
    slug: "python-desde-cero",
    title: "Programación · de cero a profesional",
    description:
      "Aprende a programar como se aprende de verdad: pensando soluciones y construyendo. Un árbol de competencias —fundamentos, funciones, POO, algoritmos, estructuras de datos, web, bases de datos, APIs e ingeniería— con libertad para elegir por dónde empezar.",
    difficulty: "beginner",
    // Revisión del fundador antes del lanzamiento público (solo ADMIN la ve).
    status: "DRAFT",
  },
  branches: {
    pensamiento: "Pensamiento computacional",
    fundamentos: "Fundamentos del código",
    control: "Control de flujo",
    datos: "Datos y colecciones",
    funciones: "Funciones y modularidad",
    poo: "Programación orientada a objetos",
    algoritmos: "Algoritmos y complejidad",
    estructuras: "Estructuras de datos",
    web: "Web: HTML, CSS y JavaScript",
    persistencia: "Bases de datos",
    apis: "APIs y la red",
    ingenieria: "Calidad e ingeniería",
    hito: "Hitos",
  },
  levels: ["Fundamentos", "Básico", "Intermedio", "Avanzado"],
  lessons: PROG_LESSONS,
  nodes: [
    // ───────────── Pensamiento computacional ─────────────
    {
      s: "prog-que-es",
      b: "pensamiento",
      lv: 0,
      t: "Qué es programar",
      root: true,
      pre: [],
      d: "Qué es un programa y cómo 'piensa' (literalmente) una computadora.",
      o: "Entender qué es un programa y el ciclo de ejecución.",
      c: "Modelo mental de la computación.",
      w: "Es la raíz: sin un modelo mental correcto (la máquina es literal), todo confunde.",
      df: "easy",
      m: 30,
      xp: 10,
      er: ["Creer que la máquina entiende intenciones."],
      cr: ["Explicas qué es un programa y ejecutas tu primera línea."],
      ex: ["Escribir y ejecutar un print()."],
      ev: ["Explicar con tus palabras qué hace un programa."],
      r: [R.cs50("Bienvenida a CS50"), R.py("El intérprete de Python")],
    },
    {
      s: "prog-pensamiento",
      b: "pensamiento",
      lv: 0,
      t: "Pensamiento computacional",
      pre: ["prog-que-es"],
      d: "Descomponer problemas, ver patrones, abstraer y escribir algoritmos.",
      o: "Descomponer un problema en pasos ordenados (pseudocódigo).",
      c: "Resolución estructurada de problemas.",
      w: "Programar es pensar antes que teclear; sostiene todo el árbol.",
      df: "easy",
      m: 40,
      xp: 12,
      er: ["Empezar a codificar sin plan."],
      cr: ["Escribes el algoritmo de una tarea cotidiana sin ambigüedad."],
      ex: ["Pseudocódigo de una receta paso a paso."],
      ev: ["Que otra persona siga tu algoritmo literalmente."],
      r: [R.cs50("Computational thinking"), R.odin("How to think")],
    },
    {
      s: "prog-logica",
      b: "pensamiento",
      lv: 1,
      t: "Lógica y booleanos",
      pre: ["prog-pensamiento"],
      d: "Verdadero/falso, AND/OR/NOT y tablas de verdad: la base de toda decisión.",
      o: "Razonar con lógica booleana para construir condiciones correctas.",
      c: "Lógica proposicional aplicada.",
      w: "Toda condición, filtro y validación se apoya en lógica booleana.",
      df: "easy",
      m: 40,
      xp: 12,
      er: ["Confundir AND con OR.", "Negaciones dobles mal razonadas."],
      cr: ["Construyes una condición compuesta correcta y la explicas."],
      ex: ["Tabla de verdad de (A and not B)."],
      ev: ["Predecir el resultado de expresiones booleanas."],
      r: [R.cs50("Boolean logic"), R.mdn("Operadores lógicos")],
    },
    {
      s: "prog-abstraccion",
      b: "pensamiento",
      lv: 2,
      t: "Abstracción y descomposición",
      pre: ["prog-funciones"],
      d: "Ocultar el detalle tras interfaces simples y dividir un problema en piezas.",
      o: "Diseñar soluciones por capas de abstracción.",
      c: "Abstracción de software.",
      w: "Es cómo se domina la complejidad; base de funciones, módulos y objetos.",
      df: "medium",
      m: 45,
      xp: 16,
      er: ["Abstraer de más (complejidad inútil).", "Fugas de abstracción."],
      cr: ["Divides un problema en piezas con responsabilidad única."],
      ex: ["Rediseñar un programa monolítico en funciones con nombres claros."],
      ev: ["Explicar la interfaz de una pieza sin su implementación."],
      r: [R.cs50("Abstraction"), R.roadmap("Fundamentals")],
    },

    // ───────────── Fundamentos del código ─────────────
    {
      s: "prog-entorno",
      b: "fundamentos",
      lv: 0,
      t: "Tu entorno: ejecutar código",
      pre: ["prog-que-es"],
      d: "Dónde escribir y ejecutar código; el ciclo escribir→ejecutar→ver.",
      o: "Ejecutar tu propio código y leer su salida.",
      c: "Manejo del entorno de desarrollo.",
      w: "Sin ejecutar y ver resultados no hay práctica ni retroalimentación.",
      df: "easy",
      m: 30,
      xp: 10,
      er: ["Instalar todo antes de escribir una línea."],
      cr: ["Ejecutas código y comentas líneas."],
      ex: ["Imprimir texto y una operación; añadir comentarios."],
      ev: ["Ejecutar un script corto y explicar su salida."],
      r: [R.py("Usar el intérprete"), R.automate("Setting up")],
    },
    {
      s: "prog-variables",
      b: "fundamentos",
      lv: 1,
      t: "Variables y tipos",
      pre: ["prog-entorno", "prog-pensamiento"],
      d: "Guardar datos con variables; tipos str, int, float, bool.",
      o: "Guardar y reutilizar datos eligiendo el tipo correcto.",
      c: "Manejo de datos y memoria del programa.",
      w: "Las variables son la memoria: todo programa guarda y transforma datos.",
      df: "easy",
      m: 40,
      xp: 12,
      er: ["Confundir '42' (texto) con 42 (número)."],
      cr: ["Creas variables de cada tipo y las combinas."],
      ex: ["Ficha de datos con str/int/float y type()."],
      ev: ["Predecir el tipo de varias expresiones."],
      r: [R.py("Tipos"), R.fcc("Variables")],
    },
    {
      s: "prog-operadores",
      b: "fundamentos",
      lv: 1,
      t: "Operadores y expresiones",
      pre: ["prog-variables"],
      d: "Aritméticos (+ - * / // % **) y de comparación (== != < >).",
      o: "Calcular y comparar valores; distinguir = de ==.",
      c: "Cálculo y evaluación de expresiones.",
      w: "Cómo el programa 'razona'; base de las decisiones.",
      df: "easy",
      m: 35,
      xp: 12,
      er: ["Usar = para comparar (es ==)."],
      cr: ["Predices el resultado de //, %, ** y comparaciones."],
      ex: ["Comprobar paridad con %."],
      ev: ["Evaluar expresiones mixtas y verificar."],
      r: [R.py("Operadores"), R.fcc("Arithmetic")],
    },
    {
      s: "prog-entrada-salida",
      b: "fundamentos",
      lv: 1,
      t: "Entrada y salida",
      pre: ["prog-variables"],
      d: "Mostrar con print() y pedir datos con input() (y convertirlos).",
      o: "Interactuar con el usuario: mostrar y recibir datos.",
      c: "Interacción básica programa–usuario.",
      w: "Un programa útil dialoga; convertir la entrada evita errores de tipo.",
      df: "easy",
      m: 30,
      xp: 12,
      er: ["Olvidar que input() da texto."],
      cr: ["Pides un número, lo conviertes y calculas con él."],
      ex: ["Saludo personalizado con nombre y edad."],
      ev: ["Programa que pide datos y responde sin romperse."],
      r: [R.py("input y print"), R.automate("Input/Output")],
    },
    {
      s: "prog-strings",
      b: "fundamentos",
      lv: 1,
      t: "Cadenas de texto",
      pre: ["prog-variables"],
      d: "Concatenar, medir (len), f-strings, métodos e indexado.",
      o: "Manipular texto: unir, medir y transformar cadenas.",
      c: "Procesamiento de texto.",
      w: "El texto está en todos los programas; dominarlo es una habilidad diaria.",
      df: "easy",
      m: 40,
      xp: 12,
      er: ["Olvidar que se indexa desde 0."],
      cr: ["Usas f-strings y métodos con soltura."],
      ex: ["Tarjeta de presentación con f-strings."],
      ev: ["Transformar un texto según reglas."],
      r: [R.py("Cadenas"), R.fcc("Strings")],
    },

    // ───────────── Control de flujo ─────────────
    {
      s: "prog-condicionales",
      b: "control",
      lv: 1,
      t: "Condicionales (if/elif/else)",
      pre: ["prog-operadores", "prog-logica"],
      d: "Tomar decisiones según condiciones; indentación de bloques.",
      o: "Ejecutar código distinto según se cumpla una condición.",
      c: "Toma de decisiones (control de flujo).",
      w: "Aquí el código empieza a decidir; base de toda lógica.",
      df: "medium",
      m: 45,
      xp: 15,
      er: ["Indentación incorrecta.", "Usar = en la condición."],
      cr: ["Escribes if/elif/else y combinas con and/or."],
      ex: ["Clasificar un número."],
      ev: ["Programa que decide entre 3+ casos."],
      r: [R.py("if/elif/else"), R.fcc("Conditional logic")],
    },
    {
      s: "prog-bucles",
      b: "control",
      lv: 1,
      t: "Bucles (for/while)",
      pre: ["prog-condicionales"],
      d: "Repetir con for y range(); repetir con while; evitar bucles infinitos.",
      o: "Repetir acciones de forma controlada.",
      c: "Iteración (control de flujo).",
      w: "La repetición hace potente a la computación; imprescindible.",
      df: "medium",
      m: 45,
      xp: 15,
      er: ["Error por uno con range.", "Bucle infinito."],
      cr: ["Usas for y while y controlas la parada."],
      ex: ["Tabla de multiplicar."],
      ev: ["Sumar/contar recorriendo."],
      r: [R.py("Bucles"), R.fcc("Loops")],
    },

    // ───────────── Datos y colecciones ─────────────
    {
      s: "prog-listas",
      b: "datos",
      lv: 1,
      t: "Listas (arrays)",
      pre: ["prog-bucles"],
      d: "Colecciones ordenadas: crear, indexar (desde 0), append, recorrer.",
      o: "Almacenar y recorrer colecciones ordenadas.",
      c: "Estructuras de datos secuenciales.",
      w: "La colección que más usarás; encaja con los bucles.",
      df: "medium",
      m: 45,
      xp: 15,
      er: ["Índice desde 0.", "Salirse de rango."],
      cr: ["Creas, modificas y recorres listas."],
      ex: ["Lista de la compra."],
      ev: ["Procesar una lista con un bucle."],
      r: [R.py("Listas"), R.fcc("Arrays")],
    },
    {
      s: "prog-diccionarios",
      b: "datos",
      lv: 2,
      t: "Diccionarios y conjuntos",
      pre: ["prog-listas", "prog-funciones"],
      d: "Pares clave→valor; cuándo usar dict vs lista; conjuntos.",
      o: "Guardar y consultar datos por clave.",
      c: "Estructuras de datos asociativas.",
      w: "Modela datos etiquetados (agenda, JSON); complementa a las listas.",
      df: "medium",
      m: 45,
      xp: 18,
      er: ["Acceder a una clave inexistente."],
      cr: ["Creas y consultas diccionarios; eliges dict vs lista."],
      ex: ["Contar frecuencias con un diccionario."],
      ev: ["Modelar una ficha como diccionario."],
      r: [R.py("Diccionarios"), R.fcc("Objects")],
    },
    {
      s: "prog-matrices",
      b: "datos",
      lv: 2,
      t: "Anidamiento y matrices",
      pre: ["prog-listas"],
      d: "Listas de listas y estructuras anidadas; recorrerlas con bucles anidados.",
      o: "Modelar datos en 2D y estructuras compuestas.",
      c: "Datos anidados.",
      w: "Tableros, tablas y datos reales suelen ser anidados.",
      df: "medium",
      m: 40,
      xp: 16,
      er: ["Confundir filas y columnas.", "Bucles anidados mal indexados."],
      cr: ["Recorres una matriz e imprimes por filas."],
      ex: ["Sumar una matriz 3x3."],
      ev: ["Buscar un valor en una estructura anidada."],
      r: [R.py("Listas anidadas")],
    },

    // ───────────── Funciones y modularidad ─────────────
    {
      s: "prog-funciones",
      b: "funciones",
      lv: 2,
      t: "Funciones",
      pre: ["hito-prog-fundamentos"],
      d: "Definir (def), parámetros, argumentos y return; reutilización.",
      o: "Encapsular y reutilizar lógica con funciones.",
      c: "Modularidad y reutilización.",
      w: "La herramienta nº1 contra la repetición; puerta a programas grandes.",
      df: "medium",
      m: 50,
      xp: 18,
      er: ["Confundir print con return."],
      cr: ["Escribes funciones con parámetros y return y las reutilizas."],
      ex: ["area_rectangulo(base, altura) que devuelve el área."],
      ev: ["Refactorizar código repetido en funciones."],
      r: [R.py("Funciones"), R.fcc("Functions")],
    },
    {
      s: "prog-alcance",
      b: "funciones",
      lv: 2,
      t: "Ámbito y closures",
      pre: ["prog-funciones"],
      d: "Variables locales vs globales; qué ve cada función y por qué.",
      o: "Controlar dónde vive y quién ve cada variable.",
      c: "Ámbito léxico.",
      w: "Evita bugs sutiles por variables compartidas; base de patrones avanzados.",
      df: "medium",
      m: 40,
      xp: 16,
      er: ["Depender de variables globales.", "Sombrear nombres sin querer."],
      cr: ["Explicas por qué una variable no es visible fuera de su función."],
      ex: ["Contador con estado encapsulado."],
      ev: ["Predecir qué imprime un ejemplo con ámbitos."],
      r: [R.py("Ámbito y espacios de nombres")],
    },
    {
      s: "prog-modulos",
      b: "funciones",
      lv: 2,
      t: "Módulos y librerías",
      pre: ["prog-funciones"],
      d: "Reutilizar código ajeno: import, la librería estándar y paquetes.",
      o: "Aprovechar módulos y librerías en tus programas.",
      c: "Reutilización a gran escala.",
      w: "No reinventes la rueda: la potencia está en el ecosistema.",
      df: "medium",
      m: 40,
      xp: 16,
      er: ["Reescribir lo que ya existe.", "Confundir módulo con función."],
      cr: ["Importas y usas un módulo estándar (random, math)."],
      ex: ["Juego de adivinar el número con random."],
      ev: ["Resolver una tarea con la librería estándar."],
      r: [R.py("Módulos"), R.py("Librería estándar")],
    },
    {
      s: "prog-recursion",
      b: "funciones",
      lv: 3,
      t: "Recursión",
      pre: ["prog-funciones"],
      d: "Funciones que se llaman a sí mismas: caso base y caso recursivo.",
      o: "Resolver problemas definiéndolos en términos de sí mismos.",
      c: "Pensamiento recursivo.",
      w: "Elegante para estructuras anidadas (árboles) y base de muchos algoritmos.",
      df: "hard",
      m: 55,
      xp: 22,
      er: ["Olvidar el caso base (recursión infinita)."],
      cr: ["Escribes una función recursiva con caso base correcto."],
      ex: ["Factorial y suma de una lista de forma recursiva."],
      ev: ["Convertir un bucle en recursión y viceversa."],
      r: [R.cs50("Recursion"), R.py("Recursión")],
    },

    // ───────────── Programación orientada a objetos ─────────────
    {
      s: "prog-oop",
      b: "poo",
      lv: 2,
      t: "Objetos y clases",
      pre: ["prog-funciones"],
      d: "Modelar el mundo con datos + comportamiento: clases, atributos y métodos.",
      o: "Definir clases y crear objetos que agrupan estado y conducta.",
      c: "Paradigma orientado a objetos.",
      w: "Organiza programas grandes; base de la mayoría de frameworks.",
      df: "hard",
      m: 60,
      xp: 22,
      er: ["Una clase gigante que hace todo.", "Confundir clase con instancia."],
      cr: ["Defines una clase con atributos y métodos y creas objetos."],
      ex: ["Clase Cuenta con depositar() y retirar()."],
      ev: ["Modelar un dominio simple con 2-3 clases."],
      r: [R.py("Clases"), R.odin("OOP basics")],
    },
    {
      s: "prog-herencia",
      b: "poo",
      lv: 3,
      t: "Herencia y polimorfismo",
      pre: ["prog-oop"],
      d: "Reutilizar y especializar clases; un mismo método, distintos comportamientos.",
      o: "Diseñar jerarquías de clases sin duplicar código.",
      c: "Reutilización orientada a objetos.",
      w: "Modela relaciones 'es-un' y permite código extensible.",
      df: "hard",
      m: 55,
      xp: 22,
      er: ["Abusar de la herencia (preferir composición).", "Jerarquías profundas frágiles."],
      cr: ["Creas una subclase que sobreescribe un método."],
      ex: ["Figura → Círculo/Cuadrado con area()."],
      ev: ["Explicar cuándo herencia vs composición."],
      r: [R.py("Herencia"), R.roadmap("OOP")],
    },
    {
      s: "prog-solid",
      b: "poo",
      lv: 3,
      t: "Encapsulación y principios",
      pre: ["prog-herencia"],
      d: "Ocultar el estado, responsabilidad única e introducción a SOLID.",
      o: "Diseñar objetos cohesivos y poco acoplados.",
      c: "Diseño orientado a objetos.",
      w: "Separa el buen diseño del código que se vuelve inmantenible.",
      df: "expert",
      m: 60,
      xp: 24,
      er: ["Exponer todo el estado.", "Clases con múltiples responsabilidades."],
      cr: ["Refactorizas una clase para que tenga una sola responsabilidad."],
      ex: ["Aplicar responsabilidad única a un ejemplo."],
      ev: ["Detectar violaciones de SOLID en un fragmento."],
      r: [R.roadmap("SOLID"), R.odin("Clean OOP")],
    },

    // ───────────── Algoritmos y complejidad ─────────────
    {
      s: "prog-algoritmos",
      b: "algoritmos",
      lv: 2,
      t: "Pensar algoritmos",
      pre: ["prog-funciones", "prog-bucles"],
      d: "Diseñar la solución antes de codificar; patrones acumulador/búsqueda/filtro.",
      o: "Diseñar y validar una solución antes de escribir código.",
      c: "Diseño de algoritmos.",
      w: "Codificar es fácil; diseñar bien la solución es lo que distingue.",
      df: "hard",
      m: 55,
      xp: 20,
      er: ["Teclear sin plan.", "No probar la lógica a mano."],
      cr: ["Escribes pseudocódigo con patrones y lo traduces."],
      ex: ["Contar pares en una lista."],
      ev: ["Resolver un problema nuevo diseñando primero."],
      r: [R.cs50("Algorithms"), R.odin("Problem solving")],
    },
    {
      s: "prog-complejidad",
      b: "algoritmos",
      lv: 3,
      t: "Eficiencia (Big-O)",
      pre: ["prog-algoritmos", "prog-diccionarios"],
      d: "Por qué unas soluciones escalan y otras no; notación Big-O intuitiva.",
      o: "Razonar sobre el coste de un algoritmo y elegir el más eficiente.",
      c: "Análisis de complejidad.",
      w: "Con datos grandes, la eficiencia decide si tu programa es usable.",
      df: "hard",
      m: 60,
      xp: 24,
      er: ["Optimizar antes de que funcione.", "Ignorar el coste de operaciones."],
      cr: ["Comparas dos soluciones y explicas cuál escala mejor."],
      ex: ["Buscar en lista O(n) vs en diccionario O(1)."],
      ev: ["Clasificar algoritmos por su crecimiento."],
      r: [R.cs50("Efficiency"), R.roadmap("Big-O")],
    },
    {
      s: "prog-busqueda",
      b: "algoritmos",
      lv: 3,
      t: "Algoritmos de búsqueda",
      pre: ["prog-algoritmos"],
      d: "Búsqueda lineal vs binaria; por qué ordenar habilita buscar rápido.",
      o: "Elegir y aplicar la búsqueda adecuada.",
      c: "Algoritmos de búsqueda.",
      w: "Buscar es la operación más común; hacerlo bien importa a escala.",
      df: "hard",
      m: 45,
      xp: 20,
      er: ["Búsqueda binaria sobre datos no ordenados."],
      cr: ["Implementas búsqueda binaria correcta."],
      ex: ["Adivina el número con estrategia binaria."],
      ev: ["Comparar pasos de lineal vs binaria."],
      r: [R.cs50("Search"), R.roadmap("Search algorithms")],
    },
    {
      s: "prog-ordenacion",
      b: "algoritmos",
      lv: 3,
      t: "Algoritmos de ordenación",
      pre: ["prog-complejidad"],
      d: "Idea de ordenaciones simples vs eficientes; por qué existen tantas.",
      o: "Entender cómo y por qué se ordena, y su coste.",
      c: "Algoritmos de ordenación.",
      w: "Clásico para entender diseño de algoritmos y complejidad.",
      df: "hard",
      m: 50,
      xp: 20,
      er: ["Reimplementar sort() en producción sin motivo."],
      cr: ["Explicas la diferencia de coste entre dos ordenaciones."],
      ex: ["Trazar a mano una ordenación por inserción."],
      ev: ["Ordenar por coste creciente varias estrategias."],
      r: [R.cs50("Sorting"), R.roadmap("Sorting")],
    },

    // ───────────── Estructuras de datos ─────────────
    {
      s: "prog-estructuras-intro",
      b: "estructuras",
      lv: 3,
      t: "Elegir la estructura correcta",
      pre: ["prog-diccionarios", "prog-complejidad"],
      d: "Cada estructura tiene fortalezas: elegir bien cambia el coste del programa.",
      o: "Escoger la estructura de datos adecuada para cada problema.",
      c: "Criterio de estructuras de datos.",
      w: "La estructura correcta simplifica el código y lo hace eficiente.",
      df: "hard",
      m: 45,
      xp: 22,
      er: ["Usar una lista para todo.", "Ignorar el coste de las operaciones."],
      cr: ["Justificas por qué eliges lista, dict o set en un caso."],
      ex: ["Elegir estructura para 3 problemas dados."],
      ev: ["Mapear operación → estructura óptima."],
      r: [R.roadmap("Data structures"), R.cs50("Data structures")],
    },
    {
      s: "prog-pilas-colas",
      b: "estructuras",
      lv: 3,
      t: "Pilas y colas",
      pre: ["prog-estructuras-intro"],
      d: "LIFO y FIFO: dos formas de ordenar el acceso muy usadas en la práctica.",
      o: "Usar pilas y colas para modelar procesos reales.",
      c: "Estructuras lineales.",
      w: "Deshacer, historial, tareas pendientes… se modelan con pilas/colas.",
      df: "hard",
      m: 45,
      xp: 20,
      er: ["Confundir el orden LIFO vs FIFO."],
      cr: ["Implementas una pila y una cola con una lista."],
      ex: ["Verificar paréntesis balanceados con una pila."],
      ev: ["Elegir pila o cola según el problema."],
      r: [R.roadmap("Stacks & queues")],
    },
    {
      s: "prog-listas-enlazadas",
      b: "estructuras",
      lv: 3,
      t: "Listas enlazadas",
      pre: ["prog-estructuras-intro"],
      d: "Nodos conectados por referencias; ventajas y costes frente a un array.",
      o: "Entender referencias y estructuras encadenadas.",
      c: "Estructuras enlazadas.",
      w: "Enseña referencias/punteros y prepara para árboles y grafos.",
      df: "hard",
      m: 50,
      xp: 22,
      er: ["Perder la referencia al insertar/borrar."],
      cr: ["Recorres e insertas en una lista enlazada simple."],
      ex: ["Insertar al inicio de una lista enlazada."],
      ev: ["Comparar coste de inserción array vs enlazada."],
      r: [R.roadmap("Linked lists")],
    },
    {
      s: "prog-hash",
      b: "estructuras",
      lv: 3,
      t: "Tablas hash",
      pre: ["prog-estructuras-intro"],
      d: "Cómo un diccionario logra acceso casi instantáneo por clave.",
      o: "Entender por qué el acceso por clave es tan rápido.",
      c: "Hashing.",
      w: "Explica el porqué de la eficiencia de dicts/sets, omnipresentes.",
      df: "hard",
      m: 45,
      xp: 20,
      er: ["Suponer orden en un dict/set."],
      cr: ["Explicas hashing y colisiones a alto nivel."],
      ex: ["Contar palabras con un diccionario (hash)."],
      ev: ["Justificar O(1) medio del acceso por clave."],
      r: [R.roadmap("Hash tables")],
    },
    {
      s: "prog-arboles-grafos",
      b: "estructuras",
      lv: 3,
      t: "Árboles y grafos",
      pre: ["prog-pilas-colas", "prog-recursion"],
      d: "Estructuras jerárquicas y de red; recorridos básicos.",
      o: "Modelar jerarquías y relaciones con árboles y grafos.",
      c: "Estructuras no lineales.",
      w: "Sistemas de archivos, redes sociales, rutas… son árboles/grafos.",
      df: "expert",
      m: 60,
      xp: 26,
      er: ["Recorridos sin marcar visitados (ciclos)."],
      cr: ["Recorres un árbol con recursión."],
      ex: ["Sumar los nodos de un árbol."],
      ev: ["Elegir árbol o grafo para un caso."],
      r: [R.roadmap("Trees & graphs"), R.cs50("Trees")],
    },

    // ───────────── Web: HTML, CSS y JavaScript ─────────────
    {
      s: "prog-como-web",
      b: "web",
      lv: 1,
      t: "Cómo funciona la web",
      pre: ["prog-que-es"],
      d: "Cliente y servidor, el navegador, URLs y qué pasa al abrir una página.",
      o: "Entender el modelo cliente-servidor de la web.",
      c: "Modelo mental de la web.",
      w: "Sin este mapa, HTML/CSS/JS y las APIs se aprenden a ciegas.",
      df: "easy",
      m: 35,
      xp: 12,
      er: ["Creer que el navegador 'ejecuta' el servidor."],
      cr: ["Explicas qué hace el navegador al abrir una URL."],
      ex: ["Dibujar el viaje de una petición web."],
      ev: ["Identificar cliente vs servidor en ejemplos."],
      r: [R.mdn("Cómo funciona la web"), R.odin("How the web works")],
    },
    {
      s: "prog-html",
      b: "web",
      lv: 1,
      t: "HTML: estructura",
      pre: ["prog-como-web"],
      d: "El esqueleto semántico de una página: etiquetas, jerarquía y significado.",
      o: "Estructurar contenido con HTML semántico.",
      c: "Marcado semántico.",
      w: "HTML es la base de toda la web y de la accesibilidad.",
      df: "easy",
      m: 45,
      xp: 15,
      er: ["Usar divs para todo (ignorar la semántica)."],
      cr: ["Construyes una página con encabezados, listas y enlaces."],
      ex: ["Maquetar una tarjeta de perfil en HTML."],
      ev: ["Corregir el HTML no semántico de un ejemplo."],
      r: [R.mdn("HTML"), R.odin("HTML foundations")],
    },
    {
      s: "prog-css",
      b: "web",
      lv: 2,
      t: "CSS: estilo y layout",
      pre: ["prog-html"],
      d: "Dar aspecto y disposición: selectores, caja, flexbox y responsive.",
      o: "Dar estilo y estructurar el layout de una página.",
      c: "Diseño de interfaces con CSS.",
      w: "Convierte el esqueleto HTML en una interfaz usable y atractiva.",
      df: "medium",
      m: 55,
      xp: 18,
      er: ["Luchar con el layout sin entender el modelo de caja."],
      cr: ["Maquetas un layout responsive con flexbox."],
      ex: ["Centrar y alinear una tarjeta con flexbox."],
      ev: ["Reproducir un diseño simple dado."],
      r: [R.mdn("CSS"), R.odin("CSS foundations")],
    },
    {
      s: "prog-js-navegador",
      b: "web",
      lv: 2,
      t: "JavaScript y el DOM",
      pre: ["prog-html", "prog-funciones"],
      d: "El lenguaje de la web: manipular la página (DOM) desde JavaScript.",
      o: "Modificar una página dinámicamente con JavaScript.",
      c: "Programación en el navegador.",
      w: "JS da vida a la web; el DOM es el puente entre código y página.",
      df: "medium",
      m: 55,
      xp: 20,
      er: ["Buscar un elemento antes de que exista en el DOM."],
      cr: ["Seleccionas y modificas elementos con JS."],
      ex: ["Cambiar un texto al pulsar un botón."],
      ev: ["Actualizar la página según una variable."],
      r: [R.mdn("JavaScript"), R.odin("JavaScript basics")],
    },
    {
      s: "prog-eventos",
      b: "web",
      lv: 3,
      t: "Eventos e interactividad",
      pre: ["prog-js-navegador"],
      d: "Responder a clics, teclado y formularios: la web se vuelve interactiva.",
      o: "Manejar eventos del usuario para crear interfaces vivas.",
      c: "Programación dirigida por eventos.",
      w: "Toda app web reacciona a eventos; es el corazón de la interactividad.",
      df: "medium",
      m: 50,
      xp: 20,
      er: ["Registrar el mismo evento varias veces."],
      cr: ["Construyes un componente interactivo (contador, lista)."],
      ex: ["Lista de tareas: añadir y borrar."],
      ev: ["Validar un formulario con eventos."],
      r: [R.mdn("Eventos"), R.odin("DOM & events")],
    },

    // ───────────── Bases de datos ─────────────
    {
      s: "prog-bd-que-es",
      b: "persistencia",
      lv: 2,
      t: "Qué es una base de datos",
      pre: ["prog-diccionarios"],
      d: "Guardar datos que perduran; tablas, filas y columnas; SQL vs NoSQL.",
      o: "Entender por qué y cuándo usar una base de datos.",
      c: "Persistencia de datos.",
      w: "Los datos de una app deben sobrevivir al cierre del programa.",
      df: "medium",
      m: 45,
      xp: 18,
      er: ["Guardar todo en archivos de texto sin estructura."],
      cr: ["Explicas tabla, fila, columna y clave primaria."],
      ex: ["Diseñar una tabla de usuarios."],
      ev: ["Elegir relacional vs NoSQL en un caso."],
      r: [R.sql("Bases de datos relacionales"), R.roadmap("Databases")],
    },
    {
      s: "prog-sql-select",
      b: "persistencia",
      lv: 2,
      t: "SQL: consultar (SELECT)",
      pre: ["prog-bd-que-es"],
      d: "Pedir datos con SELECT, WHERE, ORDER BY y LIMIT: el idioma de los datos.",
      o: "Consultar y filtrar datos con SQL.",
      c: "Consulta de datos.",
      w: "SQL es una habilidad universal y muy demandada.",
      df: "medium",
      m: 55,
      xp: 20,
      er: ["Olvidar el WHERE (traer toda la tabla)."],
      cr: ["Escribes consultas con filtro y orden."],
      ex: ["Obtener los 5 productos más caros."],
      ev: ["Traducir una pregunta a una consulta SQL."],
      r: [R.sql("SELECT queries"), R.mdn("SQL")],
    },
    {
      s: "prog-sql-escritura",
      b: "persistencia",
      lv: 3,
      t: "SQL: insertar y actualizar",
      pre: ["prog-sql-select"],
      d: "Modificar datos con INSERT, UPDATE y DELETE de forma segura.",
      o: "Crear, actualizar y borrar registros con SQL.",
      c: "Modificación de datos.",
      w: "Una app real no solo lee: escribe datos constantemente.",
      df: "medium",
      m: 45,
      xp: 20,
      er: ["UPDATE/DELETE sin WHERE (¡desastre!)."],
      cr: ["Insertas y actualizas registros con seguridad."],
      ex: ["Registrar un pedido nuevo."],
      ev: ["Corregir un DELETE peligroso."],
      r: [R.sql("Insertar y actualizar")],
    },
    {
      s: "prog-modelado",
      b: "persistencia",
      lv: 3,
      t: "Modelado relacional",
      pre: ["prog-sql-select"],
      d: "Relaciones entre tablas, claves foráneas y normalización básica.",
      o: "Diseñar un esquema relacional coherente.",
      c: "Diseño de datos.",
      w: "Un buen modelo evita datos duplicados e inconsistentes.",
      df: "hard",
      m: 55,
      xp: 22,
      er: ["Duplicar datos por no relacionar tablas."],
      cr: ["Diseñas dos tablas relacionadas con clave foránea."],
      ex: ["Modelar usuarios y sus pedidos."],
      ev: ["Detectar redundancia en un esquema."],
      r: [R.roadmap("Data modeling")],
    },

    // ───────────── APIs y la red ─────────────
    {
      s: "prog-http",
      b: "apis",
      lv: 2,
      t: "HTTP: cliente-servidor",
      pre: ["prog-como-web"],
      d: "El protocolo de la web: peticiones, respuestas, métodos y códigos de estado.",
      o: "Entender cómo dialogan cliente y servidor por HTTP.",
      c: "Comunicación en red.",
      w: "Toda API y app web habla HTTP; es alfabetización de red.",
      df: "medium",
      m: 45,
      xp: 18,
      er: ["Confundir 404 (no existe) con 500 (error del servidor)."],
      cr: ["Explicas una petición/respuesta HTTP con su método y código."],
      ex: ["Leer las peticiones en las herramientas del navegador."],
      ev: ["Emparejar código de estado con su significado."],
      r: [R.mdn("HTTP"), R.roadmap("HTTP")],
    },
    {
      s: "prog-json",
      b: "apis",
      lv: 2,
      t: "JSON",
      pre: ["prog-diccionarios"],
      d: "El formato en el que viajan los datos entre programas; parseo y serialización.",
      o: "Leer y producir datos en formato JSON.",
      c: "Intercambio de datos.",
      w: "JSON es el idioma común de las APIs; se parece a un diccionario.",
      df: "easy",
      m: 35,
      xp: 14,
      er: ["Comillas simples o comas finales inválidas en JSON."],
      cr: ["Conviertes entre objeto/diccionario y JSON."],
      ex: ["Serializar una ficha a JSON y volver."],
      ev: ["Detectar JSON inválido."],
      r: [R.mdn("JSON")],
    },
    {
      s: "prog-rest",
      b: "apis",
      lv: 3,
      t: "APIs REST",
      pre: ["prog-http", "prog-json"],
      d: "Recursos, verbos y URLs con sentido: el estilo dominante para APIs.",
      o: "Entender el diseño de una API REST.",
      c: "Diseño de APIs.",
      w: "Estándar de facto para conectar frontend, backend y servicios.",
      df: "hard",
      m: 45,
      xp: 20,
      er: ["Poner verbos en la URL (/getUsers)."],
      cr: ["Diseñas endpoints REST para un recurso."],
      ex: ["Definir la API de 'tareas' (CRUD)."],
      ev: ["Corregir un diseño de API no RESTful."],
      r: [R.roadmap("REST APIs")],
    },
    {
      s: "prog-consumir-api",
      b: "apis",
      lv: 3,
      t: "Consumir una API",
      pre: ["prog-rest"],
      d: "Hacer peticiones desde tu código y usar la respuesta (fetch/requests).",
      o: "Integrar datos de una API externa en tu programa.",
      c: "Integración de servicios.",
      w: "Casi toda app real combina datos de servicios externos.",
      df: "hard",
      m: 50,
      xp: 22,
      er: ["No manejar errores de red ni respuestas vacías."],
      cr: ["Consumes una API pública y muestras sus datos."],
      ex: ["Mostrar el clima desde una API."],
      ev: ["Manejar un fallo de la API con elegancia."],
      r: [R.mdn("Fetch"), R.py("requests")],
    },

    // ───────────── Calidad e ingeniería ─────────────
    {
      s: "prog-errores",
      b: "ingenieria",
      lv: 2,
      t: "Errores y excepciones",
      pre: ["prog-funciones"],
      d: "Tipos de error (sintaxis/ejecución/lógica); try/except.",
      o: "Leer errores y manejar excepciones sin que el programa muera.",
      c: "Robustez y manejo de errores.",
      w: "Todo programa falla; manejarlo distingue software frágil de fiable.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Ignorar el traceback.", "Capturar excepciones a ciegas."],
      cr: ["Lees el traceback de abajo arriba y usas try/except."],
      ex: ["Pedir un número a prueba de usuarios."],
      ev: ["Hacer robusto un programa que rompe con mala entrada."],
      r: [R.py("Errores y excepciones"), R.odin("Errors")],
    },
    {
      s: "prog-depuracion",
      b: "ingenieria",
      lv: 2,
      t: "Depuración",
      pre: ["prog-errores"],
      d: "Encontrar bugs con método: reproducir, hipótesis, prints, pato de goma.",
      o: "Localizar y corregir fallos de forma sistemática.",
      c: "Depuración metódica.",
      w: "La habilidad que más separa a un buen programador de uno frustrado.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Cambiar líneas al azar."],
      cr: ["Depuras por hipótesis y usas prints/depurador."],
      ex: ["Cazar un bug introducido a propósito."],
      ev: ["Explicar la causa raíz de un fallo."],
      r: [R.odin("Debugging"), R.py("pdb")],
    },
    {
      s: "prog-git",
      b: "ingenieria",
      lv: 2,
      t: "Control de versiones (Git)",
      pre: ["hito-prog-fundamentos"],
      d: "Historial de versiones y colaboración: add, commit, push, ramas.",
      o: "Guardar versiones de tu código y colaborar con Git.",
      c: "Control de versiones.",
      w: "Estándar de la industria; imprescindible para proyectos y equipo.",
      df: "medium",
      m: 45,
      xp: 16,
      er: ["Mensajes de commit vagos.", "No versionar hasta el final."],
      cr: ["Haces add + commit + push con mensajes claros."],
      ex: ["Inicializar un repo y registrar dos versiones."],
      ev: ["Explicar el flujo add→commit→push."],
      r: [R.git("Fundamentos de Git"), R.odin("Git basics")],
    },
    {
      s: "prog-testing",
      b: "ingenieria",
      lv: 3,
      t: "Testing",
      pre: ["prog-funciones", "prog-errores"],
      d: "Comprobar que tu código hace lo que crees, de forma automática y repetible.",
      o: "Escribir pruebas que verifican tu código automáticamente.",
      c: "Aseguramiento de calidad.",
      w: "Las pruebas dan confianza para cambiar código sin romper nada.",
      df: "hard",
      m: 55,
      xp: 22,
      er: ["Probar solo el 'camino feliz'.", "No probar los casos límite."],
      cr: ["Escribes pruebas que pasan y fallan cuando deben."],
      ex: ["Tests para una función de validación."],
      ev: ["Añadir un caso límite que destape un bug."],
      r: [R.py("unittest"), R.roadmap("Testing")],
    },
    {
      s: "prog-codigo-limpio",
      b: "ingenieria",
      lv: 3,
      t: "Código limpio",
      pre: ["prog-funciones"],
      d: "Nombres claros, funciones pequeñas y legibilidad: escribir para humanos.",
      o: "Escribir código legible y mantenible.",
      c: "Legibilidad y mantenibilidad.",
      w: "El código se lee más veces de las que se escribe; la claridad ahorra tiempo.",
      df: "medium",
      m: 45,
      xp: 20,
      er: ["Nombres crípticos.", "Funciones que hacen demasiado."],
      cr: ["Refactorizas un fragmento para hacerlo legible."],
      ex: ["Renombrar y dividir una función confusa."],
      ev: ["Revisar el código de otra persona con criterios claros."],
      r: [R.roadmap("Clean code"), R.odin("Clean code")],
    },
    {
      s: "prog-arquitectura",
      b: "ingenieria",
      lv: 3,
      t: "Arquitectura y patrones",
      pre: ["prog-oop", "prog-codigo-limpio"],
      d: "Organizar un proyecto grande: capas, separación de responsabilidades y patrones.",
      o: "Estructurar una aplicación de forma escalable.",
      c: "Arquitectura de software.",
      w: "Un buen diseño permite que un proyecto crezca sin volverse ingobernable.",
      df: "expert",
      m: 60,
      xp: 26,
      er: ["Aplicar patrones sin necesidad (sobreingeniería)."],
      cr: ["Divides una app en capas con responsabilidades claras."],
      ex: ["Separar lógica de datos y presentación en un proyecto."],
      ev: ["Justificar una decisión de arquitectura."],
      r: [R.roadmap("Architecture"), R.roadmap("Design patterns")],
    },

    // ───────────── Hitos ─────────────
    {
      s: "hito-prog-fundamentos",
      b: "hito",
      lv: 1,
      t: "Hito · Fundamentos",
      pre: [
        "prog-condicionales",
        "prog-bucles",
        "prog-listas",
        "prog-strings",
        "prog-entrada-salida",
      ],
      d: "Repaso integrado: datos, decisiones, repetición y colecciones.",
      o: "Confirmar los fundamentos antes de las funciones.",
      c: "Integración de fundamentos.",
      w: "Un hito consolida y asegura bases firmes antes de avanzar.",
      df: "medium",
      m: 40,
      xp: 20,
      er: ["Avanzar con lagunas en bucles o listas."],
      cr: ["Escribes un mini-programa que usa los cuatro pilares."],
      ex: ["Promedio de notas con lista + bucle + if."],
      ev: ["Autoevaluación de los descriptores de Fundamentos."],
      r: [R.cs50("Repaso de fundamentos")],
    },
    {
      s: "hito-prog-intermedio",
      b: "hito",
      lv: 2,
      t: "Hito · Intermedio",
      pre: [
        "prog-funciones",
        "prog-diccionarios",
        "prog-errores",
        "prog-algoritmos",
      ],
      d: "Repaso integrado: funciones, estructuras, robustez y diseño.",
      o: "Confirmar el nivel intermedio antes de lo avanzado.",
      c: "Integración de nivel intermedio.",
      w: "Consolida las piezas que ya construyen aplicaciones reales.",
      df: "hard",
      m: 50,
      xp: 25,
      er: ["Avanzar a especializaciones sin dominar funciones y estructuras."],
      cr: ["Construyes una mini-app (agenda) con funciones + diccionario + errores."],
      ex: ["Agenda de contactos a prueba de fallos."],
      ev: ["Autoevaluación de los descriptores de Intermedio."],
      r: [R.cs50("Repaso intermedio")],
    },
    {
      s: "prog-proyecto",
      b: "hito",
      lv: 3,
      t: "Proyecto integrador",
      pre: ["hito-prog-intermedio", "prog-oop"],
      d: "Integrar todo en un proyecto real de principio a fin, versionado con Git.",
      o: "Construir y publicar un proyecto propio completo.",
      c: "Integración y entrega de un proyecto.",
      w: "Aprender de verdad se demuestra construyendo algo que funciona y se comparte.",
      df: "expert",
      m: 240,
      xp: 40,
      er: ["Empezar sin definir el alcance.", "No versionar ni probar."],
      cr: ["Entregas un proyecto funcional en un repositorio con historial."],
      ex: ["App de consola o web: to-do, quiz o gestor de gastos."],
      ev: ["Demo del proyecto + repositorio con commits claros."],
      r: [R.odin("Build a project"), R.git("Publicar en GitHub")],
    },
    {
      s: "hito-prog-profesional",
      b: "hito",
      lv: 3,
      t: "Hito · Nivel profesional",
      pre: ["prog-proyecto", "prog-testing", "prog-git"],
      d: "Cierre: piensas en calidad, pruebas, versiones y diseño como un profesional.",
      o: "Confirmar prácticas de ingeniería de nivel profesional.",
      c: "Madurez de ingeniería.",
      w: "Programar bien no es solo que funcione: es mantenible, probado y colaborativo.",
      df: "expert",
      m: 60,
      xp: 40,
      er: ["Entregar sin pruebas ni control de versiones."],
      cr: ["Tu proyecto tiene pruebas, historial Git y código legible."],
      ex: ["Añadir tests y un README a tu proyecto."],
      ev: ["Autoevaluación de prácticas profesionales."],
      r: [R.roadmap("Backend/Frontend roadmap")],
    },
  ],
};
