/**
 * Árbol de habilidades: **Programación (base: Python)**.
 *
 * Currículo tipo bootcamp fundamentado en fuentes reconocidas: documentación
 * oficial de Python (docs.python.org), Harvard CS50, MIT 6.0001, The Odin
 * Project, freeCodeCamp, MDN y "Automate the Boring Stuff" (Sweigart). Se
 * organiza por hebras de competencia (fundamentos, datos, control de flujo,
 * funciones, estructuras, algoritmos, calidad, herramientas, paradigmas) y se
 * cruza por hitos de nivel (Fundamentos → Básico → Intermedio → Avanzado).
 *
 * Usa el motor de sembrado genérico (`./lib`), reutilizable por cualquier
 * disciplina. El contenido interactivo vive en `./programacion-lessons`.
 */

import type { SeedRes, TreeSpec } from "./lib";
import { PROG_LESSONS } from "./programacion-lessons";

const R = {
  py: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://docs.python.org/es/3/tutorial/",
    p: "Python (oficial)",
  }),
  cs50: (title: string): SeedRes => ({
    t: "VIDEO",
    title,
    url: "https://cs50.harvard.edu/python/",
    p: "Harvard CS50",
  }),
  fcc: (title: string): SeedRes => ({
    t: "EXERCISE",
    title,
    url: "https://www.freecodecamp.org/learn/scientific-computing-with-python/",
    p: "freeCodeCamp",
  }),
  odin: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://www.theodinproject.com/",
    p: "The Odin Project",
  }),
  automate: (title: string): SeedRes => ({
    t: "BOOK",
    title,
    url: "https://automatetheboringstuff.com/",
    p: "Automate the Boring Stuff",
  }),
  mdn: (title: string): SeedRes => ({
    t: "ARTICLE",
    title,
    url: "https://developer.mozilla.org/es/docs/Learn",
    p: "MDN",
  }),
  git: (title: string): SeedRes => ({
    t: "BOOK",
    title,
    url: "https://git-scm.com/book/es/v2",
    p: "Pro Git",
  }),
};

export const PROGRAMACION_SPEC: TreeSpec = {
  category: {
    slug: "programacion",
    name: "Programación",
    description: "Aprende a crear software desde cero: lógica, código y buenas prácticas.",
    icon: "💻",
    order: 1,
  },
  tree: {
    slug: "python-desde-cero",
    title: "Programación · de cero a proyectos (Python)",
    description:
      "Aprende a programar como se aprende de verdad: pensando soluciones y escribiendo código. De los fundamentos (variables, decisiones, bucles) a funciones, estructuras de datos, manejo de errores y tus primeros proyectos, con Python.",
    difficulty: "beginner",
  },
  branches: {
    fund: "Fundamentos",
    datos: "Datos y variables",
    control: "Control de flujo",
    func: "Funciones",
    estructuras: "Estructuras de datos",
    algoritmos: "Algoritmos",
    calidad: "Depuración y calidad",
    herramientas: "Herramientas",
    paradigmas: "Paradigmas",
    hito: "Hitos",
  },
  levels: ["Fundamentos", "Básico", "Intermedio", "Avanzado"],
  lessons: PROG_LESSONS,
  nodes: [
    // ───────── Fundamentos ─────────
    {
      s: "prog-que-es",
      b: "fund",
      lv: 0,
      t: "Qué es programar",
      root: true,
      pre: [],
      d: "Qué es un programa y cómo 'piensa' (literalmente) una computadora.",
      o: "Entender qué es un programa y el ciclo de ejecución.",
      c: "Modelo mental de la computación.",
      w: "Es la raíz: sin un modelo mental correcto (la máquina es literal), todo lo demás confunde.",
      df: "easy",
      m: 30,
      xp: 10,
      er: ["Creer que la máquina 'entiende' intenciones.", "Memorizar sin ejecutar."],
      cr: ["Explicas qué es un programa y ejecutas tu primera línea."],
      ex: ["Escribir y ejecutar un print()."],
      ev: ["Explicar con tus palabras qué hace un programa."],
      r: [R.cs50("Scratch/So bienvenida a CS50"), R.py("El intérprete de Python")],
    },
    {
      s: "prog-pensamiento",
      b: "fund",
      lv: 0,
      t: "Pensamiento computacional",
      pre: ["prog-que-es"],
      d: "Descomponer problemas, ver patrones, abstraer y escribir algoritmos.",
      o: "Descomponer un problema en pasos ordenados (pseudocódigo).",
      c: "Resolución estructurada de problemas.",
      w: "Programar es pensar antes que teclear; esta habilidad sostiene todo el árbol.",
      df: "easy",
      m: 40,
      xp: 12,
      er: ["Empezar a codificar sin plan.", "Saltarse pasos 'obvios'."],
      cr: ["Escribes el algoritmo de una tarea cotidiana sin ambigüedad."],
      ex: ["Pseudocódigo de una receta paso a paso."],
      ev: ["Que otra persona siga tu algoritmo literalmente."],
      r: [R.cs50("Computational thinking"), R.odin("How to think about programming")],
    },
    {
      s: "prog-entorno",
      b: "herramientas",
      lv: 0,
      t: "Tu entorno: ejecutar código",
      pre: ["prog-que-es"],
      d: "Dónde escribir y ejecutar Python; el ciclo escribir→ejecutar→ver.",
      o: "Ejecutar tu propio código y leer su salida.",
      c: "Manejo del entorno de desarrollo.",
      w: "Sin poder ejecutar y ver resultados, no hay práctica ni retroalimentación.",
      df: "easy",
      m: 30,
      xp: 10,
      er: ["Instalar todo antes de escribir una línea.", "No leer la salida."],
      cr: ["Ejecutas código y comentas líneas con #."],
      ex: ["Imprimir texto y una operación; añadir comentarios."],
      ev: ["Ejecutar un script corto y explicar su salida."],
      r: [R.py("Usar el intérprete"), R.automate("Setting up")],
    },

    // ───────── Básico ─────────
    {
      s: "prog-variables",
      b: "datos",
      lv: 1,
      t: "Variables y tipos",
      pre: ["prog-entorno", "prog-pensamiento"],
      d: "Guardar datos con variables; tipos str, int, float, bool.",
      o: "Guardar y reutilizar datos eligiendo el tipo correcto.",
      c: "Manejo de datos y memoria del programa.",
      w: "Las variables son la memoria: todo programa guarda y transforma datos.",
      df: "easy",
      m: 40,
      xp: 12,
      er: ["Confundir '42' (texto) con 42 (número).", "Nombres crípticos (x, a)."],
      cr: ["Creas variables de cada tipo y las combinas en una frase."],
      ex: ["Ficha de datos con str/int/float y type()."],
      ev: ["Predecir el tipo de varias expresiones."],
      r: [R.py("Tipos numéricos y de texto"), R.fcc("Variables")],
    },
    {
      s: "prog-operadores",
      b: "datos",
      lv: 1,
      t: "Operadores y expresiones",
      pre: ["prog-variables"],
      d: "Aritméticos (+ - * / // % **) y de comparación (== != < >).",
      o: "Calcular y comparar valores; distinguir = de ==.",
      c: "Cálculo y evaluación de expresiones.",
      w: "Los operadores son cómo el programa 'razona'; base de las decisiones.",
      df: "easy",
      m: 35,
      xp: 12,
      er: ["Usar = para comparar (es ==).", "Confundir / (decimal) con // (entero)."],
      cr: ["Predices el resultado de //, %, ** y comparaciones."],
      ex: ["Comprobar paridad con %; potencias con **."],
      ev: ["Evaluar expresiones mixtas a mano y verificar."],
      r: [R.py("Operadores"), R.fcc("Arithmetic")],
    },
    {
      s: "prog-entrada-salida",
      b: "datos",
      lv: 1,
      t: "Entrada y salida",
      pre: ["prog-variables"],
      d: "Mostrar con print() y pedir datos con input() (y convertirlos).",
      o: "Interactuar con el usuario: mostrar y recibir datos.",
      c: "Interacción básica programa–usuario.",
      w: "Un programa útil dialoga; convertir la entrada evita errores de tipo.",
      df: "easy",
      m: 30,
      xp: 12,
      er: ["Olvidar que input() da texto.", "Sumar texto con número."],
      cr: ["Pides un número, lo conviertes y calculas con él."],
      ex: ["Saludo personalizado con nombre y edad."],
      ev: ["Programa que pide datos y responde sin romperse."],
      r: [R.py("input y print"), R.automate("Input/Output")],
    },
    {
      s: "prog-strings",
      b: "datos",
      lv: 1,
      t: "Cadenas de texto",
      pre: ["prog-variables"],
      d: "Concatenar, medir (len), f-strings, métodos e indexado.",
      o: "Manipular texto: unir, medir y transformar cadenas.",
      c: "Procesamiento de texto.",
      w: "El texto está en todos los programas; dominarlo es una habilidad diaria.",
      df: "easy",
      m: 40,
      xp: 12,
      er: ["Concatenar en vez de usar f-strings.", "Olvidar que se indexa desde 0."],
      cr: ["Usas f-strings y métodos (.upper, .strip) con soltura."],
      ex: ["Tarjeta de presentación con f-strings y .upper()."],
      ev: ["Transformar un texto según reglas dadas."],
      r: [R.py("Cadenas de texto"), R.fcc("Strings")],
    },
    {
      s: "prog-condicionales",
      b: "control",
      lv: 1,
      t: "Condicionales (if/elif/else)",
      pre: ["prog-operadores"],
      d: "Tomar decisiones según condiciones; indentación de bloques.",
      o: "Ejecutar código distinto según se cumpla una condición.",
      c: "Toma de decisiones (control de flujo).",
      w: "Aquí el código empieza a 'decidir'; base de toda lógica.",
      df: "medium",
      m: 45,
      xp: 15,
      er: ["Indentación incorrecta.", "Usar = en la condición en vez de ==."],
      cr: ["Escribes if/elif/else correctos y combinas con and/or."],
      ex: ["Clasificar un número (positivo/negativo/cero, par/impar)."],
      ev: ["Programa que decide entre 3+ casos."],
      r: [R.py("if/elif/else"), R.fcc("Conditional logic")],
    },
    {
      s: "prog-bucles",
      b: "control",
      lv: 1,
      t: "Bucles (for/while)",
      pre: ["prog-condicionales"],
      d: "Repetir con for y range(); repetir con while; evitar bucles infinitos.",
      o: "Repetir acciones de forma controlada.",
      c: "Iteración (control de flujo).",
      w: "La repetición es lo que hace potente a la computación; imprescindible.",
      df: "medium",
      m: 45,
      xp: 15,
      er: ["Error por uno (off-by-one) con range.", "Bucle infinito por no actualizar la condición."],
      cr: ["Usas for y while correctamente; controlas la parada."],
      ex: ["Tabla de multiplicar con for y con while."],
      ev: ["Sumar/contar recorriendo con un bucle."],
      r: [R.py("Bucles for y while"), R.fcc("Loops")],
    },
    {
      s: "prog-listas",
      b: "estructuras",
      lv: 1,
      t: "Listas",
      pre: ["prog-bucles"],
      d: "Colecciones ordenadas: crear, indexar (desde 0), append, recorrer.",
      o: "Almacenar y recorrer colecciones ordenadas.",
      c: "Estructuras de datos secuenciales.",
      w: "La estructura de datos que más usarás; encaja de forma natural con los bucles.",
      df: "medium",
      m: 45,
      xp: 15,
      er: ["Olvidar que el índice empieza en 0.", "Salirse de rango (IndexError)."],
      cr: ["Creas, modificas y recorres listas con for."],
      ex: ["Lista de la compra: añadir, contar, recorrer."],
      ev: ["Procesar una lista (sumar, filtrar) con un bucle."],
      r: [R.py("Listas"), R.fcc("Lists")],
    },
    {
      s: "hito-prog-fundamentos",
      b: "hito",
      lv: 1,
      t: "Hito · Fundamentos",
      pre: [
        "prog-condicionales",
        "prog-bucles",
        "prog-listas",
        "prog-strings",
        "prog-entrada-salida",
      ],
      d: "Repaso integrado: datos, decisiones, repetición y colecciones.",
      o: "Confirmar los fundamentos antes de las funciones.",
      c: "Integración de fundamentos.",
      w: "Un hito consolida y motiva; asegura bases firmes antes de avanzar.",
      df: "medium",
      m: 40,
      xp: 20,
      er: ["Avanzar con lagunas en bucles o listas."],
      cr: ["Escribes un mini-programa que usa los cuatro pilares."],
      ex: ["Promedio de notas con lista + bucle + if."],
      ev: ["Autoevaluación de los descriptores de Fundamentos."],
      r: [R.cs50("Repaso de fundamentos")],
    },

    // ───────── Intermedio ─────────
    {
      s: "prog-funciones",
      b: "func",
      lv: 2,
      t: "Funciones",
      pre: ["hito-prog-fundamentos"],
      d: "Definir (def), parámetros, argumentos y return; reutilización.",
      o: "Encapsular y reutilizar lógica con funciones.",
      c: "Modularidad y reutilización.",
      w: "La herramienta nº1 contra la repetición y el desorden; puerta a programas grandes.",
      df: "medium",
      m: 50,
      xp: 18,
      er: ["Confundir print con return.", "Funciones que hacen demasiadas cosas."],
      cr: ["Escribes funciones con parámetros y return, y las reutilizas."],
      ex: ["area_rectangulo(base, altura) que devuelve el área."],
      ev: ["Refactorizar código repetido en funciones."],
      r: [R.py("Definir funciones"), R.fcc("Functions")],
    },
    {
      s: "prog-diccionarios",
      b: "estructuras",
      lv: 2,
      t: "Diccionarios y conjuntos",
      pre: ["prog-listas", "prog-funciones"],
      d: "Pares clave→valor; cuándo usar dict vs lista; pertenencia.",
      o: "Guardar y consultar datos por clave.",
      c: "Estructuras de datos asociativas.",
      w: "Modela datos etiquetados (una agenda, un JSON); complementa a las listas.",
      df: "medium",
      m: 45,
      xp: 18,
      er: ["Acceder a una clave inexistente (KeyError).", "Usar lista cuando toca dict."],
      cr: ["Creas y consultas diccionarios; eliges dict vs lista."],
      ex: ["Ficha de datos como diccionario; recorrer pares."],
      ev: ["Contar frecuencias con un diccionario."],
      r: [R.py("Diccionarios"), R.fcc("Dictionaries")],
    },
    {
      s: "prog-errores",
      b: "calidad",
      lv: 2,
      t: "Errores y excepciones",
      pre: ["prog-funciones"],
      d: "Tipos de error (sintaxis/ejecución/lógica); try/except.",
      o: "Leer errores y manejar excepciones sin que el programa muera.",
      c: "Robustez y manejo de errores.",
      w: "Todo programa falla; manejarlo distingue software frágil de fiable.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Ignorar el traceback.", "Capturar excepciones 'a ciegas'."],
      cr: ["Lees el traceball de abajo arriba y usas try/except."],
      ex: ["Pedir un número a prueba de usuarios (try/except)."],
      ev: ["Hacer robusto un programa que rompe con mala entrada."],
      r: [R.py("Errores y excepciones"), R.odin("Debugging & errors")],
    },
    {
      s: "prog-depuracion",
      b: "calidad",
      lv: 2,
      t: "Depuración",
      pre: ["prog-errores"],
      d: "Encontrar bugs con método: reproducir, hipótesis, prints, pato de goma.",
      o: "Localizar y corregir fallos de forma sistemática.",
      c: "Depuración metódica.",
      w: "La habilidad que más separa a un buen programador de uno frustrado.",
      df: "medium",
      m: 40,
      xp: 18,
      er: ["Cambiar líneas al azar.", "No reproducir el fallo antes de tocar."],
      cr: ["Depuras por hipótesis y usas prints para inspeccionar."],
      ex: ["Cazar un bug introducido a propósito."],
      ev: ["Explicar la causa raíz de un fallo y su arreglo."],
      r: [R.odin("Debugging"), R.py("El módulo pdb")],
    },
    {
      s: "prog-algoritmos",
      b: "algoritmos",
      lv: 2,
      t: "Pensar algoritmos",
      pre: ["prog-funciones", "prog-bucles"],
      d: "Diseñar la solución antes de codificar; patrones acumulador/búsqueda/filtro.",
      o: "Diseñar y validar una solución antes de escribir código.",
      c: "Diseño de algoritmos.",
      w: "Codificar es fácil; diseñar bien la solución es lo que de verdad distingue.",
      df: "hard",
      m: 55,
      xp: 20,
      er: ["Teclear sin plan.", "No probar la lógica con un ejemplo a mano."],
      cr: ["Escribes pseudocódigo con patrones y lo traduces a Python."],
      ex: ["Contar pares en una lista (acumulador + filtro)."],
      ev: ["Resolver un problema nuevo diseñando primero."],
      r: [R.cs50("Algorithms"), R.odin("Problem solving")],
    },
    {
      s: "prog-git",
      b: "herramientas",
      lv: 2,
      t: "Control de versiones (Git)",
      pre: ["hito-prog-fundamentos"],
      d: "Historial de versiones y colaboración: add, commit, push.",
      o: "Guardar versiones de tu código y entender el flujo básico de Git.",
      c: "Control de versiones.",
      w: "Estándar de la industria; imprescindible para proyectos y trabajo en equipo.",
      df: "medium",
      m: 45,
      xp: 15,
      er: ["Mensajes de commit vagos ('cambios').", "No versionar hasta el final."],
      cr: ["Haces add + commit + push con mensajes claros."],
      ex: ["Inicializar un repo y registrar dos versiones."],
      ev: ["Explicar el flujo add→commit→push."],
      r: [R.git("Fundamentos de Git"), R.odin("Git basics")],
    },
    {
      s: "prog-modulos",
      b: "paradigmas",
      lv: 2,
      t: "Módulos y librerías",
      pre: ["prog-funciones"],
      d: "Reutilizar código ajeno: import, la librería estándar y pip.",
      o: "Aprovechar módulos y librerías en tus programas.",
      c: "Reutilización a gran escala.",
      w: "No reinventes la rueda: la potencia de Python está en su ecosistema.",
      df: "medium",
      m: 40,
      xp: 16,
      er: ["Reescribir lo que ya existe.", "Confundir módulo con función."],
      cr: ["Importas y usas un módulo estándar (p. ej. random, math)."],
      ex: ["Usar random para un juego de adivinar el número."],
      ev: ["Resolver una tarea apoyándote en la librería estándar."],
      r: [R.py("Módulos"), R.py("La librería estándar")],
    },
    {
      s: "hito-prog-intermedio",
      b: "hito",
      lv: 2,
      t: "Hito · Intermedio",
      pre: [
        "prog-funciones",
        "prog-diccionarios",
        "prog-errores",
        "prog-algoritmos",
      ],
      d: "Repaso integrado: funciones, estructuras, robustez y diseño.",
      o: "Confirmar el nivel intermedio antes de lo avanzado.",
      c: "Integración de nivel intermedio.",
      w: "Consolida las piezas que ya construyen aplicaciones reales.",
      df: "hard",
      m: 50,
      xp: 25,
      er: ["Avanzar a OOP sin dominar funciones y estructuras."],
      cr: ["Construyes una mini-app (agenda) con funciones + diccionario + errores."],
      ex: ["Agenda de contactos: añadir, buscar, listar (a prueba de fallos)."],
      ev: ["Autoevaluación de los descriptores de Intermedio."],
      r: [R.cs50("Repaso intermedio")],
    },

    // ───────── Avanzado (ficha; lección en próximas iteraciones) ─────────
    {
      s: "prog-oop",
      b: "paradigmas",
      lv: 3,
      t: "Programación orientada a objetos",
      pre: ["hito-prog-intermedio"],
      d: "Clases y objetos: modelar el mundo con datos + comportamiento.",
      o: "Modelar entidades con clases, atributos y métodos.",
      c: "Paradigma orientado a objetos.",
      w: "Organiza programas grandes; base de la mayoría de frameworks modernos.",
      df: "hard",
      m: 70,
      xp: 25,
      er: ["Meter todo en una sola clase gigante.", "Confundir clase con instancia."],
      cr: ["Defines una clase con atributos y métodos y creas objetos."],
      ex: ["Clase Cuenta con depositar() y retirar()."],
      ev: ["Modelar un dominio simple con 2-3 clases."],
      r: [R.py("Clases"), R.odin("OOP basics")],
    },
    {
      s: "prog-complejidad",
      b: "algoritmos",
      lv: 3,
      t: "Eficiencia (Big-O intuitivo)",
      pre: ["prog-algoritmos", "prog-diccionarios"],
      d: "Por qué unas soluciones escalan y otras no; coste de listas vs dicts.",
      o: "Razonar de forma intuitiva sobre el coste de un algoritmo.",
      c: "Análisis de eficiencia.",
      w: "Con datos grandes, la eficiencia decide si tu programa es usable.",
      df: "hard",
      m: 60,
      xp: 22,
      er: ["Optimizar antes de que funcione.", "Ignorar el coste de operaciones."],
      cr: ["Comparas dos soluciones y explicas cuál escala mejor y por qué."],
      ex: ["Buscar en lista vs en diccionario y cronometrar."],
      ev: ["Clasificar algoritmos por su crecimiento (intuitivo)."],
      r: [R.cs50("Algorithms & efficiency")],
    },
    {
      s: "prog-proyecto",
      b: "hito",
      lv: 3,
      t: "Proyecto final",
      pre: ["hito-prog-intermedio", "prog-oop"],
      d: "Integrar todo en un proyecto real de principio a fin, versionado con Git.",
      o: "Construir y publicar un proyecto propio completo.",
      c: "Integración y entrega de un proyecto.",
      w: "Aprender de verdad se demuestra construyendo algo que funciona y se comparte.",
      df: "expert",
      m: 240,
      xp: 40,
      er: ["Empezar sin definir el alcance.", "No versionar ni probar."],
      cr: ["Entregas un proyecto funcional en un repositorio con historial."],
      ex: ["App de consola: to-do, quiz o gestor de gastos."],
      ev: ["Demo del proyecto + repositorio con commits claros."],
      r: [R.odin("Build a project"), R.git("Publicar en GitHub")],
    },
  ],
};
